export const aguai_neighborhoods = [
    {value: "BENEDITO MAMEDE JÚNIOR", label: "BENEDITO MAMEDE JÚNIOR", main: "false"},
    {value: "CECAP", label: "CECAP", main: "false"},
    {value: "CENTRO", label: "CENTRO", main: "false"},
    {value: "CIDADE NOVA", label: "CIDADE NOVA", main: "false"},
    {value: "DIVA ASSAD", label: "DIVA ASSAD", main: "false"},
    {value: "DOS ANJOS", label: "DOS ANJOS", main: "false"},
    {value: "JARDIM AEROPORTO", label: "JARDIM AEROPORTO", main: "false"},
    {value: "JARDIM BELA VISTA", label: "JARDIM BELA VISTA", main: "false"},
    {value: "JARDIM CARLOTA REHDER", label: "JARDIM CARLOTA REHDER", main: "false"},
    {value: "JARDIM CENTER CITY", label: "JARDIM CENTER CITY", main: "false"},
    {value: "JARDIM DAS FLORES", label: "JARDIM DAS FLORES", main: "false"},
    {value: "JARDIM DO EDEN", label: "JARDIM DO EDEN", main: "false"},
    {value: "JARDIM DOS ALPES", label: "JARDIM DOS ALPES", main: "false"},
    {value: "JARDIM MONTE LÍBANO", label: "JARDIM MONTE LÍBANO", main: "false"},
    {value: "JARDIM MONTEVIDEO", label: "JARDIM MONTEVIDEO", main: "false"},
    {value: "JARDIM NOVAGUAÍ", label: "JARDIM NOVAGUAÍ", main: "false"},
    {value: "JARDIM PLANALTO", label: "JARDIM PLANALTO", main: "false"},
    {value: "JARDIM PRIMAVERA", label: "JARDIM PRIMAVERA", main: "false"},
    {value: "JARDIM SANTA MARIA", label: "JARDIM SANTA MARIA", main: "false"},
    {value: "JARDIM SANTA PAULA", label: "JARDIM SANTA PAULA", main: "false"},
    {value: "JARDIM SANTA ÚRSULA", label: "JARDIM SANTA ÚRSULA", main: "false"},
    {value: "JARDIM VISTA DA COLINA", label: "JARDIM VISTA DA COLINA", main: "false"},
    {value: "LAGOA SECA", label: "LAGOA SECA", main: "false"},
    {value: "PARQUE DAS PALMEIRAS", label: "PARQUE DAS PALMEIRAS", main: "false"},
    {value: "PARQUE MIGUELITO", label: "PARQUE MIGUELITO", main: "false"},
    {value: "PORTAL DOS LAGOS", label: "PORTAL DOS LAGOS", main: "false"},
    {value: "SIRIRI", label: "SIRIRI", main: "false"},
    {value: "TEOTÔNIO VILELA", label: "TEOTÔNIO VILELA", main: "false"},
    {value: "VILA BOM GOSTO", label: "VILA BOM GOSTO", main: "false"},
    {value: "VILA BRAGA", label: "VILA BRAGA", main: "false"},
    {value: "VILA NOVA", label: "VILA NOVA", main: "false"},
    {value: "VILA NOVA AMÉRICA", label: "VILA NOVA AMÉRICA", main: "false"},
    {value: "VILA PARAISO", label: "VILA PARAISO", main: "false"},
    {value: "VILA REGINA", label: "VILA REGINA", main: "false"},
    {value: "VILA REHDER", label: "VILA REHDER", main: "false"},
    {value: "VILA SÃO JOSÉ", label: "VILA SÃO JOSÉ", main: "false"},
]


export const sjbv_neighborhoods = [
    {value: "ALTO DA BOA VISTA", label: "ALTO DA BOA VISTA", main: "false"},
    {value: "ALTO DA PAULISTA", label: "ALTO DA PAULISTA", main: "false"},
    {value: "BAIRRO ALEGRE", label: "BAIRRO ALEGRE", main: "false"},
    {value: "BAIRRO DO ROSÁRIO", label: "BAIRRO DO ROSÁRIO", main: "false"},
    {value: "CENTRO", label: "CENTRO", main: "false"},
    {value: "COLINAS DA MANTIQUEIRA", label: "COLINAS DA MANTIQUEIRA", main: "false"},
    {value: "COLINAS DO ALEGRE", label: "COLINAS DO ALEGRE", main: "false"},
    {value: "CONDOMÍNIO MORRO AZUL", label: "CONDOMÍNIO MORRO AZUL", main: "false"},
    {value: "CONDOMÍNIO MORRO AZUL II", label: "CONDOMÍNIO MORRO AZUL II", main: "false"},
    {value: "CONDOMÍNIO SERRA DO PRATA", label: "CONDOMÍNIO SERRA DO PRATA", main: "false"},
    {value: "CONDOMÍNIO VISTA DA SERRA", label: "CONDOMÍNIO VISTA DA SERRA", main: "false"},
    {value: "D.E.R", label: "D.E.R", main: "false"},
    {value: "DISTRITO INDUSTRIAL", label: "DISTRITO INDUSTRIAL", main: "false"},
    {value: "JARDIM AEROPORTO", label: "JARDIM AEROPORTO", main: "false"},
    {value: "JARDIM AEROPORTO ELDORADO", label: "JARDIM AEROPORTO ELDORADO", main: "false"},
    {value: "JARDIM ALMEIDA", label: "JARDIM ALMEIDA", main: "false"},
    {value: "JARDIM AMERICA DO SUL", label: "JARDIM AMERICA DO SUL", main: "false"},
    {value: "JARDIM AMÉLIA", label: "JARDIM AMÉLIA", main: "false"},
    {value: "JARDIM AURORA", label: "JARDIM AURORA", main: "false"},
    {value: "JARDIM BELA VISTA", label: "JARDIM BELA VISTA", main: "false"},
    {value: "JARDIM BELVEDERE", label: "JARDIM BELVEDERE", main: "false"},
    {value: "JARDIM BOA VISTA", label: "JARDIM BOA VISTA", main: "false"},
    {value: "JARDIM CANADÁ", label: "JARDIM CANADÁ", main: "false"},
    {value: "JARDIM CLEDIRNA", label: "JARDIM CLEDIRNA", main: "false"},
    {value: "JARDIM CREPÚSCULO", label: "JARDIM CREPÚSCULO", main: "false"},
    {value: "JARDIM DA GLÓRIA", label: "JARDIM DA GLÓRIA", main: "false"},
    {value: "JARDIM DAS ACÁCIAS", label: "JARDIM DAS ACÁCIAS", main: "false"},
    {value: "JARDIM DAS AMOREIRAS", label: "JARDIM DAS AMOREIRAS", main: "false"},
    {value: "JARDIM DAS AZALÉIAS", label: "JARDIM DAS AZALÉIAS", main: "false"},
    {value: "JARDIM DAS BROMÉLIAS", label: "JARDIM DAS BROMÉLIAS", main: "false"},
    {value: "JARDIM DAS FLORES", label: "JARDIM DAS FLORES", main: "false"},
    {value: "JARDIM DAS HORTÊNCIAS", label: "JARDIM DAS HORTÊNCIAS", main: "false"},
    {value: "JARDIM DAS MACAUBEIRAS", label: "JARDIM DAS MACAUBEIRAS", main: "false"},
    {value: "JARDIM DAS MANGUEIRAS", label: "JARDIM DAS MANGUEIRAS", main: "false"},
    {value: "JARDIM DAS PAINEIRAS", label: "JARDIM DAS PAINEIRAS", main: "false"},
    {value: "JARDIM DAS ROSAS", label: "JARDIM DAS ROSAS", main: "false"},
    {value: "JARDIM DAS TULIPAS", label: "JARDIM DAS TULIPAS", main: "false"},
    {value: "JARDIM DEL PLATA", label: "JARDIM DEL PLATA", main: "false"},
    {value: "JARDIM DO TREVO", label: "JARDIM DO TREVO", main: "false"},
    {value: "JARDIM DONA TEREZA", label: "JARDIM DONA TEREZA", main: "false"},
    {value: "JARDIM DOS COMERCIÁRIOS", label: "JARDIM DOS COMERCIÁRIOS", main: "false"},
    {value: "JARDIM DOS EUCALIPTOS", label: "JARDIM DOS EUCALIPTOS", main: "false"},
    {value: "JARDIM DOS IPÊS", label: "JARDIM DOS IPÊS", main: "false"},
    {value: "JARDIM DOS JACARANDÁS", label: "JARDIM DOS JACARANDÁS", main: "false"},
    {value: "JARDIM DOS REIS", label: "JARDIM DOS REIS", main: "false"},
    {value: "JARDIM ELDORADO", label: "JARDIM ELDORADO", main: "false"},
    {value: "JARDIM EUROPA", label: "JARDIM EUROPA", main: "false"},
    {value: "JARDIM FLAMBOYANT", label: "JARDIM FLAMBOYANT", main: "false"},
    {value: "JARDIM FLEMING", label: "JARDIM FLEMING", main: "false"},
    {value: "JARDIM GUANABARA", label: "JARDIM GUANABARA", main: "false"},
    {value: "JARDIM INDUSTRIAL", label: "JARDIM INDUSTRIAL", main: "false"},
    {value: "JARDIM ITÁLIA", label: "JARDIM ITÁLIA", main: "false"},
    {value: "JARDIM LEONOR", label: "JARDIM LEONOR", main: "false"},
    {value: "JARDIM LUCAS TEIXEIRA", label: "JARDIM LUCAS TEIXEIRA", main: "false"},
    {value: "JARDIM MAGALHÃES", label: "JARDIM MAGALHÃES", main: "false"},
    {value: "JARDIM MICHELAZZO", label: "JARDIM MICHELAZZO", main: "false"},
    {value: "JARDIM MOLINARI", label: "JARDIM MOLINARI", main: "false"},
    {value: "JARDIM MONTE VERDE", label: "JARDIM MONTE VERDE", main: "false"},
    {value: "JARDIM NOVA SÃO JOÃO", label: "JARDIM NOVA SÃO JOÃO", main: "false"},
    {value: "JARDIM NOVO HORIZONTE", label: "JARDIM NOVO HORIZONTE", main: "false"},
    {value: "JARDIM ORIENTAL", label: "JARDIM ORIENTAL", main: "false"},
    {value: "JARDIM PRIMAVERA", label: "JARDIM PRIMAVERA", main: "false"},
    {value: "JARDIM PRISCILA", label: "JARDIM PRISCILA", main: "false"},
    {value: "JARDIM PROGRESSO", label: "JARDIM PROGRESSO", main: "false"},
    {value: "JARDIM RECANTO", label: "JARDIM RECANTO", main: "false"},
    {value: "JARDIM RECANTO DAS ÁGUAS", label: "JARDIM RECANTO DAS ÁGUAS", main: "false"},
    {value: "JARDIM RECANTO DOS PÁSSAROS", label: "JARDIM RECANTO DOS PÁSSAROS", main: "false"},
    {value: "JARDIM RECREIO", label: "JARDIM RECREIO", main: "false"},
    {value: "JARDIM SANTA ADÉLIA", label: "JARDIM SANTA ADÉLIA", main: "false"},
    {value: "JARDIM SANTA CLARA", label: "JARDIM SANTA CLARA", main: "false"},
    {value: "JARDIM SANTA HELENA", label: "JARDIM SANTA HELENA", main: "false"},
    {value: "JARDIM SANTA RITA", label: "JARDIM SANTA RITA", main: "false"},
    {value: "JARDIM SANTA ÁGUIDA", label: "JARDIM SANTA ÁGUIDA", main: "false"},
    {value: "JARDIM SANTARÉM", label: "JARDIM SANTARÉM", main: "false"},
    {value: "JARDIM SANTIAGO PENHA", label: "JARDIM SANTIAGO PENHA", main: "false"},
    {value: "JARDIM SANTO ANDRÉ", label: "JARDIM SANTO ANDRÉ", main: "false"},
    {value: "JARDIM SOL NASCENTE", label: "JARDIM SOL NASCENTE", main: "false"},
    {value: "JARDIM SÃO JORGE", label: "JARDIM SÃO JORGE", main: "false"},
    {value: "JARDIM SÃO MANOEL", label: "JARDIM SÃO MANOEL", main: "false"},
    {value: "JARDIM SÃO NICOLAU", label: "JARDIM SÃO NICOLAU", main: "false"},
    {value: "JARDIM SÃO PAULO", label: "JARDIM SÃO PAULO", main: "false"},
    {value: "JARDIM SÃO SALVADOR", label: "JARDIM SÃO SALVADOR", main: "false"},
    {value: "JARDIM SÃO THIAGO", label: "JARDIM SÃO THIAGO", main: "false"},
    {value: "JARDIM TRIANON", label: "JARDIM TRIANON", main: "false"},
    {value: "JARDIM VALE DO SOL", label: "JARDIM VALE DO SOL", main: "false"},
    {value: "JARDIM VILA RICA", label: "JARDIM VILA RICA", main: "false"},
    {value: "JARDIM YARA", label: "JARDIM YARA", main: "false"},
    {value: "JARDIM YOLANDA", label: "JARDIM YOLANDA", main: "false"},
    {value: "LAGOA DOS PATOS", label: "LAGOA DOS PATOS", main: "false"},
    {value: "LOTEAMENTO JARDIM POR DO SOL", label: "LOTEAMENTO JARDIM POR DO SOL", main: "false"},
    {value: "LOTEAMENTO PORTAL DA ALIANÇA", label: "LOTEAMENTO PORTAL DA ALIANÇA", main: "false"},
    {value: "LOTEAMENTO RESIDENCIAL PORTAL DA SERRA", label: "LOTEAMENTO RESIDENCIAL PORTAL DA SERRA", main: "false"},
    {value: "LOTEAMENTO RESIDENCIAL VALLE DO PRATA", label: "LOTEAMENTO RESIDENCIAL VALLE DO PRATA", main: "false"},
    {value: "MACUCO", label: "MACUCO", main: "false"},
    {value: "MAESTRO MOURÃO", label: "MAESTRO MOURÃO", main: "false"},
    {value: "NOVA REPÚBLICA", label: "NOVA REPÚBLICA", main: "false"},
    {value: "NÚCLEO HABITACIONAL EUGÊNIO S MATIAS", label: "NÚCLEO HABITACIONAL EUGÊNIO S MATIAS", main: "false"},
    {value: "NÚCLEO RESIDENCIAL DURVAL NICOLAU", label: "NÚCLEO RESIDENCIAL DURVAL NICOLAU", main: "false"},
    {value: "PARQUE ALVORADA", label: "PARQUE ALVORADA", main: "false"},
    {value: "PARQUE DAS NAÇÕES", label: "PARQUE DAS NAÇÕES", main: "false"},
    {value: "PARQUE DOS JEQUITIBÁS", label: "PARQUE DOS JEQUITIBÁS", main: "false"},
    {value: "PARQUE DOS RESEDÁS", label: "PARQUE DOS RESEDÁS", main: "false"},
    {value: "PARQUE RESIDENCIAL JARDIM SÃO DOMINGOS", label: "PARQUE RESIDENCIAL JARDIM SÃO DOMINGOS", main: "false"},
    {value: "PARQUE RESIDENCIAL TEREZA CRISTINA", label: "PARQUE RESIDENCIAL TEREZA CRISTINA", main: "false"},
    {value: "PARQUE UNIVERSITÁRIO", label: "PARQUE UNIVERSITÁRIO", main: "false"},
    {value: "PEDREGULHO", label: "PEDREGULHO", main: "false"},
    {value: "PERPÉTUO SOCORRO", label: "PERPÉTUO SOCORRO", main: "false"},
    {value: "POUSADA DO SOL", label: "POUSADA DO SOL", main: "false"},
    {value: "PRATINHA", label: "PRATINHA", main: "false"},
    {value: "RECANTO DA SERRA", label: "RECANTO DA SERRA", main: "false"},
    {value: "RECANTO DO BOSQUE", label: "RECANTO DO BOSQUE", main: "false"},
    {value: "RECANTO DO JAGUARI", label: "RECANTO DO JAGUARI", main: "false"},
    {value: "RECANTO DO LAGO", label: "RECANTO DO LAGO", main: "false"},
    {value: "RESIDENCIAL DAS PAINEIRAS", label: "RESIDENCIAL DAS PAINEIRAS", main: "false"},
    {value: "RESIDENCIAL FAZENDA DAS AREIAS", label: "RESIDENCIAL FAZENDA DAS AREIAS", main: "false"},
    {value: "RESIDENCIAL SÃO LOURENÇO", label: "RESIDENCIAL SÃO LOURENÇO", main: "false"},
    {value: "RIVIERA DE SÃO JOÃO", label: "RIVIERA DE SÃO JOÃO", main: "false"},
    {value: "SANTO ANTÔNIO", label: "SANTO ANTÔNIO", main: "false"},
    {value: "SERRA DA PAULISTA", label: "SERRA DA PAULISTA", main: "false"},
    {value: "SERRA DO PRATA", label: "SERRA DO PRATA", main: "false"},
    {value: "SOLÁRIO DA MANTIQUEIRA", label: "SOLÁRIO DA MANTIQUEIRA", main: "false"},
    {value: "SÃO BENEDITO", label: "SÃO BENEDITO", main: "false"},
    {value: "SÃO LAZÁRO", label: "SÃO LAZÁRO", main: "false"},
    {value: "SÃO MARCOS", label: "SÃO MARCOS", main: "false"},
    {value: "TERRAS DE SÃO JOSÉ", label: "TERRAS DE SÃO JOSÉ", main: "false"},
    {value: "VILA 1° DE MAIO", label: "VILA 1° DE MAIO", main: "false"},
    {value: "VILA BRASIL", label: "VILA BRASIL", main: "false"},
    {value: "VILA BÁNCARIA", label: "VILA BÁNCARIA", main: "false"},
    {value: "VILA CARVALHO", label: "VILA CARVALHO", main: "false"},
    {value: "VILA CLARO", label: "VILA CLARO", main: "false"},
    {value: "VILA CLAYTON", label: "VILA CLAYTON", main: "false"},
    {value: "VILA CONCEIÇÃO", label: "VILA CONCEIÇÃO", main: "false"},
    {value: "VILA CONRADO", label: "VILA CONRADO", main: "false"},
    {value: "VILA DAMÁGLIO", label: "VILA DAMÁGLIO", main: "false"},
    {value: "VILA DOS BANCÁRIOS", label: "VILA DOS BANCÁRIOS", main: "false"},
    {value: "VILA ESPERANÇA", label: "VILA ESPERANÇA", main: "false"},
    {value: "VILA ESTRELA", label: "VILA ESTRELA", main: "false"},
    {value: "VILA GOMES", label: "VILA GOMES", main: "false"},
    {value: "VILA ISABEL", label: "VILA ISABEL", main: "false"},
    {value: "VILA LOYOLA", label: "VILA LOYOLA", main: "false"},
    {value: "VILA LUZITANA", label: "VILA LUZITANA", main: "false"},
    {value: "VILA MAGNÓLIA", label: "VILA MAGNÓLIA", main: "false"},
    {value: "VILA NOSSA SENHORA FÁTIMA", label: "VILA NOSSA SENHORA FÁTIMA", main: "false"},
    {value: "VILA OPERÁRIA", label: "VILA OPERÁRIA", main: "false"},
    {value: "VILA ORIENTAL", label: "VILA ORIENTAL", main: "false"},
    {value: "VILA SANTA EDWIRGES", label: "VILA SANTA EDWIRGES", main: "false"},
    {value: "VILA SÃO JOSÉ", label: "VILA SÃO JOSÉ", main: "false"},
    {value: "VILA TENENTE VASCONCELOS", label: "VILA TENENTE VASCONCELOS", main: "false"},
    {value: "VILA TRAFANI", label: "VILA TRAFANI", main: "false"},
    {value: "VILA VALENTIM", label: "VILA VALENTIM", main: "false"},
    {value: "VILA WESTIN", label: "VILA WESTIN", main: "false"},
    {value: "VILA ZANETTI", label: "VILA ZANETTI", main: "false"},
]


export const aguai_neighborhoods_text = [
    {value: "BENEDITO MAMEDE JÚNIOR", text: "BENEDITO MAMEDE JÚNIOR", main: "false"},
    {value: "CECAP", text: "CECAP", main: "false"},
    {value: "CENTRO", text: "CENTRO", main: "false"},
    {value: "CIDADE NOVA", text: "CIDADE NOVA", main: "false"},
    {value: "DIVA ASSAD", text: "DIVA ASSAD", main: "false"},
    {value: "DOS ANJOS", text: "DOS ANJOS", main: "false"},
    {value: "JARDIM AEROPORTO", text: "JARDIM AEROPORTO", main: "false"},
    {value: "JARDIM BELA VISTA", text: "JARDIM BELA VISTA", main: "false"},
    {value: "JARDIM CARLOTA REHDER", text: "JARDIM CARLOTA REHDER", main: "false"},
    {value: "JARDIM CENTER CITY", text: "JARDIM CENTER CITY", main: "false"},
    {value: "JARDIM DAS FLORES", text: "JARDIM DAS FLORES", main: "false"},
    {value: "JARDIM DO EDEN", text: "JARDIM DO EDEN", main: "false"},
    {value: "JARDIM DOS ALPES", text: "JARDIM DOS ALPES", main: "false"},
    {value: "JARDIM MONTE LÍBANO", text: "JARDIM MONTE LÍBANO", main: "false"},
    {value: "JARDIM MONTEVIDEO", text: "JARDIM MONTEVIDEO", main: "false"},
    {value: "JARDIM NOVAGUAÍ", text: "JARDIM NOVAGUAÍ", main: "false"},
    {value: "JARDIM PLANALTO", text: "JARDIM PLANALTO", main: "false"},
    {value: "JARDIM PRIMAVERA", text: "JARDIM PRIMAVERA", main: "false"},
    {value: "JARDIM SANTA MARIA", text: "JARDIM SANTA MARIA", main: "false"},
    {value: "JARDIM SANTA PAULA", text: "JARDIM SANTA PAULA", main: "false"},
    {value: "JARDIM SANTA ÚRSULA", text: "JARDIM SANTA ÚRSULA", main: "false"},
    {value: "JARDIM VISTA DA COLINA", text: "JARDIM VISTA DA COLINA", main: "false"},
    {value: "LAGOA SECA", text: "LAGOA SECA", main: "false"},
    {value: "PARQUE DAS PALMEIRAS", text: "PARQUE DAS PALMEIRAS", main: "false"},
    {value: "PARQUE MIGUELITO", text: "PARQUE MIGUELITO", main: "false"},
    {value: "PORTAL DOS LAGOS", text: "PORTAL DOS LAGOS", main: "false"},
    {value: "SIRIRI", text: "SIRIRI", main: "false"},
    {value: "TEOTÔNIO VILELA", text: "TEOTÔNIO VILELA", main: "false"},
    {value: "VILA BOM GOSTO", text: "VILA BOM GOSTO", main: "false"},
    {value: "VILA BRAGA", text: "VILA BRAGA", main: "false"},
    {value: "VILA NOVA", text: "VILA NOVA", main: "false"},
    {value: "VILA NOVA AMÉRICA", text: "VILA NOVA AMÉRICA", main: "false"},
    {value: "VILA PARAISO", text: "VILA PARAISO", main: "false"},
    {value: "VILA REGINA", text: "VILA REGINA", main: "false"},
    {value: "VILA REHDER", text: "VILA REHDER", main: "false"},
    {value: "VILA SÃO JOSÉ", text: "VILA SÃO JOSÉ", main: "false"},
]


export const sjbv_neighborhoods_text = [
    {value: "ALTO DA BOA VISTA", text: "ALTO DA BOA VISTA", main: "false"},
    {value: "ALTO DA PAULISTA", text: "ALTO DA PAULISTA", main: "false"},
    {value: "BAIRRO ALEGRE", text: "BAIRRO ALEGRE", main: "false"},
    {value: "BAIRRO DO ROSÁRIO", text: "BAIRRO DO ROSÁRIO", main: "false"},
    {value: "CENTRO", text: "CENTRO", main: "false"},
    {value: "COLINAS DA MANTIQUEIRA", text: "COLINAS DA MANTIQUEIRA", main: "false"},
    {value: "COLINAS DO ALEGRE", text: "COLINAS DO ALEGRE", main: "false"},
    {value: "CONDOMÍNIO MORRO AZUL", text: "CONDOMÍNIO MORRO AZUL", main: "false"},
    {value: "CONDOMÍNIO MORRO AZUL II", text: "CONDOMÍNIO MORRO AZUL II", main: "false"},
    {value: "CONDOMÍNIO SERRA DO PRATA", text: "CONDOMÍNIO SERRA DO PRATA", main: "false"},
    {value: "CONDOMÍNIO VISTA DA SERRA", text: "CONDOMÍNIO VISTA DA SERRA", main: "false"},
    {value: "D.E.R", text: "D.E.R", main: "false"},
    {value: "DISTRITO INDUSTRIAL", text: "DISTRITO INDUSTRIAL", main: "false"},
    {value: "JARDIM AEROPORTO", text: "JARDIM AEROPORTO", main: "false"},
    {value: "JARDIM AEROPORTO ELDORADO", text: "JARDIM AEROPORTO ELDORADO", main: "false"},
    {value: "JARDIM ALMEIDA", text: "JARDIM ALMEIDA", main: "false"},
    {value: "JARDIM AMERICA DO SUL", text: "JARDIM AMERICA DO SUL", main: "false"},
    {value: "JARDIM AMÉLIA", text: "JARDIM AMÉLIA", main: "false"},
    {value: "JARDIM AURORA", text: "JARDIM AURORA", main: "false"},
    {value: "JARDIM BELA VISTA", text: "JARDIM BELA VISTA", main: "false"},
    {value: "JARDIM BELVEDERE", text: "JARDIM BELVEDERE", main: "false"},
    {value: "JARDIM BOA VISTA", text: "JARDIM BOA VISTA", main: "false"},
    {value: "JARDIM CANADÁ", text: "JARDIM CANADÁ", main: "false"},
    {value: "JARDIM CLEDIRNA", text: "JARDIM CLEDIRNA", main: "false"},
    {value: "JARDIM CREPÚSCULO", text: "JARDIM CREPÚSCULO", main: "false"},
    {value: "JARDIM DA GLÓRIA", text: "JARDIM DA GLÓRIA", main: "false"},
    {value: "JARDIM DAS ACÁCIAS", text: "JARDIM DAS ACÁCIAS", main: "false"},
    {value: "JARDIM DAS AMOREIRAS", text: "JARDIM DAS AMOREIRAS", main: "false"},
    {value: "JARDIM DAS AZALÉIAS", text: "JARDIM DAS AZALÉIAS", main: "false"},
    {value: "JARDIM DAS BROMÉLIAS", text: "JARDIM DAS BROMÉLIAS", main: "false"},
    {value: "JARDIM DAS FLORES", text: "JARDIM DAS FLORES", main: "false"},
    {value: "JARDIM DAS HORTÊNCIAS", text: "JARDIM DAS HORTÊNCIAS", main: "false"},
    {value: "JARDIM DAS MACAUBEIRAS", text: "JARDIM DAS MACAUBEIRAS", main: "false"},
    {value: "JARDIM DAS MANGUEIRAS", text: "JARDIM DAS MANGUEIRAS", main: "false"},
    {value: "JARDIM DAS PAINEIRAS", text: "JARDIM DAS PAINEIRAS", main: "false"},
    {value: "JARDIM DAS ROSAS", text: "JARDIM DAS ROSAS", main: "false"},
    {value: "JARDIM DAS TULIPAS", text: "JARDIM DAS TULIPAS", main: "false"},
    {value: "JARDIM DEL PLATA", text: "JARDIM DEL PLATA", main: "false"},
    {value: "JARDIM DO TREVO", text: "JARDIM DO TREVO", main: "false"},
    {value: "JARDIM DONA TEREZA", text: "JARDIM DONA TEREZA", main: "false"},
    {value: "JARDIM DOS COMERCIÁRIOS", text: "JARDIM DOS COMERCIÁRIOS", main: "false"},
    {value: "JARDIM DOS EUCALIPTOS", text: "JARDIM DOS EUCALIPTOS", main: "false"},
    {value: "JARDIM DOS IPÊS", text: "JARDIM DOS IPÊS", main: "false"},
    {value: "JARDIM DOS JACARANDÁS", text: "JARDIM DOS JACARANDÁS", main: "false"},
    {value: "JARDIM DOS REIS", text: "JARDIM DOS REIS", main: "false"},
    {value: "JARDIM ELDORADO", text: "JARDIM ELDORADO", main: "false"},
    {value: "JARDIM EUROPA", text: "JARDIM EUROPA", main: "false"},
    {value: "JARDIM FLAMBOYANT", text: "JARDIM FLAMBOYANT", main: "false"},
    {value: "JARDIM FLEMING", text: "JARDIM FLEMING", main: "false"},
    {value: "JARDIM GUANABARA", text: "JARDIM GUANABARA", main: "false"},
    {value: "JARDIM INDUSTRIAL", text: "JARDIM INDUSTRIAL", main: "false"},
    {value: "JARDIM ITÁLIA", text: "JARDIM ITÁLIA", main: "false"},
    {value: "JARDIM LEONOR", text: "JARDIM LEONOR", main: "false"},
    {value: "JARDIM LUCAS TEIXEIRA", text: "JARDIM LUCAS TEIXEIRA", main: "false"},
    {value: "JARDIM MAGALHÃES", text: "JARDIM MAGALHÃES", main: "false"},
    {value: "JARDIM MICHELAZZO", text: "JARDIM MICHELAZZO", main: "false"},
    {value: "JARDIM MOLINARI", text: "JARDIM MOLINARI", main: "false"},
    {value: "JARDIM MONTE VERDE", text: "JARDIM MONTE VERDE", main: "false"},
    {value: "JARDIM NOVA SÃO JOÃO", text: "JARDIM NOVA SÃO JOÃO", main: "false"},
    {value: "JARDIM NOVO HORIZONTE", text: "JARDIM NOVO HORIZONTE", main: "false"},
    {value: "JARDIM ORIENTAL", text: "JARDIM ORIENTAL", main: "false"},
    {value: "JARDIM PRIMAVERA", text: "JARDIM PRIMAVERA", main: "false"},
    {value: "JARDIM PRISCILA", text: "JARDIM PRISCILA", main: "false"},
    {value: "JARDIM PROGRESSO", text: "JARDIM PROGRESSO", main: "false"},
    {value: "JARDIM RECANTO", text: "JARDIM RECANTO", main: "false"},
    {value: "JARDIM RECANTO DAS ÁGUAS", text: "JARDIM RECANTO DAS ÁGUAS", main: "false"},
    {value: "JARDIM RECANTO DOS PÁSSAROS", text: "JARDIM RECANTO DOS PÁSSAROS", main: "false"},
    {value: "JARDIM RECREIO", text: "JARDIM RECREIO", main: "false"},
    {value: "JARDIM SANTA ADÉLIA", text: "JARDIM SANTA ADÉLIA", main: "false"},
    {value: "JARDIM SANTA CLARA", text: "JARDIM SANTA CLARA", main: "false"},
    {value: "JARDIM SANTA HELENA", text: "JARDIM SANTA HELENA", main: "false"},
    {value: "JARDIM SANTA RITA", text: "JARDIM SANTA RITA", main: "false"},
    {value: "JARDIM SANTA ÁGUIDA", text: "JARDIM SANTA ÁGUIDA", main: "false"},
    {value: "JARDIM SANTARÉM", text: "JARDIM SANTARÉM", main: "false"},
    {value: "JARDIM SANTIAGO PENHA", text: "JARDIM SANTIAGO PENHA", main: "false"},
    {value: "JARDIM SANTO ANDRÉ", text: "JARDIM SANTO ANDRÉ", main: "false"},
    {value: "JARDIM SOL NASCENTE", text: "JARDIM SOL NASCENTE", main: "false"},
    {value: "JARDIM SÃO JORGE", text: "JARDIM SÃO JORGE", main: "false"},
    {value: "JARDIM SÃO MANOEL", text: "JARDIM SÃO MANOEL", main: "false"},
    {value: "JARDIM SÃO NICOLAU", text: "JARDIM SÃO NICOLAU", main: "false"},
    {value: "JARDIM SÃO PAULO", text: "JARDIM SÃO PAULO", main: "false"},
    {value: "JARDIM SÃO SALVADOR", text: "JARDIM SÃO SALVADOR", main: "false"},
    {value: "JARDIM SÃO THIAGO", text: "JARDIM SÃO THIAGO", main: "false"},
    {value: "JARDIM TRIANON", text: "JARDIM TRIANON", main: "false"},
    {value: "JARDIM VALE DO SOL", text: "JARDIM VALE DO SOL", main: "false"},
    {value: "JARDIM VILA RICA", text: "JARDIM VILA RICA", main: "false"},
    {value: "JARDIM YARA", text: "JARDIM YARA", main: "false"},
    {value: "JARDIM YOLANDA", text: "JARDIM YOLANDA", main: "false"},
    {value: "LAGOA DOS PATOS", text: "LAGOA DOS PATOS", main: "false"},
    {value: "LOTEAMENTO JARDIM POR DO SOL", text: "LOTEAMENTO JARDIM POR DO SOL", main: "false"},
    {value: "LOTEAMENTO PORTAL DA ALIANÇA", text: "LOTEAMENTO PORTAL DA ALIANÇA", main: "false"},
    {value: "LOTEAMENTO RESIDENCIAL PORTAL DA SERRA", text: "LOTEAMENTO RESIDENCIAL PORTAL DA SERRA", main: "false"},
    {value: "LOTEAMENTO RESIDENCIAL VALLE DO PRATA", text: "LOTEAMENTO RESIDENCIAL VALLE DO PRATA", main: "false"},
    {value: "MACUCO", text: "MACUCO", main: "false"},
    {value: "MAESTRO MOURÃO", text: "MAESTRO MOURÃO", main: "false"},
    {value: "NOVA REPÚBLICA", text: "NOVA REPÚBLICA", main: "false"},
    {value: "NÚCLEO HABITACIONAL EUGÊNIO S MATIAS", text: "NÚCLEO HABITACIONAL EUGÊNIO S MATIAS", main: "false"},
    {value: "NÚCLEO RESIDENCIAL DURVAL NICOLAU", text: "NÚCLEO RESIDENCIAL DURVAL NICOLAU", main: "false"},
    {value: "PARQUE ALVORADA", text: "PARQUE ALVORADA", main: "false"},
    {value: "PARQUE DAS NAÇÕES", text: "PARQUE DAS NAÇÕES", main: "false"},
    {value: "PARQUE DOS JEQUITIBÁS", text: "PARQUE DOS JEQUITIBÁS", main: "false"},
    {value: "PARQUE DOS RESEDÁS", text: "PARQUE DOS RESEDÁS", main: "false"},
    {value: "PARQUE RESIDENCIAL JARDIM SÃO DOMINGOS", text: "PARQUE RESIDENCIAL JARDIM SÃO DOMINGOS", main: "false"},
    {value: "PARQUE RESIDENCIAL TEREZA CRISTINA", text: "PARQUE RESIDENCIAL TEREZA CRISTINA", main: "false"},
    {value: "PARQUE UNIVERSITÁRIO", text: "PARQUE UNIVERSITÁRIO", main: "false"},
    {value: "PEDREGULHO", text: "PEDREGULHO", main: "false"},
    {value: "PERPÉTUO SOCORRO", text: "PERPÉTUO SOCORRO", main: "false"},
    {value: "POUSADA DO SOL", text: "POUSADA DO SOL", main: "false"},
    {value: "PRATINHA", text: "PRATINHA", main: "false"},
    {value: "RECANTO DA SERRA", text: "RECANTO DA SERRA", main: "false"},
    {value: "RECANTO DO BOSQUE", text: "RECANTO DO BOSQUE", main: "false"},
    {value: "RECANTO DO JAGUARI", text: "RECANTO DO JAGUARI", main: "false"},
    {value: "RECANTO DO LAGO", text: "RECANTO DO LAGO", main: "false"},
    {value: "RESIDENCIAL DAS PAINEIRAS", text: "RESIDENCIAL DAS PAINEIRAS", main: "false"},
    {value: "RESIDENCIAL FAZENDA DAS AREIAS", text: "RESIDENCIAL FAZENDA DAS AREIAS", main: "false"},
    {value: "RESIDENCIAL SÃO LOURENÇO", text: "RESIDENCIAL SÃO LOURENÇO", main: "false"},
    {value: "RIVIERA DE SÃO JOÃO", text: "RIVIERA DE SÃO JOÃO", main: "false"},
    {value: "SANTO ANTÔNIO", text: "SANTO ANTÔNIO", main: "false"},
    {value: "SERRA DA PAULISTA", text: "SERRA DA PAULISTA", main: "false"},
    {value: "SERRA DO PRATA", text: "SERRA DO PRATA", main: "false"},
    {value: "SOLÁRIO DA MANTIQUEIRA", text: "SOLÁRIO DA MANTIQUEIRA", main: "false"},
    {value: "SÃO BENEDITO", text: "SÃO BENEDITO", main: "false"},
    {value: "SÃO LAZÁRO", text: "SÃO LAZÁRO", main: "false"},
    {value: "SÃO MARCOS", text: "SÃO MARCOS", main: "false"},
    {value: "TERRAS DE SÃO JOSÉ", text: "TERRAS DE SÃO JOSÉ", main: "false"},
    {value: "VILA 1° DE MAIO", text: "VILA 1° DE MAIO", main: "false"},
    {value: "VILA BRASIL", text: "VILA BRASIL", main: "false"},
    {value: "VILA BÁNCARIA", text: "VILA BÁNCARIA", main: "false"},
    {value: "VILA CARVALHO", text: "VILA CARVALHO", main: "false"},
    {value: "VILA CLARO", text: "VILA CLARO", main: "false"},
    {value: "VILA CLAYTON", text: "VILA CLAYTON", main: "false"},
    {value: "VILA CONCEIÇÃO", text: "VILA CONCEIÇÃO", main: "false"},
    {value: "VILA CONRADO", text: "VILA CONRADO", main: "false"},
    {value: "VILA DAMÁGLIO", text: "VILA DAMÁGLIO", main: "false"},
    {value: "VILA DOS BANCÁRIOS", text: "VILA DOS BANCÁRIOS", main: "false"},
    {value: "VILA ESPERANÇA", text: "VILA ESPERANÇA", main: "false"},
    {value: "VILA ESTRELA", text: "VILA ESTRELA", main: "false"},
    {value: "VILA GOMES", text: "VILA GOMES", main: "false"},
    {value: "VILA ISABEL", text: "VILA ISABEL", main: "false"},
    {value: "VILA LOYOLA", text: "VILA LOYOLA", main: "false"},
    {value: "VILA LUZITANA", text: "VILA LUZITANA", main: "false"},
    {value: "VILA MAGNÓLIA", text: "VILA MAGNÓLIA", main: "false"},
    {value: "VILA NOSSA SENHORA FÁTIMA", text: "VILA NOSSA SENHORA FÁTIMA", main: "false"},
    {value: "VILA OPERÁRIA", text: "VILA OPERÁRIA", main: "false"},
    {value: "VILA ORIENTAL", text: "VILA ORIENTAL", main: "false"},
    {value: "VILA SANTA EDWIRGES", text: "VILA SANTA EDWIRGES", main: "false"},
    {value: "VILA SÃO JOSÉ", text: "VILA SÃO JOSÉ", main: "false"},
    {value: "VILA TENENTE VASCONCELOS", text: "VILA TENENTE VASCONCELOS", main: "false"},
    {value: "VILA TRAFANI", text: "VILA TRAFANI", main: "false"},
    {value: "VILA VALENTIM", text: "VILA VALENTIM", main: "false"},
    {value: "VILA WESTIN", text: "VILA WESTIN", main: "false"},
    {value: "VILA ZANETTI", text: "VILA ZANETTI", main: "false"},
]