export const brazilian_districts = [
    {value: "AC", text: "AC - Acre"},
    {value: "AL", text: "AL - Alagoas"},
    {value: "AP", text: "AP - Macapá"},
    {value: "AM", text: "AM - Amapá"},
    {value: "BA", text: "BA - Bahia"},
    {value: "CE", text: "CE - Ceará"},
    {value: "DF", text: "DF - Distrito Federal"},
    {value: "ES", text: "ES - Espírito Santo"},
    {value: "GO", text: "GO - Goiás"},
    {value: "MA", text: "MA - Maranhão"},
    {value: "MT", text: "MT - Mato Grosso"},
    {value: "MS", text: "MS - Mato Grosso do Sul"},
    {value: "MG", text: "MG - Minas Gerais"},
    {value: "PA", text: "PA - Pará"},
    {value: "PB", text: "PB - Paraíba"},
    {value: "PR", text: "PR - Paraná"},
    {value: "PE", text: "PE - Pernambuco"},
    {value: "PI", text: "PI - Piauí"},
    {value: "RJ", text: "RJ - Rio de Janeiro"},
    {value: "RN", text: "RN - Rio Grande do Norte"},
    {value: "RS", text: "RS - Rio Grande do Sul"},
    {value: "RO", text: "RO - Rondônia"},
    {value: "RR", text: "RR - Roraima"},
    {value: "SC", text: "SC - Santa Catarina"},
    {value: "SP", text: "SP - São Paulo"},
    {value: "SE", text: "SE - Sergipe"},
    {value: "TO", text: "TO - Tocantins"}, 
    {value: "União", text: "União"}, 
];