export const brazilian_neighborhoods = [
    { value: "BENEDITO MAMEDE JÚNIOR", label: "BENEDITO MAMEDE JÚNIOR", filter: { city: "AGUAÍ" } },
    { value: "CECAP", label: "CECAP", filter: { city: "AGUAÍ" } },
    { value: "CENTRO", label: "CENTRO", filter: { city: "AGUAÍ" } },
    { value: "CIDADE NOVA", label: "CIDADE NOVA", filter: { city: "AGUAÍ" } },
    { value: "DIVA ASSAD", label: "DIVA ASSAD", filter: { city: "AGUAÍ" } },
    { value: "DOS ANJOS", label: "DOS ANJOS", filter: { city: "AGUAÍ" } },
    { value: "JARDIM AEROPORTO", label: "JARDIM AEROPORTO", filter: { city: "AGUAÍ" } },
    { value: "JARDIM BELA VISTA", label: "JARDIM BELA VISTA", filter: { city: "AGUAÍ" } },
    { value: "JARDIM CARLOTA REHDER", label: "JARDIM CARLOTA REHDER", filter: { city: "AGUAÍ" } },
    { value: "JARDIM CENTER CITY", label: "JARDIM CENTER CITY", filter: { city: "AGUAÍ" } },
    { value: "JARDIM DAS FLORES", label: "JARDIM DAS FLORES", filter: { city: "AGUAÍ" } },
    { value: "JARDIM DO EDEN", label: "JARDIM DO EDEN", filter: { city: "AGUAÍ" } },
    { value: "JARDIM DOS ALPES", label: "JARDIM DOS ALPES", filter: { city: "AGUAÍ" } },
    { value: "JARDIM MONTE LÍBANO", label: "JARDIM MONTE LÍBANO", filter: { city: "AGUAÍ" } },
    { value: "JARDIM MONTEVIDEO", label: "JARDIM MONTEVIDEO", filter: { city: "AGUAÍ" } },
    { value: "JARDIM NOVAGUAÍ", label: "JARDIM NOVAGUAÍ", filter: { city: "AGUAÍ" } },
    { value: "JARDIM PLANALTO", label: "JARDIM PLANALTO", filter: { city: "AGUAÍ" } },
    { value: "JARDIM PRIMAVERA", label: "JARDIM PRIMAVERA", filter: { city: "AGUAÍ" } },
    { value: "JARDIM SANTA MARIA", label: "JARDIM SANTA MARIA", filter: { city: "AGUAÍ" } },
    { value: "JARDIM SANTA PAULA", label: "JARDIM SANTA PAULA", filter: { city: "AGUAÍ" } },
    { value: "JARDIM SANTA ÚRSULA", label: "JARDIM SANTA ÚRSULA", filter: { city: "AGUAÍ" } },
    { value: "JARDIM VISTA DA COLINA", label: "JARDIM VISTA DA COLINA", filter: { city: "AGUAÍ" } },
    { value: "LAGOA SECA", label: "LAGOA SECA", filter: { city: "AGUAÍ" } },
    { value: "PARQUE DAS PALMEIRAS", label: "PARQUE DAS PALMEIRAS", filter: { city: "AGUAÍ" } },
    { value: "PARQUE MIGUELITO", label: "PARQUE MIGUELITO", filter: { city: "AGUAÍ" } },
    { value: "PORTAL DOS LAGOS", label: "PORTAL DOS LAGOS", filter: { city: "AGUAÍ" } },
    { value: "SIRIRI", label: "SIRIRI", filter: { city: "AGUAÍ" } },
    { value: "TEOTÔNIO VILELA", label: "TEOTÔNIO VILELA", filter: { city: "AGUAÍ" } },
    { value: "VILA BOM GOSTO", label: "VILA BOM GOSTO", filter: { city: "AGUAÍ" } },
    { value: "VILA BRAGA", label: "VILA BRAGA", filter: { city: "AGUAÍ" } },
    { value: "VILA NOVA", label: "VILA NOVA", filter: { city: "AGUAÍ" } },
    { value: "VILA NOVA AMÉRICA", label: "VILA NOVA AMÉRICA", filter: { city: "AGUAÍ" } },
    { value: "VILA PARAISO", label: "VILA PARAISO", filter: { city: "AGUAÍ" } },
    { value: "VILA REGINA", label: "VILA REGINA", filter: { city: "AGUAÍ" } },
    { value: "VILA REHDER", label: "VILA REHDER", filter: { city: "AGUAÍ" } },
    { value: "VILA SÃO JOSÉ", label: "VILA SÃO JOSÉ", filter: { city: "AGUAÍ" } },
]

export const sjbv_neighborhoods = [
    { value: "ALTO DA BOA VISTA", label: "ALTO DA BOA VISTA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "ALTO DA PAULISTA", label: "ALTO DA PAULISTA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "BAIRRO ALEGRE", label: "BAIRRO ALEGRE", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "BAIRRO DO ROSÁRIO", label: "BAIRRO DO ROSÁRIO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "CENTRO", label: "CENTRO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "COLINAS DA MANTIQUEIRA", label: "COLINAS DA MANTIQUEIRA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "COLINAS DO ALEGRE", label: "COLINAS DO ALEGRE", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "CONDOMÍNIO MORRO AZUL", label: "CONDOMÍNIO MORRO AZUL", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "CONDOMÍNIO MORRO AZUL II", label: "CONDOMÍNIO MORRO AZUL II", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "CONDOMÍNIO SERRA DO PRATA", label: "CONDOMÍNIO SERRA DO PRATA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "CONDOMÍNIO VISTA DA SERRA", label: "CONDOMÍNIO VISTA DA SERRA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "D.E.R", label: "D.E.R", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "DISTRITO INDUSTRIAL", label: "DISTRITO INDUSTRIAL", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM AEROPORTO", label: "JARDIM AEROPORTO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM AEROPORTO ELDORADO", label: "JARDIM AEROPORTO ELDORADO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM ALMEIDA", label: "JARDIM ALMEIDA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM AMERICA DO SUL", label: "JARDIM AMERICA DO SUL", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM AMÉLIA", label: "JARDIM AMÉLIA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM AURORA", label: "JARDIM AURORA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM BELA VISTA", label: "JARDIM BELA VISTA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM BELVEDERE", label: "JARDIM BELVEDERE", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM BOA VISTA", label: "JARDIM BOA VISTA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM CANADÁ", label: "JARDIM CANADÁ", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM CLEDIRNA", label: "JARDIM CLEDIRNA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM CREPÚSCULO", label: "JARDIM CREPÚSCULO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DA GLÓRIA", label: "JARDIM DA GLÓRIA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DAS ACÁCIAS", label: "JARDIM DAS ACÁCIAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DAS AMOREIRAS", label: "JARDIM DAS AMOREIRAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DAS AZALÉIAS", label: "JARDIM DAS AZALÉIAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DAS BROMÉLIAS", label: "JARDIM DAS BROMÉLIAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DAS FLORES", label: "JARDIM DAS FLORES", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DAS HORTÊNCIAS", label: "JARDIM DAS HORTÊNCIAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DAS MACAUBEIRAS", label: "JARDIM DAS MACAUBEIRAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DAS MANGUEIRAS", label: "JARDIM DAS MANGUEIRAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DAS PAINEIRAS", label: "JARDIM DAS PAINEIRAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DAS ROSAS", label: "JARDIM DAS ROSAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DAS TULIPAS", label: "JARDIM DAS TULIPAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DEL PLATA", label: "JARDIM DEL PLATA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DO TREVO", label: "JARDIM DO TREVO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DONA TEREZA", label: "JARDIM DONA TEREZA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DOS COMERCIÁRIOS", label: "JARDIM DOS COMERCIÁRIOS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DOS EUCALIPTOS", label: "JARDIM DOS EUCALIPTOS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DOS IPÊS", label: "JARDIM DOS IPÊS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DOS JACARANDÁS", label: "JARDIM DOS JACARANDÁS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM DOS REIS", label: "JARDIM DOS REIS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM ELDORADO", label: "JARDIM ELDORADO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM EUROPA", label: "JARDIM EUROPA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM FLAMBOYANT", label: "JARDIM FLAMBOYANT", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM FLEMING", label: "JARDIM FLEMING", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM GUANABARA", label: "JARDIM GUANABARA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM INDUSTRIAL", label: "JARDIM INDUSTRIAL", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM ITÁLIA", label: "JARDIM ITÁLIA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM LEONOR", label: "JARDIM LEONOR", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM LUCAS TEIXEIRA", label: "JARDIM LUCAS TEIXEIRA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM MAGALHÃES", label: "JARDIM MAGALHÃES", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM MICHELAZZO", label: "JARDIM MICHELAZZO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM MOLINARI", label: "JARDIM MOLINARI", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM MONTE VERDE", label: "JARDIM MONTE VERDE", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM NOVA SÃO JOÃO", label: "JARDIM NOVA SÃO JOÃO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM NOVO HORIZONTE", label: "JARDIM NOVO HORIZONTE", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM ORIENTAL", label: "JARDIM ORIENTAL", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM PRIMAVERA", label: "JARDIM PRIMAVERA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM PRISCILA", label: "JARDIM PRISCILA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM PROGRESSO", label: "JARDIM PROGRESSO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM RECANTO", label: "JARDIM RECANTO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM RECANTO DAS ÁGUAS", label: "JARDIM RECANTO DAS ÁGUAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM RECANTO DOS PÁSSAROS", label: "JARDIM RECANTO DOS PÁSSAROS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM RECREIO", label: "JARDIM RECREIO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SANTA ADÉLIA", label: "JARDIM SANTA ADÉLIA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SANTA CLARA", label: "JARDIM SANTA CLARA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SANTA HELENA", label: "JARDIM SANTA HELENA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SANTA RITA", label: "JARDIM SANTA RITA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SANTA ÁGUIDA", label: "JARDIM SANTA ÁGUIDA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SANTARÉM", label: "JARDIM SANTARÉM", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SANTIAGO PENHA", label: "JARDIM SANTIAGO PENHA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SANTO ANDRÉ", label: "JARDIM SANTO ANDRÉ", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SOL NASCENTE", label: "JARDIM SOL NASCENTE", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SÃO JORGE", label: "JARDIM SÃO JORGE", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SÃO MANOEL", label: "JARDIM SÃO MANOEL", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SÃO NICOLAU", label: "JARDIM SÃO NICOLAU", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SÃO PAULO", label: "JARDIM SÃO PAULO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SÃO SALVADOR", label: "JARDIM SÃO SALVADOR", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM SÃO THIAGO", label: "JARDIM SÃO THIAGO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM TRIANON", label: "JARDIM TRIANON", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM VALE DO SOL", label: "JARDIM VALE DO SOL", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM VILA RICA", label: "JARDIM VILA RICA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM YARA", label: "JARDIM YARA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "JARDIM YOLANDA", label: "JARDIM YOLANDA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "LAGOA DOS PATOS", label: "LAGOA DOS PATOS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "LOTEAMENTO JARDIM POR DO SOL", label: "LOTEAMENTO JARDIM POR DO SOL", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "LOTEAMENTO PORTAL DA ALIANÇA", label: "LOTEAMENTO PORTAL DA ALIANÇA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "LOTEAMENTO RESIDENCIAL PORTAL DA SERRA", label: "LOTEAMENTO RESIDENCIAL PORTAL DA SERRA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "LOTEAMENTO RESIDENCIAL VALLE DO PRATA", label: "LOTEAMENTO RESIDENCIAL VALLE DO PRATA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "MACUCO", label: "MACUCO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "MAESTRO MOURÃO", label: "MAESTRO MOURÃO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "NOVA REPÚBLICA", label: "NOVA REPÚBLICA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "NÚCLEO HABITACIONAL EUGÊNIO S MATIAS", label: "NÚCLEO HABITACIONAL EUGÊNIO S MATIAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "NÚCLEO RESIDENCIAL DURVAL NICOLAU", label: "NÚCLEO RESIDENCIAL DURVAL NICOLAU", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "PARQUE ALVORADA", label: "PARQUE ALVORADA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "PARQUE DAS NAÇÕES", label: "PARQUE DAS NAÇÕES", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "PARQUE DOS JEQUITIBÁS", label: "PARQUE DOS JEQUITIBÁS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "PARQUE DOS RESEDÁS", label: "PARQUE DOS RESEDÁS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "PARQUE RESIDENCIAL JARDIM SÃO DOMINGOS", label: "PARQUE RESIDENCIAL JARDIM SÃO DOMINGOS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "PARQUE RESIDENCIAL TEREZA CRISTINA", label: "PARQUE RESIDENCIAL TEREZA CRISTINA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "PARQUE UNIVERSITÁRIO", label: "PARQUE UNIVERSITÁRIO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "PEDREGULHO", label: "PEDREGULHO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "PERPÉTUO SOCORRO", label: "PERPÉTUO SOCORRO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "POUSADA DO SOL", label: "POUSADA DO SOL", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "PRATINHA", label: "PRATINHA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "RECANTO DA SERRA", label: "RECANTO DA SERRA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "RECANTO DO BOSQUE", label: "RECANTO DO BOSQUE", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "RECANTO DO JAGUARI", label: "RECANTO DO JAGUARI", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "RECANTO DO LAGO", label: "RECANTO DO LAGO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "RESIDENCIAL DAS PAINEIRAS", label: "RESIDENCIAL DAS PAINEIRAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "RESIDENCIAL FAZENDA DAS AREIAS", label: "RESIDENCIAL FAZENDA DAS AREIAS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "RESIDENCIAL SÃO LOURENÇO", label: "RESIDENCIAL SÃO LOURENÇO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "RIVIERA DE SÃO JOÃO", label: "RIVIERA DE SÃO JOÃO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "SANTO ANTÔNIO", label: "SANTO ANTÔNIO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "SERRA DA PAULISTA", label: "SERRA DA PAULISTA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "SERRA DO PRATA", label: "SERRA DO PRATA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "SOLÁRIO DA MANTIQUEIRA", label: "SOLÁRIO DA MANTIQUEIRA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "SÃO BENEDITO", label: "SÃO BENEDITO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "SÃO LAZÁRO", label: "SÃO LAZÁRO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "SÃO MARCOS", label: "SÃO MARCOS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "TERRAS DE SÃO JOSÉ", label: "TERRAS DE SÃO JOSÉ", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA 1° DE MAIO", label: "VILA 1° DE MAIO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA BRASIL", label: "VILA BRASIL", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA BÁNCARIA", label: "VILA BÁNCARIA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA CARVALHO", label: "VILA CARVALHO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA CLARO", label: "VILA CLARO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA CLAYTON", label: "VILA CLAYTON", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA CONCEIÇÃO", label: "VILA CONCEIÇÃO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA CONRADO", label: "VILA CONRADO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA DAMÁGLIO", label: "VILA DAMÁGLIO", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA DOS BANCÁRIOS", label: "VILA DOS BANCÁRIOS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA ESPERANÇA", label: "VILA ESPERANÇA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA ESTRELA", label: "VILA ESTRELA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA GOMES", label: "VILA GOMES", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA ISABEL", label: "VILA ISABEL", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA LOYOLA", label: "VILA LOYOLA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA LUZITANA", label: "VILA LUZITANA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA MAGNÓLIA", label: "VILA MAGNÓLIA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA NOSSA SENHORA FÁTIMA", label: "VILA NOSSA SENHORA FÁTIMA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA OPERÁRIA", label: "VILA OPERÁRIA", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA ORIENTAL", label: "VILA ORIENTAL", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA SANTA EDWIRGES", label: "VILA SANTA EDWIRGES", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA SÃO JOSÉ", label: "VILA SÃO JOSÉ", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA TENENTE VASCONCELOS", label: "VILA TENENTE VASCONCELOS", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA TRAFANI", label: "VILA TRAFANI", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA VALENTIM", label: "VILA VALENTIM", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA WESTIN", label: "VILA WESTIN", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
    { value: "VILA ZANETTI", label: "VILA ZANETTI", filter: { city: "SÃO JOÃO DA BOA VISTA" } },
]
