export const brazilian_kind_street = [
    { short: "ACAMP", value: "ACAMPAMENTO", label: "ACAMPAMENTO" },
    { short: "AC", value: "ACESSO", label: "ACESSO" },
    { short: "AD", value: "ADRO", label: "ADRO" },
    { short: "ERA", value: "AEROPORTO", label: "AEROPORTO" },
    { short: "AL", value: "ALAMEDA", label: "ALAMEDA" },
    { short: "AT", value: "ALTO", label: "ALTO" },
    { short: "A", value: "AREA", label: "AREA" },
    { short: "AE", value: "AREA ESPECIAL", label: "AREA ESPECIAL" },
    { short: "ART", value: "ARTERIA", label: "ARTERIA" },
    { short: "ATL", value: "ATALHO", label: "ATALHO" },
    { short: "AV", value: "AVENIDA", label: "AVENIDA" },
    { short: "AV-CONT", value: "AVENIDA CONTORNO", label: "AVENIDA CONTORNO" },
    { short: "BX", value: "BAIXA", label: "BAIXA" },
    { short: "BLO", value: "BALAO", label: "BALAO" },
    { short: "BAL", value: "BALNEARIO", label: "BALNEARIO" },
    { short: "BC", value: "BECO", label: "BECO" },
    { short: "BELV", value: "BELVEDERE", label: "BELVEDERE" },
    { short: "BL", value: "BLOCO", label: "BLOCO" },
    { short: "BSQ", value: "BOSQUE", label: "BOSQUE" },
    { short: "BVD", value: "BOULEVARD", label: "BOULEVARD" },
    { short: "BCO", value: "BURACO", label: "BURACO" },
    { short: "C", value: "CAIS", label: "CAIS" },
    { short: "CALC", value: "CALCADA", label: "CALCADA" },
    { short: "CAM", value: "CAMINHO", label: "CAMINHO" },
    { short: "CPO", value: "CAMPO", label: "CAMPO" },
    { short: "CAN", value: "CANAL", label: "CANAL" },
    { short: "CHAP", value: "CHACARA", label: "CHACARA" },
    { short: "CHAP", value: "CHAPADAO", label: "CHAPADAO" },
    { short: "CIRC", value: "CIRCULAR", label: "CIRCULAR" },
    { short: "COL", value: "COLONIA", label: "COLONIA" },
    { short: "CMP-VR", value: "COMPLEXO VIARIO", label: "COMPLEXO VIARIO" },
    { short: "COND", value: "CONDOMINIO", label: "CONDOMINIO" },
    { short: "CJ", value: "CONJUNTO", label: "CONJUNTO" },
    { short: "COR", value: "CORREDOR", label: "CORREDOR" },
    { short: "CRG", value: "CORREGO", label: "CORREGO" },
    { short: "DSC", value: "DESCIDA", label: "DESCIDA" },
    { short: "DSV", value: "DESVIO", label: "DESVIO" },
    { short: "DT", value: "DISTRITO", label: "DISTRITO" },
    { short: "EVD", value: "ELEVADA", label: "ELEVADA" },
    { short: "ENT-PART", value: "ENTRADA PARTICULAR", label: "ENTRADA PARTICULAR" },
    { short: "EQ", value: "ENTRE QUADRA", label: "ENTRE QUADRA" },
    { short: "ESC", value: "ESCADA", label: "ESCADA" },
    { short: "ESP", value: "ESPLANADA", label: "ESPLANADA" },
    { short: "ETC", value: "ESTACAO", label: "ESTACAO" },
    { short: "ESTC", value: "ESTACIONAMENTO", label: "ESTACIONAMENTO" },
    { short: "ETD", value: "ESTADIO", label: "ESTADIO" },
    { short: "ETN", value: "ESTANCIA", label: "ESTANCIA" },
    { short: "EST", value: "ESTRADA", label: "ESTRADA" },
    { short: "EST-MUN ", value: "ESTRADA MUNICIPAL", label: "ESTRADA MUNICIPAL" },
    { short: "FAV", value: "FAVELA", label: "FAVELA" },
    { short: "FAZ", value: "FAZENDA", label: "FAZENDA" },
    { short: "FRA", value: "FEIRA", label: "FEIRA" },
    { short: "FER", value: "FERROVIA", label: "FERROVIA" },
    { short: "FNT", value: "FONTE", label: "FONTE" },
    { short: "FTE", value: "FORTE", label: "FORTE" },
    { short: "GAL", value: "GALERIA", label: "GALERIA" },
    { short: "GJA", value: "GRANJA", label: "GRANJA" },
    { short: "HAB", value: "HABITACIONAL", label: "HABITACIONAL" },
    { short: "IA", value: "ILHA", label: "ILHA" },
    { short: "JD", value: "JARDIM", label: "JARDIM" },
    { short: "JDE", value: "JARDINETE", label: "JARDINETE" },
    { short: "LD", value: "LADEIRA", label: "LADEIRA" },
    { short: "LG", value: "LAGO", label: "LAGO" },
    { short: "LGA", value: "LAGOA", label: "LAGOA" },
    { short: "LRG", value: "LARGO", label: "LARGO" },
    { short: "LOT", value: "LOTEAMENTO", label: "LOTEAMENTO" },
    { short: "MNA", value: "MARINA", label: "MARINA" },
    { short: "MOD", value: "MODULO", label: "MODULO" },
    { short: "TEM", value: "MONTE", label: "MONTE" },
    { short: "MRO", value: "MORRO", label: "MORRO" },
    { short: "NUC", value: "NUCLEO", label: "NUCLEO" },
    { short: "PDA", value: "PARADA", label: "PARADA" },
    { short: "PDO", value: "PARADOURO", label: "PARADOURO" },
    { short: "PAR", value: "PARALELA", label: "PARALELA" },
    { short: "PRQ", value: "PARQUE", label: "PARQUE" },
    { short: "PSG", value: "PASSAGEM", label: "PASSAGEM" },
    { short: "PSC-SUB", value: "PASSAGEM SUBTERRANEA", label: "PASSAGEM SUBTERRANEA" },
    { short: "PSA", value: "PASSARELA", label: "PASSARELA" },
    { short: "PAS", value: "PASSEIO", label: "PASSEIO" },
    { short: "PAT", value: "PATIO", label: "PATIO" },
    { short: "PNT", value: "PONTA", label: "PONTA" },
    { short: "PTE", value: "PONTE", label: "PONTE" },
    { short: "PTO", value: "PORTO", label: "PORTO" },
    { short: "PC", value: "PRACA", label: "PRACA" },
    { short: "PC-ESP", value: "PRACA DE ESPORTES", label: "PRACA DE ESPORTES" },
    { short: "PR", value: "PRAIA", label: "PRAIA" },
    { short: "PRL", value: "PROLONGAMENTO", label: "PROLONGAMENTO" },
    { short: "Q", value: "QUADRA", label: "QUADRA" },
    { short: "QTA", value: "QUINTA", label: "QUINTA" },
    { short: "QTAS", value: "QUINTA", label: "QUINTA" },
    { short: "RAM", value: "RAMAL", label: "RAMAL" },
    { short: "RMP", value: "RAMPA", label: "RAMPA" },
    { short: "REC", value: "RECANTO", label: "RECANTO" },
    { short: "RES", value: "RESIDENCIAL", label: "RESIDENCIAL" },
    { short: "RET", value: "RETA", label: "RETA" },
    { short: "RER", value: "RETIRO", label: "RETIRO" },
    { short: "RTN", value: "RETORNO", label: "RETORNO" },
    { short: "ROD-AN", value: "RODO ANEL", label: "RODO ANEL" },
    { short: "ROD", value: "RODOVIA", label: "RODOVIA" },
    { short: "RTT", value: "ROTATORIA", label: "ROTATORIA" },
    { short: "ROT", value: "ROTULA", label: "ROTULA" },
    { short: "R", value: "RUA", label: "RUA" },
    { short: "R-LIG", value: "RUA DE LIGACAO", label: "RUA DE LIGACAO" },
    { short: "R-PED", value: "RUA DE PEDESTRE", label: "RUA DE PEDESTRE" },
    { short: "SRV", value: "SERVIDAO", label: "SERVIDAO" },
    { short: "ST", value: "SETOR", label: "SETOR" },
    { short: "SIT", value: "SITIO", label: "SITIO" },
    { short: "SUB", value: "SUBIDA", label: "SUBIDA" },
    { short: "TER", value: "TERMINAL", label: "TERMINAL" },
    { short: "TV", value: "TRAVESSA", label: "TRAVESSA" },
    { short: "TV-PART", value: "TRAVESSA PARTICULAR", label: "TRAVESSA PARTICULAR" },
    { short: "TRV", value: "TRECHO", label: "TRECHO" },
    { short: "TRV", value: "TREVO", label: "TREVO" },
    { short: "TCH", value: "TRINCHEIRA", label: "TRINCHEIRA" },
    { short: "TUN", value: "TUNEL", label: "TUNEL" },
    { short: "UNID", value: "UNIDADE", label: "UNIDADE" },
    { short: "VAL", value: "VALA", label: "VALA" },
    { short: "VLE", value: "VALE", label: "VALE" },
    { short: "VRTE", value: "VARIANTE", label: "VARIANTE" },
    { short: "VER", value: "VEREDA", label: "VEREDA" },
    { short: "V", value: "VIA", label: "VIA" },
    { short: "V-AC", value: "VIA DE ACESSO", label: "VIA DE ACESSO" },
    { short: "V-PED", value: "VIA DE PEDESTRE", label: "VIA DE PEDESTRE" },
    { short: "V-EVD", value: "VIA ELEVADO", label: "VIA ELEVADO" },
    { short: "V-EXP", value: "VIA EXPRESSA", label: "VIA EXPRESSA" },
    { short: "VD", value: "VIADUTO", label: "VIADUTO" },
    { short: "VLA", value: "VIELA", label: "VIELA" },
    { short: "VL", value: "VILA", label: "VILA" },
    { short: "ZIG-ZAG ", value: "ZIGUE - ZAGUE", label: "ZIGUE - ZAGUE" },
]