export const brazilian_districts = [
    { value: "AC", label: "AC - Acre", filter: { country: "BRASIL" } },
    { value: "AL", label: "AL - Alagoas", filter: { country: "BRASIL" } },
    { value: "AP", label: "AP - Macapá", filter: { country: "BRASIL" } },
    { value: "AM", label: "AM - Amapá", filter: { country: "BRASIL" } },
    { value: "BA", label: "BA - Bahia", filter: { country: "BRASIL" } },
    { value: "CE", label: "CE - Ceará", filter: { country: "BRASIL" } },
    { value: "DF", label: "DF - Distrito Federal", filter: { country: "BRASIL" } },
    { value: "ES", label: "ES - Espírito Santo", filter: { country: "BRASIL" } },
    { value: "GO", label: "GO - Goiás", filter: { country: "BRASIL" } },
    { value: "MA", label: "MA - Maranhão", filter: { country: "BRASIL" } },
    { value: "MT", label: "MT - Mato Grosso", filter: { country: "BRASIL" } },
    { value: "MS", label: "MS - Mato Grosso do Sul", filter: { country: "BRASIL" } },
    { value: "MG", label: "MG - Minas Gerais", filter: { country: "BRASIL" } },
    { value: "PA", label: "PA - Pará", filter: { country: "BRASIL" } },
    { value: "PB", label: "PB - Paraíba", filter: { country: "BRASIL" } },
    { value: "PR", label: "PR - Paraná", filter: { country: "BRASIL" } },
    { value: "PE", label: "PE - Pernambuco", filter: { country: "BRASIL" } },
    { value: "PI", label: "PI - Piauí", filter: { country: "BRASIL" } },
    { value: "RJ", label: "RJ - Rio de Janeiro", filter: { country: "BRASIL" } },
    { value: "RN", label: "RN - Rio Grande do Norte", filter: { country: "BRASIL" } },
    { value: "RS", label: "RS - Rio Grande do Sul", filter: { country: "BRASIL" } },
    { value: "RO", label: "RO - Rondônia", filter: { country: "BRASIL" } },
    { value: "RR", label: "RR - Roraima", filter: { country: "BRASIL" } },
    { value: "SC", label: "SC - Santa Catarina", filter: { country: "BRASIL" } },
    { value: "SP", label: "SP - São Paulo", filter: { country: "BRASIL" } },
    { value: "SE", label: "SE - Sergipe", filter: { country: "BRASIL" } },
    { value: "TO", label: "TO - Tocantins", filter: { country: "BRASIL" } },
    { value: "União", label: "União", filter: { country: "BRASIL" } },
];