export const cnpj_nature = [
    {value: '101-5 - Órgão Público do Poder Executivo Federal', label: '101-5 - Órgão Público do Poder Executivo Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '102-3 - Órgão Público do Poder Executivo Estadual ou do Distrito Federal', label: '102-3 - Órgão Público do Poder Executivo Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '103-1 - Órgão Público do Poder Executivo Municipal', label: '103-1 - Órgão Público do Poder Executivo Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '104-0 - Órgão Público do Poder Legislativo Federal', label: '104-0 - Órgão Público do Poder Legislativo Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '105-8 - Órgão Público do Poder Legislativo Estadual ou do Distrito Federal', label: '105-8 - Órgão Público do Poder Legislativo Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '106-6 - Órgão Público do Poder Legislativo Municipal', label: '106-6 - Órgão Público do Poder Legislativo Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '107-4 - Órgão Público do Poder Judiciário Federal', label: '107-4 - Órgão Público do Poder Judiciário Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '108-2 - Órgão Público do Poder Judiciário Estadual', label: '108-2 - Órgão Público do Poder Judiciário Estadual', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '110-4 - Autarquia Federal', label: '110-4 - Autarquia Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '111-2 - Autarquia Estadual ou do Distrito Federal', label: '111-2 - Autarquia Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '112-0 - Autarquia Municipal', label: '112-0 - Autarquia Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '113-9 - Fundação Pública de Direito Público Federal', label: '113-9 - Fundação Pública de Direito Público Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '114-7 - Fundação Pública de Direito Público Estadual ou do Distrito Federal', label: '114-7 - Fundação Pública de Direito Público Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '115-5 - Fundação Pública de Direito Público Municipal', label: '115-5 - Fundação Pública de Direito Público Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '116-3 - Órgão Público Autônomo Federal', label: '116-3 - Órgão Público Autônomo Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '117-1 - Órgão Público Autônomo Estadual ou do Distrito Federal', label: '117-1 - Órgão Público Autônomo Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '118-0 - Órgão Público Autônomo Municipal', label: '118-0 - Órgão Público Autônomo Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '119-8 - Comissão Polinacional', label: '119-8 - Comissão Polinacional', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '121-0 - Consórcio Público de Direito Público (Associação Pública)', label: '121-0 - Consórcio Público de Direito Público (Associação Pública)', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '122-8 - Consórcio Público de Direito Privado', label: '122-8 - Consórcio Público de Direito Privado', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '123-6 - Estado ou Distrito Federal', label: '123-6 - Estado ou Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '124-4 - Município', label: '124-4 - Município', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '125-2 - Fundação Pública de Direito Privado Federal', label: '125-2 - Fundação Pública de Direito Privado Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '126-0 - Fundação Pública de Direito Privado Estadual ou do Distrito Federal', label: '126-0 - Fundação Pública de Direito Privado Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '127-9 - Fundação Pública de Direito Privado Municipal', label: '127-9 - Fundação Pública de Direito Privado Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '128-7 - Fundo Público da Administração Indireta Federal', label: '128-7 - Fundo Público da Administração Indireta Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '129-5 - Fundo Público da Administração Indireta Estadual ou do Distrito Federal', label: '129-5 - Fundo Público da Administração Indireta Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '130-9 - Fundo Público da Administração Indireta Municipal', label: '130-9 - Fundo Público da Administração Indireta Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '131-7 - Fundo Público da Administração Direta Federal', label: '131-7 - Fundo Público da Administração Direta Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '132-5 - Fundo Público da Administração Direta Estadual ou do Distrito Federal', label: '132-5 - Fundo Público da Administração Direta Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '133-3 - Fundo Público da Administração Direta Municipal', label: '133-3 - Fundo Público da Administração Direta Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '134-1 - União', label: '134-1 - União', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '201-1 - Empresa Pública', label: '201-1 - Empresa Pública', type: 'PRIVADA'},
    {value: '203-8 - Sociedade de Economia Mista', label: '203-8 - Sociedade de Economia Mista', type: 'PRIVADA'},
    {value: '204-6 - Sociedade Anônima Aberta', label: '204-6 - Sociedade Anônima Aberta', type: 'PRIVADA'},
    {value: '205-4 - Sociedade Anônima Fechada', label: '205-4 - Sociedade Anônima Fechada', type: 'PRIVADA'},
    {value: '206-2 - Sociedade Empresária Limitada', label: '206-2 - Sociedade Empresária Limitada', type: 'PRIVADA'},
    {value: '207-0 - Sociedade Empresária em Nome Coletivo', label: '207-0 - Sociedade Empresária em Nome Coletivo', type: 'PRIVADA'},
    {value: '208-9 - Sociedade Empresária em Comandita Simples', label: '208-9 - Sociedade Empresária em Comandita Simples', type: 'PRIVADA'},
    {value: '209-7 - Sociedade Empresária em Comandita por Ações', label: '209-7 - Sociedade Empresária em Comandita por Ações', type: 'PRIVADA'},
    {value: '212-7 - Sociedade em Conta de Participação', label: '212-7 - Sociedade em Conta de Participação', type: 'PRIVADA'},
    {value: '213-5 - Empresário (Individual)', label: '213-5 - Empresário (Individual)', type: 'PRIVADA'},
    {value: '214-3 - Cooperativa', label: '214-3 - Cooperativa', type: 'PRIVADA'},
    {value: '215-1 - Consórcio de Sociedades', label: '215-1 - Consórcio de Sociedades', type: 'PRIVADA'},
    {value: '216-0 - Grupo de Sociedades', label: '216-0 - Grupo de Sociedades', type: 'PRIVADA'},
    {value: '217-8 - Estabelecimento, no Brasil, de Sociedade Estrangeira', label: '217-8 - Estabelecimento, no Brasil, de Sociedade Estrangeira', type: 'PRIVADA'},
    {value: '219-4 - Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira', label: '219-4 - Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira', type: 'PRIVADA'},
    {value: '221-6 - Empresa Domiciliada no Exterior', label: '221-6 - Empresa Domiciliada no Exterior', type: 'PRIVADA'},
    {value: '222-4 - Clube/Fundo de Investimento', label: '222-4 - Clube/Fundo de Investimento', type: 'PRIVADA'},
    {value: '223-2 - Sociedade Simples Pura', label: '223-2 - Sociedade Simples Pura', type: 'PRIVADA'},
    {value: '224-0 - Sociedade Simples Limitada', label: '224-0 - Sociedade Simples Limitada', type: 'PRIVADA'},
    {value: '225-9 - Sociedade Simples em Nome Coletivo', label: '225-9 - Sociedade Simples em Nome Coletivo', type: 'PRIVADA'},
    {value: '226-7 - Sociedade Simples em Comandita Simples', label: '226-7 - Sociedade Simples em Comandita Simples', type: 'PRIVADA'},
    {value: '227-5 - Empresa Binacional', label: '227-5 - Empresa Binacional', type: 'PRIVADA'},
    {value: '228-3 - Consórcio de Empregadores', label: '228-3 - Consórcio de Empregadores', type: 'PRIVADA'},
    {value: '229-1 - Consórcio Simples', label: '229-1 - Consórcio Simples', type: 'PRIVADA'},
    {value: '230-5 - Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)', label: '230-5 - Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)', type: 'PRIVADA'},
    {value: '231-3 - Empresa Individual de Responsabilidade Limitada (de Natureza Simples)', label: '231-3 - Empresa Individual de Responsabilidade Limitada (de Natureza Simples)', type: 'PRIVADA'},
    {value: '232-1 – Sociedade Unipessoal de Advogados', label: '232-1 – Sociedade Unipessoal de Advogados', type: 'PRIVADA'},
    {value: '233-0 – Cooperativas de Consumo', label: '233-0 – Cooperativas de Consumo', type: 'PRIVADA'},
    {value: '303-4 - Serviço Notarial e Registral (Cartório)', label: '303-4 - Serviço Notarial e Registral (Cartório)', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '306-9 - Fundação Privada', label: '306-9 - Fundação Privada', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '307-7 - Serviço Social Autônomo', label: '307-7 - Serviço Social Autônomo', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '308-5 - Condomínio Edilício', label: '308-5 - Condomínio Edilício', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '310-7 - Comissão de Conciliação Prévia', label: '310-7 - Comissão de Conciliação Prévia', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '311-5 - Entidade de Mediação e Arbitragem', label: '311-5 - Entidade de Mediação e Arbitragem', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '313-1 - Entidade Sindical', label: '313-1 - Entidade Sindical', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '320-4 - Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras', label: '320-4 - Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '321-2 - Fundação ou Associação Domiciliada no Exterior', label: '321-2 - Fundação ou Associação Domiciliada no Exterior', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '322-0 - Organização Religiosa', label: '322-0 - Organização Religiosa', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '323-9 - Comunidade Indígena', label: '323-9 - Comunidade Indígena', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '324-7 - Fundo Privado', label: '324-7 - Fundo Privado', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '325-5 - Órgão de Direção Nacional de Partido Político', label: '325-5 - Órgão de Direção Nacional de Partido Político', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '326-3 - Órgão de Direção Regional de Partido Político', label: '326-3 - Órgão de Direção Regional de Partido Político', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '327-1 - Órgão de Direção Local de Partido Político', label: '327-1 - Órgão de Direção Local de Partido Político', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '328-0 - Comitê Financeiro de Partido Político', label: '328-0 - Comitê Financeiro de Partido Político', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '329-8 - Frente Plebiscitária ou Referendária', label: '329-8 - Frente Plebiscitária ou Referendária', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '330-1 - Organização Social (OS)', label: '330-1 - Organização Social (OS)', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '331-0 - Demais Condomínios', label: '331-0 - Demais Condomínios', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '399-9 - Associação Privada', label: '399-9 - Associação Privada', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '401-4 - Empresa Individual Imobiliária', label: '401-4 - Empresa Individual Imobiliária', type: 'PESSOA FÍSICAS'},
    {value: '402-2 - Segurado Especial', label: '402-2 - Segurado Especial', type: 'PESSOA FÍSICAS'},
    {value: '408-1 - Contribuinte individual', label: '408-1 - Contribuinte individual', type: 'PESSOA FÍSICAS'},
    {value: '409-0 - Candidato a Cargo Político Eletivo', label: '409-0 - Candidato a Cargo Político Eletivo', type: 'PESSOA FÍSICAS'},
    {value: '411-1 - Leiloeiro', label: '411-1 - Leiloeiro', type: 'PESSOA FÍSICAS'},
    {value: '412-0 - Produtor Rural (Pessoa Física)', label: '412-0 - Produtor Rural (Pessoa Física)', type: 'PESSOA FÍSICAS'},
    {value: '501-0 - Organização Internacional', label: '501-0 - Organização Internacional', type: 'ORGANIZAÇÃO INTERNACIONAL'},
    {value: '502-9 - Representação Diplomática Estrangeira', label: '502-9 - Representação Diplomática Estrangeira', type: 'ORGANIZAÇÃO INTERNACIONAL'},
    {value: '503-7 - Outras Instituições Extraterritoriais', label: '503-7 - Outras Instituições Extraterritoriais', type: 'ORGANIZAÇÃO INTERNACIONAL'},
];