export const cnpj_nature = [
    {value: '101-5 - Órgão Público do Poder Executivo Federal', text: '101-5 - Órgão Público do Poder Executivo Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '102-3 - Órgão Público do Poder Executivo Estadual ou do Distrito Federal', text: '102-3 - Órgão Público do Poder Executivo Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '103-1 - Órgão Público do Poder Executivo Municipal', text: '103-1 - Órgão Público do Poder Executivo Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '104-0 - Órgão Público do Poder Legislativo Federal', text: '104-0 - Órgão Público do Poder Legislativo Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '105-8 - Órgão Público do Poder Legislativo Estadual ou do Distrito Federal', text: '105-8 - Órgão Público do Poder Legislativo Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '106-6 - Órgão Público do Poder Legislativo Municipal', text: '106-6 - Órgão Público do Poder Legislativo Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '107-4 - Órgão Público do Poder Judiciário Federal', text: '107-4 - Órgão Público do Poder Judiciário Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '108-2 - Órgão Público do Poder Judiciário Estadual', text: '108-2 - Órgão Público do Poder Judiciário Estadual', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '110-4 - Autarquia Federal', text: '110-4 - Autarquia Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '111-2 - Autarquia Estadual ou do Distrito Federal', text: '111-2 - Autarquia Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '112-0 - Autarquia Municipal', text: '112-0 - Autarquia Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '113-9 - Fundação Pública de Direito Público Federal', text: '113-9 - Fundação Pública de Direito Público Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '114-7 - Fundação Pública de Direito Público Estadual ou do Distrito Federal', text: '114-7 - Fundação Pública de Direito Público Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '115-5 - Fundação Pública de Direito Público Municipal', text: '115-5 - Fundação Pública de Direito Público Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '116-3 - Órgão Público Autônomo Federal', text: '116-3 - Órgão Público Autônomo Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '117-1 - Órgão Público Autônomo Estadual ou do Distrito Federal', text: '117-1 - Órgão Público Autônomo Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '118-0 - Órgão Público Autônomo Municipal', text: '118-0 - Órgão Público Autônomo Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '119-8 - Comissão Polinacional', text: '119-8 - Comissão Polinacional', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '121-0 - Consórcio Público de Direito Público (Associação Pública)', text: '121-0 - Consórcio Público de Direito Público (Associação Pública)', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '122-8 - Consórcio Público de Direito Privado', text: '122-8 - Consórcio Público de Direito Privado', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '123-6 - Estado ou Distrito Federal', text: '123-6 - Estado ou Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '124-4 - Município', text: '124-4 - Município', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '125-2 - Fundação Pública de Direito Privado Federal', text: '125-2 - Fundação Pública de Direito Privado Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '126-0 - Fundação Pública de Direito Privado Estadual ou do Distrito Federal', text: '126-0 - Fundação Pública de Direito Privado Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '127-9 - Fundação Pública de Direito Privado Municipal', text: '127-9 - Fundação Pública de Direito Privado Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '128-7 - Fundo Público da Administração Indireta Federal', text: '128-7 - Fundo Público da Administração Indireta Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '129-5 - Fundo Público da Administração Indireta Estadual ou do Distrito Federal', text: '129-5 - Fundo Público da Administração Indireta Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '130-9 - Fundo Público da Administração Indireta Municipal', text: '130-9 - Fundo Público da Administração Indireta Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '131-7 - Fundo Público da Administração Direta Federal', text: '131-7 - Fundo Público da Administração Direta Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '132-5 - Fundo Público da Administração Direta Estadual ou do Distrito Federal', text: '132-5 - Fundo Público da Administração Direta Estadual ou do Distrito Federal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '133-3 - Fundo Público da Administração Direta Municipal', text: '133-3 - Fundo Público da Administração Direta Municipal', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '134-1 - União', text: '134-1 - União', type: "MUNICIPAL, ESTADUAL OU FEDERAL"},
    {value: '201-1 - Empresa Pública', text: '201-1 - Empresa Pública', type: 'PRIVADA'},
    {value: '203-8 - Sociedade de Economia Mista', text: '203-8 - Sociedade de Economia Mista', type: 'PRIVADA'},
    {value: '204-6 - Sociedade Anônima Aberta', text: '204-6 - Sociedade Anônima Aberta', type: 'PRIVADA'},
    {value: '205-4 - Sociedade Anônima Fechada', text: '205-4 - Sociedade Anônima Fechada', type: 'PRIVADA'},
    {value: '206-2 - Sociedade Empresária Limitada', text: '206-2 - Sociedade Empresária Limitada', type: 'PRIVADA'},
    {value: '207-0 - Sociedade Empresária em Nome Coletivo', text: '207-0 - Sociedade Empresária em Nome Coletivo', type: 'PRIVADA'},
    {value: '208-9 - Sociedade Empresária em Comandita Simples', text: '208-9 - Sociedade Empresária em Comandita Simples', type: 'PRIVADA'},
    {value: '209-7 - Sociedade Empresária em Comandita por Ações', text: '209-7 - Sociedade Empresária em Comandita por Ações', type: 'PRIVADA'},
    {value: '212-7 - Sociedade em Conta de Participação', text: '212-7 - Sociedade em Conta de Participação', type: 'PRIVADA'},
    {value: '213-5 - Empresário (Individual)', text: '213-5 - Empresário (Individual)', type: 'PRIVADA'},
    {value: '214-3 - Cooperativa', text: '214-3 - Cooperativa', type: 'PRIVADA'},
    {value: '215-1 - Consórcio de Sociedades', text: '215-1 - Consórcio de Sociedades', type: 'PRIVADA'},
    {value: '216-0 - Grupo de Sociedades', text: '216-0 - Grupo de Sociedades', type: 'PRIVADA'},
    {value: '217-8 - Estabelecimento, no Brasil, de Sociedade Estrangeira', text: '217-8 - Estabelecimento, no Brasil, de Sociedade Estrangeira', type: 'PRIVADA'},
    {value: '219-4 - Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira', text: '219-4 - Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira', type: 'PRIVADA'},
    {value: '221-6 - Empresa Domiciliada no Exterior', text: '221-6 - Empresa Domiciliada no Exterior', type: 'PRIVADA'},
    {value: '222-4 - Clube/Fundo de Investimento', text: '222-4 - Clube/Fundo de Investimento', type: 'PRIVADA'},
    {value: '223-2 - Sociedade Simples Pura', text: '223-2 - Sociedade Simples Pura', type: 'PRIVADA'},
    {value: '224-0 - Sociedade Simples Limitada', text: '224-0 - Sociedade Simples Limitada', type: 'PRIVADA'},
    {value: '225-9 - Sociedade Simples em Nome Coletivo', text: '225-9 - Sociedade Simples em Nome Coletivo', type: 'PRIVADA'},
    {value: '226-7 - Sociedade Simples em Comandita Simples', text: '226-7 - Sociedade Simples em Comandita Simples', type: 'PRIVADA'},
    {value: '227-5 - Empresa Binacional', text: '227-5 - Empresa Binacional', type: 'PRIVADA'},
    {value: '228-3 - Consórcio de Empregadores', text: '228-3 - Consórcio de Empregadores', type: 'PRIVADA'},
    {value: '229-1 - Consórcio Simples', text: '229-1 - Consórcio Simples', type: 'PRIVADA'},
    {value: '230-5 - Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)', text: '230-5 - Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)', type: 'PRIVADA'},
    {value: '231-3 - Empresa Individual de Responsabilidade Limitada (de Natureza Simples)', text: '231-3 - Empresa Individual de Responsabilidade Limitada (de Natureza Simples)', type: 'PRIVADA'},
    {value: '232-1 – Sociedade Unipessoal de Advogados', text: '232-1 – Sociedade Unipessoal de Advogados', type: 'PRIVADA'},
    {value: '233-0 – Cooperativas de Consumo', text: '233-0 – Cooperativas de Consumo', type: 'PRIVADA'},
    {value: '303-4 - Serviço Notarial e Registral (Cartório)', text: '303-4 - Serviço Notarial e Registral (Cartório)', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '306-9 - Fundação Privada', text: '306-9 - Fundação Privada', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '307-7 - Serviço Social Autônomo', text: '307-7 - Serviço Social Autônomo', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '308-5 - Condomínio Edilício', text: '308-5 - Condomínio Edilício', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '310-7 - Comissão de Conciliação Prévia', text: '310-7 - Comissão de Conciliação Prévia', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '311-5 - Entidade de Mediação e Arbitragem', text: '311-5 - Entidade de Mediação e Arbitragem', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '313-1 - Entidade Sindical', text: '313-1 - Entidade Sindical', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '320-4 - Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras', text: '320-4 - Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '321-2 - Fundação ou Associação Domiciliada no Exterior', text: '321-2 - Fundação ou Associação Domiciliada no Exterior', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '322-0 - Organização Religiosa', text: '322-0 - Organização Religiosa', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '323-9 - Comunidade Indígena', text: '323-9 - Comunidade Indígena', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '324-7 - Fundo Privado', text: '324-7 - Fundo Privado', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '325-5 - Órgão de Direção Nacional de Partido Político', text: '325-5 - Órgão de Direção Nacional de Partido Político', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '326-3 - Órgão de Direção Regional de Partido Político', text: '326-3 - Órgão de Direção Regional de Partido Político', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '327-1 - Órgão de Direção Local de Partido Político', text: '327-1 - Órgão de Direção Local de Partido Político', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '328-0 - Comitê Financeiro de Partido Político', text: '328-0 - Comitê Financeiro de Partido Político', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '329-8 - Frente Plebiscitária ou Referendária', text: '329-8 - Frente Plebiscitária ou Referendária', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '330-1 - Organização Social (OS)', text: '330-1 - Organização Social (OS)', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '331-0 - Demais Condomínios', text: '331-0 - Demais Condomínios', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '399-9 - Associação Privada', text: '399-9 - Associação Privada', type: 'ENTIDADE SEM FINS LUCRATIVOS'},
    {value: '401-4 - Empresa Individual Imobiliária', text: '401-4 - Empresa Individual Imobiliária', type: 'PESSOA FÍSICAS'},
    {value: '402-2 - Segurado Especial', text: '402-2 - Segurado Especial', type: 'PESSOA FÍSICAS'},
    {value: '408-1 - Contribuinte individual', text: '408-1 - Contribuinte individual', type: 'PESSOA FÍSICAS'},
    {value: '409-0 - Candidato a Cargo Político Eletivo', text: '409-0 - Candidato a Cargo Político Eletivo', type: 'PESSOA FÍSICAS'},
    {value: '411-1 - Leiloeiro', text: '411-1 - Leiloeiro', type: 'PESSOA FÍSICAS'},
    {value: '412-0 - Produtor Rural (Pessoa Física)', text: '412-0 - Produtor Rural (Pessoa Física)', type: 'PESSOA FÍSICAS'},
    {value: '501-0 - Organização Internacional', text: '501-0 - Organização Internacional', type: 'ORGANIZAÇÃO INTERNACIONAL'},
    {value: '502-9 - Representação Diplomática Estrangeira', text: '502-9 - Representação Diplomática Estrangeira', type: 'ORGANIZAÇÃO INTERNACIONAL'},
    {value: '503-7 - Outras Instituições Extraterritoriais', text: '503-7 - Outras Instituições Extraterritoriais', type: 'ORGANIZAÇÃO INTERNACIONAL'},
];