export const countries = [
    {value: "AFEGANISTÃO", label: "AFEGANISTÃO", main: false},
    {value: "ÁFRICA DO SUL", label: "ÁFRICA DO SUL", main: false},
    {value: "ALBÂNIA", label: "ALBÂNIA", main: false},
    {value: "ALEMANHA", label: "ALEMANHA", main: true},
    {value: "ANDORRA", label: "ANDORRA", main: false},
    {value: "ANGOLA", label: "ANGOLA", main: false},
    {value: "ANTÍGUA E BARBUDA", label: "ANTÍGUA E BARBUDA", main: false},
    {value: "ARÁBIA SAUDITA", label: "ARÁBIA SAUDITA", main: false},
    {value: "ARGÉLIA", label: "ARGÉLIA", main: false},
    {value: "ARGENTINA", label: "ARGENTINA", main: true},
    {value: "ARMÊNIA", label: "ARMÊNIA", main: false},
    {value: "AUSTRÁLIA", label: "AUSTRÁLIA", main: false},
    {value: "ÁUSTRIA", label: "ÁUSTRIA", main: false},
    {value: "AZERBAIDJÃO", label: "AZERBAIDJÃO", main: false},
    {value: "BAHAMAS", label: "BAHAMAS", main: false},
    {value: "BANGLADESH", label: "BANGLADESH", main: false},
    {value: "BARBADOS", label: "BARBADOS", main: false},
    {value: "BELARUS", label: "BELARUS", main: false},
    {value: "BÉLGICA", label: "BÉLGICA", main: false},
    {value: "BELIZE", label: "BELIZE", main: false},
    {value: "BENIN", label: "BENIN", main: false},
    {value: "BOLÍVIA", label: "BOLÍVIA", main: false},
    {value: "BÓSNIA-HERZEGÓVINA", label: "BÓSNIA-HERZEGÓVINA", main: false},
    {value: "BOTSUANA", label: "BOTSUANA", main: false},
    {value: "BRASIL", label: "BRASIL", main: true},
    {value: "BRUNEI", label: "BRUNEI", main: false},
    {value: "BULGÁRIA", label: "BULGÁRIA", main: false},
    {value: "BURKINA FASO", label: "BURKINA FASO", main: false},
    {value: "BURUNDI", label: "BURUNDI", main: false},
    {value: "BUTÃO", label: "BUTÃO", main: false},
    {value: "CABO VERDE", label: "CABO VERDE", main: false},
    {value: "CAMARÕES", label: "CAMARÕES", main: false},
    {value: "CAMBOJA", label: "CAMBOJA", main: false},
    {value: "CATAR", label: "CATAR", main: false},
    {value: "CAZAQUISTÃO", label: "CAZAQUISTÃO", main: false},
    {value: "CHADE", label: "CHADE", main: false},
    {value: "CHILE", label: "CHILE", main: true},
    {value: "CHINA", label: "CHINA", main: false},
    {value: "CHIPRE", label: "CHIPRE", main: false},
    {value: "CINGAPURA", label: "CINGAPURA", main: false},
    {value: "COLÔMBIA", label: "COLÔMBIA", main: true},
    {value: "COMORES", label: "COMORES", main: false},
    {value: "CONGO", label: "CONGO", main: false},
    {value: "CORÉIA DO NORTE", label: "CORÉIA DO NORTE", main: false},
    {value: "CORÉIA DO SUL", label: "CORÉIA DO SUL", main: false},
    {value: "COSTA DO MARFIM", label: "COSTA DO MARFIM", main: false},
    {value: "COSTA RICA", label: "COSTA RICA", main: false},
    {value: "CROÁCIA", label: "CROÁCIA", main: false},
    {value: "CUBA", label: "CUBA", main: true},
    {value: "DINAMARCA", label: "DINAMARCA", main: false},
    {value: "DJIBUTI", label: "DJIBUTI", main: false},
    {value: "DOMINICA", label: "DOMINICA", main: false},
    {value: "EGITO", label: "EGITO", main: false},
    {value: "EL SALVADOR", label: "EL SALVADOR", main: false},
    {value: "EMIRADOS ÁRABES UNIDOS", label: "EMIRADOS ÁRABES UNIDOS", main: false},
    {value: "EQUADOR", label: "EQUADOR", main: false},
    {value: "ERITREIA", label: "ERITREIA", main: false},
    {value: "ESLOVÁQUIA", label: "ESLOVÁQUIA", main: false},
    {value: "ESLOVÊNIA", label: "ESLOVÊNIA", main: false},
    {value: "ESPANHA", label: "ESPANHA", main: false},
    {value: "ESTADOS UNIDOS", label: "ESTADOS UNIDOS", main: true},
    {value: "ESTÔNIA", label: "ESTÔNIA", main: false},
    {value: "ETIÓPIA", label: "ETIÓPIA", main: false},
    {value: "FEDERAÇÃO RUSSA", label: "FEDERAÇÃO RUSSA", main: false},
    {value: "FIJI", label: "FIJI", main: false},
    {value: "FILIPINAS", label: "FILIPINAS", main: false},
    {value: "FINLÂNDIA", label: "FINLÂNDIA", main: false},
    {value: "FRANÇA", label: "FRANÇA", main: false},
    {value: "GABÃO", label: "GABÃO", main: false},
    {value: "GÂMBIA", label: "GÂMBIA", main: false},
    {value: "GANA", label: "GANA", main: false},
    {value: "GEÓRGIA", label: "GEÓRGIA", main: false},
    {value: "GRANADA", label: "GRANADA", main: false},
    {value: "GRÉCIA", label: "GRÉCIA", main: false},
    {value: "GUATEMALA", label: "GUATEMALA", main: false},
    {value: "GUIANA", label: "GUIANA", main: false},
    {value: "GUINÉ-BISSAU", label: "GUINÉ-BISSAU", main: false},
    {value: "GUINÉ-EQUATORIAL", label: "GUINÉ-EQUATORIAL", main: false},
    {value: "HAITI", label: "HAITI", main: false},
    {value: "HOLANDA", label: "HOLANDA", main: false},
    {value: "HONDURAS", label: "HONDURAS", main: false},
    {value: "HUNGRIA", label: "HUNGRIA", main: false},
    {value: "IÉMEN", label: "IÉMEN", main: false},
    {value: "ILHAS MARSHALL", label: "ILHAS MARSHALL", main: false},
    {value: "ILHAS SALOMÃO", label: "ILHAS SALOMÃO", main: false},
    {value: "ÍNDIA", label: "ÍNDIA", main: false},
    {value: "INDONÉSIA", label: "INDONÉSIA", main: false},
    {value: "IRÃ", label: "IRÃ", main: false},
    {value: "IRAQUE", label: "IRAQUE", main: false},
    {value: "IRLANDA", label: "IRLANDA", main: false},
    {value: "ISLÂNDIA", label: "ISLÂNDIA", main: false},
    {value: "ISRAEL", label: "ISRAEL", main: false},
    {value: "ITÁLIA", label: "ITÁLIA", main: false},
    {value: "JAMAICA", label: "JAMAICA", main: false},
    {value: "JAPÃO", label: "JAPÃO", main: false},
    {value: "JORDÂNIA", label: "JORDÂNIA", main: false},
    {value: "KIRIBATI", label: "KIRIBATI", main: false},
    {value: "KUWAIT", label: "KUWAIT", main: false},
    {value: "LAOS", label: "LAOS", main: false},
    {value: "LESOTO", label: "LESOTO", main: false},
    {value: "LETÔNIA", label: "LETÔNIA", main: false},
    {value: "LÍBANO", label: "LÍBANO", main: false},
    {value: "LIBÉRIA", label: "LIBÉRIA", main: false},
    {value: "LÍBIA", label: "LÍBIA", main: false},
    {value: "LIECHTENSTEIN", label: "LIECHTENSTEIN", main: false},
    {value: "LITUÂNIA", label: "LITUÂNIA", main: false},
    {value: "LUXEMBURGO", label: "LUXEMBURGO", main: false},
    {value: "MACEDÔNIA", label: "MACEDÔNIA", main: false},
    {value: "MADAGASCAR", label: "MADAGASCAR", main: false},
    {value: "MALÁSIA", label: "MALÁSIA", main: false},
    {value: "MALAUÍ", label: "MALAUÍ", main: false},
    {value: "MALDIVAS", label: "MALDIVAS", main: false},
    {value: "MALI", label: "MALI", main: false},
    {value: "MALTA", label: "MALTA", main: false},
    {value: "MARROCOS", label: "MARROCOS", main: false},
    {value: "MAURÍCIO", label: "MAURÍCIO", main: false},
    {value: "MAURITÂNIA", label: "MAURITÂNIA", main: false},
    {value: "MÉXICO", label: "MÉXICO", main: false},
    {value: "MIANMAR", label: "MIANMAR", main: false},
    {value: "MICRONÉSIA", label: "MICRONÉSIA", main: false},
    {value: "MOÇAMBIQUE", label: "MOÇAMBIQUE", main: false},
    {value: "MOLDÁVIA", label: "MOLDÁVIA", main: false},
    {value: "MÔNACO", label: "MÔNACO", main: false},
    {value: "MONGÓLIA", label: "MONGÓLIA", main: false},
    {value: "MONTENEGRO", label: "MONTENEGRO", main: false},
    {value: "NAMÍBIA", label: "NAMÍBIA", main: false},
    {value: "NAURU", label: "NAURU", main: false},
    {value: "NEPAL", label: "NEPAL", main: false},
    {value: "NICARÁGUA", label: "NICARÁGUA", main: false},
    {value: "NÍGER", label: "NÍGER", main: false},
    {value: "NIGÉRIA", label: "NIGÉRIA", main: false},
    {value: "NORUEGA", label: "NORUEGA", main: false},
    {value: "NOVA ZELÂNDIA", label: "NOVA ZELÂNDIA", main: false},
    {value: "O CANADÁ", label: "O CANADÁ", main: false},
    {value: "OMÃ", label: "OMÃ", main: false},
    {value: "PALAU", label: "PALAU", main: false},
    {value: "PANAMÁ", label: "PANAMÁ", main: false},
    {value: "PAPUA NOVA GUINÉ", label: "PAPUA NOVA GUINÉ", main: false},
    {value: "PAQUISTÃO", label: "PAQUISTÃO", main: false},
    {value: "PARAGUAI", label: "PARAGUAI", main: false},
    {value: "PERU", label: "PERU", main: false},
    {value: "POLÔNIA", label: "POLÔNIA", main: false},
    {value: "PORTUGAL", label: "PORTUGAL", main: false},
    {value: "QUÊNIA", label: "QUÊNIA", main: false},
    {value: "REINO UNIDO", label: "REINO UNIDO", main: false},
    {value: "REPÚBLICA CENTRO-AFRICANA", label: "REPÚBLICA CENTRO-AFRICANA", main: false},
    {value: "REPÚBLICA DOMINICANA", label: "REPÚBLICA DOMINICANA", main: false},
    {value: "REPÚBLICA TCHECA", label: "REPÚBLICA TCHECA", main: false},
    {value: "ROMÊNIA", label: "ROMÊNIA", main: false},
    {value: "RUANDA", label: "RUANDA", main: false},
    {value: "SAMOA", label: "SAMOA", main: false},
    {value: "SAN MARINO", label: "SAN MARINO", main: false},
    {value: "SANTA LÚCIA", label: "SANTA LÚCIA", main: false},
    {value: "SÃO CRISTÓVÃO E NÉVIS", label: "SÃO CRISTÓVÃO E NÉVIS", main: false},
    {value: "SÃO TOMÉ E PRÍNCIPE", label: "SÃO TOMÉ E PRÍNCIPE", main: false},
    {value: "SÃO VICENTE E GRANADINAS", label: "SÃO VICENTE E GRANADINAS", main: false},
    {value: "SEICHELES", label: "SEICHELES", main: false},
    {value: "SENEGAL", label: "SENEGAL", main: false},
    {value: "SERRA LEOA", label: "SERRA LEOA", main: false},
    {value: "SÉRVIA", label: "SÉRVIA", main: false},
    {value: "SÍRIA", label: "SÍRIA", main: false},
    {value: "SOMÁLIA", label: "SOMÁLIA", main: false},
    {value: "SRI LANKA", label: "SRI LANKA", main: false},
    {value: "SUAZILÂNDIA", label: "SUAZILÂNDIA", main: false},
    {value: "SUDÃO", label: "SUDÃO", main: false},
    {value: "SUÉCIA", label: "SUÉCIA", main: false},
    {value: "SUÍÇA", label: "SUÍÇA", main: false},
    {value: "SURINAME", label: "SURINAME", main: false},
    {value: "TAILÂNDIA", label: "TAILÂNDIA", main: false},
    {value: "TAJIQUISTÃO", label: "TAJIQUISTÃO", main: false},
    {value: "TANZÂNIA", label: "TANZÂNIA", main: false},
    {value: "TIMOR LESTE", label: "TIMOR LESTE", main: false},
    {value: "TOGO", label: "TOGO", main: false},
    {value: "TONGA", label: "TONGA", main: false},
    {value: "TRINIDAD E TOBAGO", label: "TRINIDAD E TOBAGO", main: false},
    {value: "TUNÍSIA", label: "TUNÍSIA", main: false},
    {value: "TURCOMENISTÃO", label: "TURCOMENISTÃO", main: false},
    {value: "TURQUIA", label: "TURQUIA", main: false},
    {value: "TUVALU", label: "TUVALU", main: false},
    {value: "UCRÂNIA", label: "UCRÂNIA", main: false},
    {value: "UGANDA", label: "UGANDA", main: false},
    {value: "URUGUAI", label: "URUGUAI", main: false},
    {value: "USBEQUISTÃO", label: "USBEQUISTÃO", main: false},
    {value: "VANUATU", label: "VANUATU", main: false},
    {value: "VENEZUELA", label: "VENEZUELA", main: false},
    {value: "VIETNÃ", label: "VIETNÃ", main: false},
    {value: "ZÂMBIA", label: "ZÂMBIA", main: false},
    {value: "ZIMBÁBUE", label: "ZIMBÁBUE", main: false},
]
