export const masculin_country_of_birth = [
    {value: 'AFEGÃO', label: 'AFEGANISTÃO | AFEGÃO', main: false},
    {value: 'SUL-AFRICANO', label: 'ÁFRICA DO SUL | SUL-AFRICANO', main: false},
    {value: 'ALBANÊS', label: 'ALBÂNIA | ALBANÊS', main: false},
    {value: 'ALEMÃO', label: 'ALEMANHA | ALEMÃO', main: true},
    {value: 'ANDORRANO', label: 'ANDORRA | ANDORRANO', main: false},
    {value: 'ANGOLANO', label: 'ANGOLA | ANGOLANO', main: false},
    {value: 'ANTIGUANO', label: 'ANTÍGUA E BARBUDA | ANTIGUANO', main: false},
    {value: 'SAUDITO', label: 'ARÁBIA SAUDITA | SAUDITO', main: false},
    {value: 'ARGELINO', label: 'ARGÉLIA | ARGELINO', main: false},
    {value: 'ARGENTINO', label: 'ARGENTINA | ARGENTINO', main: true},
    {value: 'ARMÊNIO', label: 'ARMÊNIA | ARMÊNIO', main: false},
    {value: 'AUSTRALIANO', label: 'AUSTRÁLIA | AUSTRALIANO', main: false},
    {value: 'AUSTRÍACO', label: 'ÁUSTRIA | AUSTRÍACO', main: false},
    {value: 'AZERBAIJANO', label: 'AZERBAIDJÃO | AZERBAIJANO', main: false},
    {value: 'BAHAMENSE', label: 'BAHAMAS | BAHAMENSE', main: false},
    {value: 'BENGALÊS', label: 'BANGLADESH | BENGALÊS', main: false},
    {value: 'BARBADIANO', label: 'BARBADOS | BARBADIANO', main: false},
    {value: 'BIELO-RUSSO', label: 'BELARUS | BIELO-RUSSO', main: false},
    {value: 'BELGA', label: 'BÉLGICA | BELGA', main: false},
    {value: 'BELIZENHO', label: 'BELIZE | BELIZENHO', main: false},
    {value: 'BENINENSE', label: 'BENIN | BENINENSE', main: false},
    {value: 'BOLIVIANO', label: 'BOLÍVIA | BOLIVIANO', main: false},
    {value: 'BÓSNIO', label: 'BÓSNIA-HERZEGÓVINA | BÓSNIO', main: false},
    {value: 'BECHUANO', label: 'BOTSUANA | BECHUANO', main: false},
    {value: 'BRASILEIRO', label: 'BRASIL | BRASILEIRO', main: true},
    {value: 'BRUNEANO', label: 'BRUNEI | BRUNEANO', main: false},
    {value: 'BÚLGARO', label: 'BULGÁRIA | BÚLGARO', main: false},
    {value: 'BURQUINENSE', label: 'BURKINA FASO | BURQUINENSE', main: false},
    {value: 'BURUNDINÊS', label: 'BURUNDI | BURUNDINÊS', main: false},
    {value: 'BUTANÊS', label: 'BUTÃO | BUTANÊS', main: false},
    {value: 'CABOVERDIANO', label: 'CABO VERDE | CABOVERDIANO', main: false},
    {value: 'CAMARONÊS', label: 'CAMARÕES | CAMARONÊS', main: false},
    {value: 'CAMBOJANO', label: 'CAMBOJA | CAMBOJANO', main: false},
    {value: 'CATARIANO', label: 'CATAR | CATARIANO', main: false},
    {value: 'CAZAQUE', label: 'CAZAQUISTÃO | CAZAQUE', main: false},
    {value: 'CHADIANO', label: 'CHADE | CHADIANO', main: false},
    {value: 'CHILENO', label: 'CHILE | CHILENO', main: true},
    {value: 'CHINÊS', label: 'CHINA | CHINÊS', main: true},
    {value: 'CIPRIOTA', label: 'CHIPRE | CIPRIOTA', main: false},
    {value: 'CINGAPURIANO', label: 'CINGAPURA | CINGAPURIANO', main: false},
    {value: 'COLOMBIANO', label: 'COLÔMBIA | COLOMBIANO', main: true},
    {value: 'COMORENSE', label: 'COMORES | COMORENSE', main: false},
    {value: 'CONGOLÊS', label: 'CONGO | CONGOLÊS', main: false},
    {value: 'NORTE-COREANO', label: 'CORÉIA DO NORTE | NORTE-COREANO', main: false},
    {value: 'SUL-COREANO', label: 'CORÉIA DO SUL | SUL-COREANO', main: false},
    {value: 'MARFINENSE', label: 'COSTA DO MARFIM | MARFINENSE', main: false},
    {value: 'COSTARRIQUENHO', label: 'COSTA RICA | COSTARRIQUENHO', main: false},
    {value: 'CROATA', label: 'CROÁCIA | CROATA', main: false},
    {value: 'CUBANO', label: 'CUBA | CUBANO', main: true},
    {value: 'DINAMARQUÊS', label: 'DINAMARCA | DINAMARQUÊS', main: false},
    {value: 'DJIBUTIANO', label: 'DJIBUTI | DJIBUTIANO', main: false},
    {value: 'DOMINICANO', label: 'DOMINICA | DOMINICANO', main: false},
    {value: 'EGÍPCIO', label: 'EGITO | EGÍPCIO', main: false},
    {value: 'SALVADORENHO', label: 'EL SALVADOR | SALVADORENHO', main: false},
    {value: 'EMIRENSE', label: 'EMIRADOS ÁRABES UNIDOS | EMIRENSE', main: false},
    {value: 'EQUATORIANO', label: 'EQUADOR | EQUATORIANO', main: false},
    {value: 'ERITREU', label: 'ERITREIA | ERITREU', main: false},
    {value: 'ESLOVACO', label: 'ESLOVÁQUIA | ESLOVACO', main: false},
    {value: 'ESLOVENO', label: 'ESLOVÊNIA | ESLOVENO', main: false},
    {value: 'ESPANHOL', label: 'ESPANHA | ESPANHOL', main: true},
    {value: 'AMERICANO', label: 'ESTADOS UNIDOS | AMERICANO', main: false},
    {value: 'ESTONIANO', label: 'ESTÔNIA | ESTONIANO', main: false},
    {value: 'ETÍOPE', label: 'ETIÓPIA | ETÍOPE', main: false},
    {value: 'RUSSO', label: 'FEDERAÇÃO RUSSA | RUSSO', main: false},
    {value: 'FIJIANO', label: 'FIJI | FIJIANO', main: false},
    {value: 'FILIPINO', label: 'FILIPINAS | FILIPINO', main: false},
    {value: 'FINLANDÊS', label: 'FINLÂNDIA | FINLANDÊS', main: false},
    {value: 'FRANCÊS', label: 'FRANÇA | FRANCÊS', main: false},
    {value: 'GABONÊS', label: 'GABÃO | GABONÊS', main: false},
    {value: 'GAMBIANO', label: 'GÂMBIA | GAMBIANO', main: false},
    {value: 'GANÊS', label: 'GANA | GANÊS', main: false},
    {value: 'GEORGIANO', label: 'GEÓRGIA | GEORGIANO', main: false},
    {value: 'GRANADINO', label: 'GRANADA | GRANADINO', main: false},
    {value: 'GREGO', label: 'GRÉCIA | GREGO', main: false},
    {value: 'GUATEMALTECO', label: 'GUATEMALA | GUATEMALTECO', main: false},
    {value: 'GUIANÊS', label: 'GUIANA | GUIANÊS', main: false},
    {value: 'GUINEENSE', label: 'GUINÉ-BISSAU | GUINEENSE', main: false},
    {value: 'GUINÉU-EQUATORIANO', label: 'GUINÉ-EQUATORIAL | GUINÉU-EQUATORIANO', main: false},
    {value: 'HAITIANO', label: 'HAITI | HAITIANO', main: false},
    {value: 'HOLANDÊS', label: 'HOLANDA | HOLANDÊS', main: false},
    {value: 'HONDURENHO', label: 'HONDURAS | HONDURENHO', main: false},
    {value: 'HÚNGARO', label: 'HUNGRIA | HÚNGARO', main: false},
    {value: 'IEMENITA', label: 'IÉMEN | IEMENITA', main: false},
    {value: 'MARSHALINO', label: 'ILHAS MARSHALL | MARSHALINO', main: false},
    {value: 'SALOMÔNICO', label: 'ILHAS SALOMÃO | SALOMÔNICO', main: false},
    {value: 'INDIANO', label: 'ÍNDIA | INDIANO', main: false},
    {value: 'INDONÉSIO', label: 'INDONÉSIA | INDONÉSIO', main: false},
    {value: 'IRANIANO', label: 'IRÃ | IRANIANO', main: false},
    {value: 'IRAQUIANO', label: 'IRAQUE | IRAQUIANO', main: false},
    {value: 'IRLANDÊS', label: 'IRLANDA | IRLANDÊS', main: false},
    {value: 'ISLANDÊS', label: 'ISLÂNDIA | ISLANDÊS', main: false},
    {value: 'ISRAELENSE', label: 'ISRAEL | ISRAELENSE', main: false},
    {value: 'ITALIANO', label: 'ITÁLIA | ITALIANO', main: false},
    {value: 'JAMAICANO', label: 'JAMAICA | JAMAICANO', main: false},
    {value: 'JAPONÊS', label: 'JAPÃO | JAPONÊS', main: false},
    {value: 'JORDANIANO', label: 'JORDÂNIA | JORDANIANO', main: false},
    {value: 'KIRIBATIANO', label: 'KIRIBATI | KIRIBATIANO', main: false},
    {value: 'KUWAITIANO', label: 'KUWAIT | KUWAITIANO', main: false},
    {value: 'LAOSIANO', label: 'LAOS | LAOSIANO', main: false},
    {value: 'LESOTO', label: 'LESOTO | LESOTO', main: false},
    {value: 'LETÃO', label: 'LETÔNIA | LETÃO', main: false},
    {value: 'LIBANÊS', label: 'LÍBANO | LIBANÊS', main: false},
    {value: 'LIBERIANO', label: 'LIBÉRIA | LIBERIANO', main: false},
    {value: 'LÍBIO', label: 'LÍBIA | LÍBIO', main: false},
    {value: 'LIECHTENSTEINIENSE', label: 'LIECHTENSTEIN | LIECHTENSTEINIENSE', main: false},
    {value: 'LITUANO', label: 'LITUÂNIA | LITUANO', main: false},
    {value: 'LUXEMBURGUÊS', label: 'LUXEMBURGO | LUXEMBURGUÊS', main: false},
    {value: 'MACEDÔNIO', label: 'MACEDÔNIA | MACEDÔNIO', main: false},
    {value: 'MALGACHE', label: 'MADAGASCAR | MALGACHE', main: false},
    {value: 'MALAIO', label: 'MALÁSIA | MALAIO', main: false},
    {value: 'MALAUIANO', label: 'MALAUÍ | MALAUIANO', main: false},
    {value: 'MALDIVO', label: 'MALDIVAS | MALDIVO', main: false},
    {value: 'MALINÊS', label: 'MALI | MALINÊS', main: false},
    {value: 'MALTÊS', label: 'MALTA | MALTÊS', main: false},
    {value: 'MARROQUINO', label: 'MARROCOS | MARROQUINO', main: false},
    {value: 'MAURICIANO', label: 'MAURÍCIO | MAURICIANO', main: false},
    {value: 'MAURITANO', label: 'MAURITÂNIA | MAURITANO', main: false},
    {value: 'MEXICANO', label: 'MÉXICO | MEXICANO', main: false},
    {value: 'BIRMANÊS', label: 'MIANMAR | BIRMANÊS', main: false},
    {value: 'MICRONÉSIO', label: 'MICRONÉSIA | MICRONÉSIO', main: false},
    {value: 'MOÇAMBICANO', label: 'MOÇAMBIQUE | MOÇAMBICANO', main: false},
    {value: 'MOLDÁVIO', label: 'MOLDÁVIA | MOLDÁVIO', main: false},
    {value: 'MONEGASCO', label: 'MÔNACO | MONEGASCO', main: false},
    {value: 'MONGOL', label: 'MONGÓLIA | MONGOL', main: false},
    {value: 'MONTENEGRINO', label: 'MONTENEGRO | MONTENEGRINO', main: false},
    {value: 'NAMIBIANO', label: 'NAMÍBIA | NAMIBIANO', main: false},
    {value: 'NAURUANO', label: 'NAURU | NAURUANO', main: false},
    {value: 'NEPALÊS', label: 'NEPAL | NEPALÊS', main: false},
    {value: 'NICARAGUENSE', label: 'NICARÁGUA | NICARAGUENSE', main: false},
    {value: 'NIGERINO', label: 'NÍGER | NIGERINO', main: false},
    {value: 'NIGERIANO', label: 'NIGÉRIA | NIGERIANO', main: false},
    {value: 'NORUEGUÊS', label: 'NORUEGA | NORUEGUÊS', main: false},
    {value: 'NEOZELANDÊS', label: 'NOVA ZELÂNDIA | NEOZELANDÊS', main: false},
    {value: 'CANADENSE', label: 'O CANADÁ | CANADENSE', main: false},
    {value: 'OMANI', label: 'OMÃ | OMANI', main: false},
    {value: 'PALAUENSE', label: 'PALAU | PALAUENSE', main: false},
    {value: 'PANAMENHO', label: 'PANAMÁ | PANAMENHO', main: false},
    {value: 'PAPUÁSIO', label: 'PAPUA NOVA GUINÉ | PAPUÁSIO', main: false},
    {value: 'PAQUISTANÊS', label: 'PAQUISTÃO | PAQUISTANÊS', main: false},
    {value: 'PARAGUAIO', label: 'PARAGUAI | PARAGUAIO', main: false},
    {value: 'PERUANO', label: 'PERU | PERUANO', main: false},
    {value: 'POLONÊS', label: 'POLÔNIA | POLONÊS', main: false},
    {value: 'PORTUGUÊS', label: 'PORTUGAL | PORTUGUÊS', main: false},
    {value: 'QUENIANO', label: 'QUÊNIA | QUENIANO', main: false},
    {value: 'INGLÊS', label: 'REINO UNIDO | INGLÊS', main: false},
    {value: 'CENTRO-AFRICANO', label: 'REPÚBLICA CENTRO-AFRICANA | CENTRO-AFRICANO', main: false},
    {value: 'DOMINICANO', label: 'REPÚBLICA DOMINICANA | DOMINICANO', main: false},
    {value: 'TCHECO', label: 'REPÚBLICA TCHECA | TCHECO', main: false},
    {value: 'ROMENO', label: 'ROMÊNIA | ROMENO', main: false},
    {value: 'RUANDÊS', label: 'RUANDA | RUANDÊS', main: false},
    {value: 'SAMOANO', label: 'SAMOA | SAMOANO', main: false},
    {value: 'SAMARINÊS', label: 'SAN MARINO | SAMARINÊS', main: false},
    {value: 'SANTA-LUCENSE', label: 'SANTA LÚCIA | SANTA-LUCENSE', main: false},
    {value: 'SÃO-CRISTOVENSE', label: 'SÃO CRISTÓVÃO E NÉVIS | SÃO-CRISTOVENSE', main: false},
    {value: 'SANTOMENSE', label: 'SÃO TOMÉ E PRÍNCIPE | SANTOMENSE', main: false},
    {value: 'SÃO-VICENTINO', label: 'SÃO VICENTE E GRANADINAS | SÃO-VICENTINO', main: false},
    {value: 'SEICHELENSE', label: 'SEICHELES | SEICHELENSE', main: false},
    {value: 'SENEGALÊS', label: 'SENEGAL | SENEGALÊS', main: false},
    {value: 'LEONÊS', label: 'SERRA LEOA | LEONÊS', main: false},
    {value: 'SÉRVIO', label: 'SÉRVIA | SÉRVIO', main: false},
    {value: 'SÍRIO', label: 'SÍRIA | SÍRIO', main: false},
    {value: 'SOMALI', label: 'SOMÁLIA | SOMALI', main: false},
    {value: 'CINGALÊS', label: 'SRI LANKA | CINGALÊS', main: false},
    {value: 'SUAZI', label: 'SUAZILÂNDIA | SUAZI', main: false},
    {value: 'SUDANÊS', label: 'SUDÃO | SUDANÊS', main: false},
    {value: 'SUÉCO', label: 'SUÉCIA | SUÉCO', main: false},
    {value: 'SUÍÇO', label: 'SUÍÇA | SUÍÇO', main: false},
    {value: 'SURINAMÊS', label: 'SURINAME | SURINAMÊS', main: false},
    {value: 'TAILANDÊS', label: 'TAILÂNDIA | TAILANDÊS', main: false},
    {value: 'TAJIQUE', label: 'TAJIQUISTÃO | TAJIQUE', main: false},
    {value: 'TANZANIANO', label: 'TANZÂNIA | TANZANIANO', main: false},
    {value: 'TIMORENSE', label: 'TIMOR LESTE | TIMORENSE', main: false},
    {value: 'TOGONÊS', label: 'TOGO | TOGONÊS', main: false},
    {value: 'TONGALÊS', label: 'TONGA | TONGALÊS', main: false},
    {value: 'TRINITINO', label: 'TRINIDAD E TOBAGO | TRINITINO', main: false},
    {value: 'TUNISIANO', label: 'TUNÍSIA | TUNISIANO', main: false},
    {value: 'TURCOMANO', label: 'TURCOMENISTÃO | TURCOMANO', main: false},
    {value: 'TURCO', label: 'TURQUIA | TURCO', main: false},
    {value: 'TUVALUANO', label: 'TUVALU | TUVALUANO', main: false},
    {value: 'UCRANIANO', label: 'UCRÂNIA | UCRANIANO', main: false},
    {value: 'UGANDENSE', label: 'UGANDA | UGANDENSE', main: false},
    {value: 'URUGUAIO', label: 'URUGUAI | URUGUAIO', main: false},
    {value: 'UZBEQUE', label: 'USBEQUISTÃO | UZBEQUE', main: false},
    {value: 'VANUATENSE', label: 'VANUATU | VANUATENSE', main: false},
    {value: 'VENEZUELANO', label: 'VENEZUELA | VENEZUELANO', main: false},
    {value: 'VIETNAMITA', label: 'VIETNÃ | VIETNAMITA', main: false},
    {value: 'ZAMBIANO', label: 'ZÂMBIA | ZAMBIANO', main: false},
    {value: 'ZIMBABUANO', label: 'ZIMBÁBUE | ZIMBABUANO', main: false},
];

export const feminin_country_of_birth = [
    {value: 'AFEGÃ', label: 'AFEGANISTÃO | AFEGÃ', main: false},
    {value: 'SUL-AFRICANA', label: 'ÁFRICA DO SUL | SUL-AFRICANA', main: false},
    {value: 'ALBANESA', label: 'ALBÂNIA | ALBANESA', main: false},
    {value: 'ALEMÃ', label: 'ALEMANHA | ALEMÃ', main: true},
    {value: 'ANDORRANA', label: 'ANDORRA | ANDORRANA', main: false},
    {value: 'ANGOLANA', label: 'ANGOLA | ANGOLANA', main: false},
    {value: 'ANTIGUANA', label: 'ANTÍGUA E BARBUDA | ANTIGUANA', main: false},
    {value: 'SAUDITA', label: 'ARÁBIA SAUDITA | SAUDITA', main: false},
    {value: 'ARGELINA', label: 'ARGÉLIA | ARGELINA', main: false},
    {value: 'ARGENTINO', label: 'ARGENTINA | ARGENTINO', main: true},
    {value: 'ARMÊNIA', label: 'ARMÊNIA | ARMÊNIA', main: false},
    {value: 'AUSTRALIANA', label: 'AUSTRÁLIA | AUSTRALIANA', main: false},
    {value: 'AUSTRÍACA', label: 'ÁUSTRIA | AUSTRÍACA', main: false},
    {value: 'AZERBAIJANA', label: 'AZERBAIDJÃO | AZERBAIJANA', main: false},
    {value: 'BAHAMENSE', label: 'BAHAMAS | BAHAMENSE', main: false},
    {value: 'BENGALESA', label: 'BANGLADESH | BENGALESA', main: false},
    {value: 'BARBADIANA', label: 'BARBADOS | BARBADIANA', main: false},
    {value: 'BIELO-RUSSA', label: 'BELARUS | BIELO-RUSSA', main: false},
    {value: 'BELGA', label: 'BÉLGICA | BELGA', main: false},
    {value: 'BELIZENHA', label: 'BELIZE | BELIZENHA', main: false},
    {value: 'BENINENSE', label: 'BENIN | BENINENSE', main: false},
    {value: 'BOLIVIANA', label: 'BOLÍVIA | BOLIVIANA', main: false},
    {value: 'BÓSNIA', label: 'BÓSNIA-HERZEGÓVINA | BÓSNIA', main: false},
    {value: 'BECHUANA', label: 'BOTSUANA | BECHUANA', main: false},
    {value: 'BRASILEIRA', label: 'BRASIL | BRASILEIRA', main: true},
    {value: 'BRUNEANA', label: 'BRUNEI | BRUNEANA', main: false},
    {value: 'BÚLGARA', label: 'BULGÁRIA | BÚLGARA', main: false},
    {value: 'BURQUINENSE', label: 'BURKINA FASO | BURQUINENSE', main: false},
    {value: 'BURUNDINESA', label: 'BURUNDI | BURUNDINESA', main: false},
    {value: 'BUTANESA', label: 'BUTÃO | BUTANESA', main: false},
    {value: 'CABOVERDIANA', label: 'CABO VERDE | CABOVERDIANA', main: false},
    {value: 'CAMARONESA', label: 'CAMARÕES | CAMARONESA', main: false},
    {value: 'CAMBOJANA', label: 'CAMBOJA | CAMBOJANA', main: false},
    {value: 'CATARIANA', label: 'CATAR | CATARIANA', main: false},
    {value: 'CAZAQUE', label: 'CAZAQUISTÃO | CAZAQUE', main: false},
    {value: 'CHADIANA', label: 'CHADE | CHADIANA', main: false},
    {value: 'CHILENA', label: 'CHILE | CHILENA', main: true},
    {value: 'CHINESA', label: 'CHINA | CHINESA', main: true},
    {value: 'CIPRIOTA', label: 'CHIPRE | CIPRIOTA', main: false},
    {value: 'CINGAPURIANA', label: 'CINGAPURA | CINGAPURIANA', main: false},
    {value: 'COLOMBIANA', label: 'COLÔMBIA | COLOMBIANA', main: true},
    {value: 'COMORENSE', label: 'COMORES | COMORENSE', main: false},
    {value: 'CONGOLESA', label: 'CONGO | CONGOLESA', main: false},
    {value: 'NORTE-COREANA', label: 'CORÉIA DO NORTE | NORTE-COREANA', main: false},
    {value: 'SUL-COREANA', label: 'CORÉIA DO SUL | SUL-COREANA', main: false},
    {value: 'MARFINENSE', label: 'COSTA DO MARFIM | MARFINENSE', main: false},
    {value: 'COSTARRIQUENHA', label: 'COSTA RICA | COSTARRIQUENHA', main: false},
    {value: 'CROATA', label: 'CROÁCIA | CROATA', main: false},
    {value: 'CUBANA', label: 'CUBA | CUBANA', main: true},
    {value: 'DINAMARQUESA', label: 'DINAMARCA | DINAMARQUESA', main: false},
    {value: 'DJIBUTIANA', label: 'DJIBUTI | DJIBUTIANA', main: false},
    {value: 'DOMINICANA', label: 'DOMINICA | DOMINICANA', main: false},
    {value: 'EGÍPCIA', label: 'EGITO | EGÍPCIA', main: false},
    {value: 'SALVADORENHA', label: 'EL SALVADOR | SALVADORENHA', main: false},
    {value: 'EMIRENSE', label: 'EMIRADOS ÁRABES UNIDOS | EMIRENSE', main: false},
    {value: 'EQUATORIANA', label: 'EQUADOR | EQUATORIANA', main: false},
    {value: 'ERITREIA', label: 'ERITREIA | ERITREIA', main: false},
    {value: 'ESLOVACA', label: 'ESLOVÁQUIA | ESLOVACA', main: false},
    {value: 'ESLOVENA', label: 'ESLOVÊNIA | ESLOVENA', main: false},
    {value: 'ESPANHOLA', label: 'ESPANHA | ESPANHOLA', main: true},
    {value: 'AMERICANA', label: 'ESTADOS UNIDOS | AMERICANA', main: false},
    {value: 'ESTONIANA', label: 'ESTÔNIA | ESTONIANA', main: false},
    {value: 'ETÍOPE', label: 'ETIÓPIA | ETÍOPE', main: false},
    {value: 'RUSSA', label: 'FEDERAÇÃO RUSSA | RUSSA', main: false},
    {value: 'FIJIANA', label: 'FIJI | FIJIANA', main: false},
    {value: 'FILIPINA', label: 'FILIPINAS | FILIPINA', main: false},
    {value: 'FINLANDESA', label: 'FINLÂNDIA | FINLANDESA', main: false},
    {value: 'FRANCESA', label: 'FRANÇA | FRANCESA', main: false},
    {value: 'GABONESA', label: 'GABÃO | GABONESA', main: false},
    {value: 'GAMBIANA', label: 'GÂMBIA | GAMBIANA', main: false},
    {value: 'GANESA', label: 'GANA | GANESA', main: false},
    {value: 'GEORGIANA', label: 'GEÓRGIA | GEORGIANA', main: false},
    {value: 'GRANADINA', label: 'GRANADA | GRANADINA', main: false},
    {value: 'GREGA', label: 'GRÉCIA | GREGA', main: false},
    {value: 'GUATEMALTECA', label: 'GUATEMALA | GUATEMALTECA', main: false},
    {value: 'GUIANESA', label: 'GUIANA | GUIANESA', main: false},
    {value: 'GUINEENSE', label: 'GUINÉ-BISSAU | GUINEENSE', main: false},
    {value: 'GUINÉU-EQUATORIANA', label: 'GUINÉ-EQUATORIAL | GUINÉU-EQUATORIANA', main: false},
    {value: 'HAITIANA', label: 'HAITI | HAITIANA', main: false},
    {value: 'HOLANDESA', label: 'HOLANDA | HOLANDESA', main: false},
    {value: 'HONDURENHA', label: 'HONDURAS | HONDURENHA', main: false},
    {value: 'HÚNGARA', label: 'HUNGRIA | HÚNGARA', main: false},
    {value: 'IEMENITA', label: 'IÉMEN | IEMENITA', main: false},
    {value: 'MARSHALINA', label: 'ILHAS MARSHALL | MARSHALINA', main: false},
    {value: 'SALOMÔNICA', label: 'ILHAS SALOMÃO | SALOMÔNICA', main: false},
    {value: 'INDIANA', label: 'ÍNDIA | INDIANA', main: false},
    {value: 'INDONÉSIA', label: 'INDONÉSIA | INDONÉSIA', main: false},
    {value: 'IRANIANA', label: 'IRÃ | IRANIANA', main: false},
    {value: 'IRAQUIANA', label: 'IRAQUE | IRAQUIANA', main: false},
    {value: 'IRLANDESA', label: 'IRLANDA | IRLANDESA', main: false},
    {value: 'ISLANDESA', label: 'ISLÂNDIA | ISLANDESA', main: false},
    {value: 'ISRAELENSE', label: 'ISRAEL | ISRAELENSE', main: false},
    {value: 'ITALIANA', label: 'ITÁLIA | ITALIANA', main: false},
    {value: 'JAMAICANA', label: 'JAMAICA | JAMAICANA', main: false},
    {value: 'JAPONESA', label: 'JAPÃO | JAPONESA', main: false},
    {value: 'JORDANIANA', label: 'JORDÂNIA | JORDANIANA', main: false},
    {value: 'KIRIBATIANA', label: 'KIRIBATI | KIRIBATIANA', main: false},
    {value: 'KUWAITIANA', label: 'KUWAIT | KUWAITIANA', main: false},
    {value: 'LAOSIANA', label: 'LAOS | LAOSIANA', main: false},
    {value: 'LESOTA', label: 'LESOTO | LESOTA', main: false},
    {value: 'LETÃ', label: 'LETÔNIA | LETÃ', main: false},
    {value: 'LIBANESA', label: 'LÍBANO | LIBANESA', main: false},
    {value: 'LIBERIANA', label: 'LIBÉRIA | LIBERIANA', main: false},
    {value: 'LÍBIA', label: 'LÍBIA | LÍBIA', main: false},
    {value: 'LIECHTENSTEINIENSE', label: 'LIECHTENSTEIN | LIECHTENSTEINIENSE', main: false},
    {value: 'LITUANA', label: 'LITUÂNIA | LITUANA', main: false},
    {value: 'LUXEMBURGUESA', label: 'LUXEMBURGO | LUXEMBURGUESA', main: false},
    {value: 'MACEDÔNIA', label: 'MACEDÔNIA | MACEDÔNIA', main: false},
    {value: 'MALGACHE', label: 'MADAGASCAR | MALGACHE', main: false},
    {value: 'MALAIA', label: 'MALÁSIA | MALAIA', main: false},
    {value: 'MALAUIANA', label: 'MALAUÍ | MALAUIANA', main: false},
    {value: 'MALDIVA', label: 'MALDIVAS | MALDIVA', main: false},
    {value: 'MALINESA', label: 'MALI | MALINESA', main: false},
    {value: 'MALTESA', label: 'MALTA | MALTESA', main: false},
    {value: 'MARROQUINA', label: 'MARROCOS | MARROQUINA', main: false},
    {value: 'MAURICIANA', label: 'MAURÍCIO | MAURICIANA', main: false},
    {value: 'MAURITANA', label: 'MAURITÂNIA | MAURITANA', main: false},
    {value: 'MEXICANA', label: 'MÉXICO | MEXICANA', main: false},
    {value: 'BIRMANESA', label: 'MIANMAR | BIRMANESA', main: false},
    {value: 'MICRONÉSIA', label: 'MICRONÉSIA | MICRONÉSIA', main: false},
    {value: 'MOÇAMBICANA', label: 'MOÇAMBIQUE | MOÇAMBICANA', main: false},
    {value: 'MOLDÁVIA', label: 'MOLDÁVIA | MOLDÁVIA', main: false},
    {value: 'MONEGASCA', label: 'MÔNACO | MONEGASCA', main: false},
    {value: 'MONGOL', label: 'MONGÓLIA | MONGOL', main: false},
    {value: 'MONTENEGRINA', label: 'MONTENEGRO | MONTENEGRINA', main: false},
    {value: 'NAMIBIANA', label: 'NAMÍBIA | NAMIBIANA', main: false},
    {value: 'NAURUANA', label: 'NAURU | NAURUANA', main: false},
    {value: 'NEPALESA', label: 'NEPAL | NEPALESA', main: false},
    {value: 'NICARAGUENSE', label: 'NICARÁGUA | NICARAGUENSE', main: false},
    {value: 'NIGERINA', label: 'NÍGER | NIGERINA', main: false},
    {value: 'NIGERIANA', label: 'NIGÉRIA | NIGERIANA', main: false},
    {value: 'NORUEGUESA', label: 'NORUEGA | NORUEGUESA', main: false},
    {value: 'NEOZELANDESA', label: 'NOVA ZELÂNDIA | NEOZELANDESA', main: false},
    {value: 'CANADENSE', label: 'O CANADÁ | CANADENSE', main: false},
    {value: 'OMANI', label: 'OMÃ | OMANI', main: false},
    {value: 'PALAUENSE', label: 'PALAU | PALAUENSE', main: false},
    {value: 'PANAMENHA', label: 'PANAMÁ | PANAMENHA', main: false},
    {value: 'PAPUÁSIA', label: 'PAPUA NOVA GUINÉ | PAPUÁSIA', main: false},
    {value: 'PAQUISTANESA', label: 'PAQUISTÃO | PAQUISTANESA', main: false},
    {value: 'PARAGUAIA', label: 'PARAGUAI | PARAGUAIA', main: false},
    {value: 'PERUANA', label: 'PERU | PERUANA', main: false},
    {value: 'POLONESA', label: 'POLÔNIA | POLONESA', main: false},
    {value: 'PORTUGUESA', label: 'PORTUGAL | PORTUGUESA', main: false},
    {value: 'QUENIANA', label: 'QUÊNIA | QUENIANA', main: false},
    {value: 'INGLESA', label: 'REINO UNIDO | INGLESA', main: false},
    {value: 'CENTRO-AFRICANA', label: 'REPÚBLICA CENTRO-AFRICANA | CENTRO-AFRICANA', main: false},
    {value: 'DOMINICANA', label: 'REPÚBLICA DOMINICANA | DOMINICANA', main: false},
    {value: 'TCHECA', label: 'REPÚBLICA TCHECA | TCHECA', main: false},
    {value: 'ROMENA', label: 'ROMÊNIA | ROMENA', main: false},
    {value: 'RUANDESA', label: 'RUANDA | RUANDESA', main: false},
    {value: 'SAMOANA', label: 'SAMOA | SAMOANA', main: false},
    {value: 'SAMARINESA', label: 'SAN MARINO | SAMARINESA', main: false},
    {value: 'SANTA-LUCENSE', label: 'SANTA LÚCIA | SANTA-LUCENSE', main: false},
    {value: 'SÃO-CRISTOVENSE', label: 'SÃO CRISTÓVÃO E NÉVIS | SÃO-CRISTOVENSE', main: false},
    {value: 'SANTOMENSE', label: 'SÃO TOMÉ E PRÍNCIPE | SANTOMENSE', main: false},
    {value: 'SÃO-VICENTINA', label: 'SÃO VICENTE E GRANADINAS | SÃO-VICENTINA', main: false},
    {value: 'SEICHELENSE', label: 'SEICHELES | SEICHELENSE', main: false},
    {value: 'SENEGALESA', label: 'SENEGAL | SENEGALESA', main: false},
    {value: 'LEONESA', label: 'SERRA LEOA | LEONESA', main: false},
    {value: 'SÉRVIA', label: 'SÉRVIA | SÉRVIA', main: false},
    {value: 'SÍRIA', label: 'SÍRIA | SÍRIA', main: false},
    {value: 'SOMALI', label: 'SOMÁLIA | SOMALI', main: false},
    {value: 'CINGALESA', label: 'SRI LANKA | CINGALESA', main: false},
    {value: 'SUAZI', label: 'SUAZILÂNDIA | SUAZI', main: false},
    {value: 'SUDANESA', label: 'SUDÃO | SUDANESA', main: false},
    {value: 'SUÉCA', label: 'SUÉCIA | SUÉCA', main: false},
    {value: 'SUÍÇA', label: 'SUÍÇA | SUÍÇA', main: false},
    {value: 'SURINAMESA', label: 'SURINAME | SURINAMESA', main: false},
    {value: 'TAILANDESA', label: 'TAILÂNDIA | TAILANDESA', main: false},
    {value: 'TAJIQUE', label: 'TAJIQUISTÃO | TAJIQUE', main: false},
    {value: 'TANZANIANA', label: 'TANZÂNIA | TANZANIANA', main: false},
    {value: 'TIMORENSE', label: 'TIMOR LESTE | TIMORENSE', main: false},
    {value: 'TOGONESA', label: 'TOGO | TOGONESA', main: false},
    {value: 'TONGALESA', label: 'TONGA | TONGALESA', main: false},
    {value: 'TRINITINA', label: 'TRINIDAD E TOBAGO | TRINITINA', main: false},
    {value: 'TUNISIANA', label: 'TUNÍSIA | TUNISIANA', main: false},
    {value: 'TURCOMANA', label: 'TURCOMENISTÃO | TURCOMANA', main: false},
    {value: 'TURCA', label: 'TURQUIA | TURCA', main: false},
    {value: 'TUVALUANA', label: 'TUVALU | TUVALUANA', main: false},
    {value: 'UCRANIANA', label: 'UCRÂNIA | UCRANIANA', main: false},
    {value: 'UGANDENSE', label: 'UGANDA | UGANDENSE', main: false},
    {value: 'URUGUAIA', label: 'URUGUAI | URUGUAIA', main: false},
    {value: 'UZBEQUE', label: 'USBEQUISTÃO | UZBEQUE', main: false},
    {value: 'VANUATENSE', label: 'VANUATU | VANUATENSE', main: false},
    {value: 'VENEZUELANA', label: 'VENEZUELA | VENEZUELANA', main: false},
    {value: 'VIETNAMITA', label: 'VIETNÃ | VIETNAMITA', main: false},
    {value: 'ZAMBIANA', label: 'ZÂMBIA | ZAMBIANA', main: false},
    {value: 'ZIMBABUANA', label: 'ZIMBÁBUE | ZIMBABUANA', main: false},
]