export const ddi = [
    {value: '+93', label: '+93 (Afghanistan)', main: 'false'},
    {value: '+355', label: '+355 (Albania)', main: 'false'},
    {value: '+213', label: '+213 (Algeria)', main: 'false'},
    {value: '+1-684', label: '+1-684 (American Samoa)', main: 'false'},
    {value: '+376', label: '+376 (Andorra)', main: 'false'},
    {value: '+244', label: '+244 (Angola)', main: 'false'},
    {value: '+1-264', label: '+1-264 (Anguilla)', main: 'false'},
    {value: '+672', label: '+672 (Antarctica)', main: 'false'},
    {value: '+1-268', label: '+1-268 (Antigua and Barbuda)', main: 'false'},
    {value: '+54', label: '+54 (Argentina)', main: 'false'},
    {value: '+374', label: '+374 (Armenia)', main: 'false'},
    {value: '+297', label: '+297 (Aruba)', main: 'false'},
    {value: '+61', label: '+61 (Australia)', main: 'false'},
    {value: '+43', label: '+43 (Austria)', main: 'false'},
    {value: '+994', label: '+994 (Azerbaijan)', main: 'false'},
    {value: '+1-242', label: '+1-242 (Bahamas)', main: 'false'},
    {value: '+973', label: '+973 (Bahrain)', main: 'false'},
    {value: '+880', label: '+880 (Bangladesh)', main: 'false'},
    {value: '+1-246', label: '+1-246 (Barbados)', main: 'false'},
    {value: '+375', label: '+375 (Belarus)', main: 'false'},
    {value: '+32', label: '+32 (Belgium)', main: 'false'},
    {value: '+501', label: '+501 (Belize)', main: 'false'},
    {value: '+229', label: '+229 (Benin)', main: 'false'},
    {value: '+1-441', label: '+1-441 (Bermuda)', main: 'false'},
    {value: '+975', label: '+975 (Bhutan)', main: 'false'},
    {value: '+591', label: '+591 (Bolivia)', main: 'false'},
    {value: '+387', label: '+387 (Bosnia and Herzegovina)', main: 'false'},
    {value: '+267', label: '+267 (Botswana)', main: 'false'},
    {value: '+55', label: '+55 (Brazil)', main: 'false'},
    {value: '+246', label: '+246 (British Indian Ocean Territory)', main: 'false'},
    {value: '+1-284', label: '+1-284 (British Virgin Islands)', main: 'false'},
    {value: '+673', label: '+673 (Brunei)', main: 'false'},
    {value: '+359', label: '+359 (Bulgaria)', main: 'false'},
    {value: '+226', label: '+226 (Burkina Faso)', main: 'false'},
    {value: '+257', label: '+257 (Burundi)', main: 'false'},
    {value: '+855', label: '+855 (Cambodia)', main: 'false'},
    {value: '+237', label: '+237 (Cameroon)', main: 'false'},
    {value: '+1', label: '+1 (Canada)', main: 'false'},
    {value: '+238', label: '+238 (Cape Verde)', main: 'false'},
    {value: '+1-345', label: '+1-345 (Cayman Islands)', main: 'false'},
    {value: '+236', label: '+236 (Central African Republic)', main: 'false'},
    {value: '+235', label: '+235 (Chad)', main: 'false'},
    {value: '+56', label: '+56 (Chile)', main: 'false'},
    {value: '+86', label: '+86 (China)', main: 'false'},
    {value: '+61', label: '+61 (Christmas Island)', main: 'false'},
    {value: '+61', label: '+61 (Cocos Islands)', main: 'false'},
    {value: '+57', label: '+57 (Colombia)', main: 'false'},
    {value: '+269', label: '+269 (Comoros)', main: 'false'},
    {value: '+682', label: '+682 (Cook Islands)', main: 'false'},
    {value: '+506', label: '+506 (Costa Rica)', main: 'false'},
    {value: '+385', label: '+385 (Croatia)', main: 'false'},
    {value: '+53', label: '+53 (Cuba)', main: 'false'},
    {value: '+599', label: '+599 (Curacao)', main: 'false'},
    {value: '+357', label: '+357 (Cyprus)', main: 'false'},
    {value: '+420', label: '+420 (Czech Republic)', main: 'false'},
    {value: '+243', label: '+243 (Democratic Republic of the Congo)', main: 'false'},
    {value: '+45', label: '+45 (Denmark)', main: 'false'},
    {value: '+253', label: '+253 (Djibouti)', main: 'false'},
    {value: '+1-767', label: '+1-767 (Dominica)', main: 'false'},
    {value: '+1-809, 1-829, 1-849', label: '+1-809, 1-829, 1-849 (Dominican Republic)', main: 'false'},
    {value: '+670', label: '+670 (East Timor)', main: 'false'},
    {value: '+593', label: '+593 (Ecuador)', main: 'false'},
    {value: '+20', label: '+20 (Egypt)', main: 'false'},
    {value: '+503', label: '+503 (El Salvador)', main: 'false'},
    {value: '+240', label: '+240 (Equatorial Guinea)', main: 'false'},
    {value: '+291', label: '+291 (Eritrea)', main: 'false'},
    {value: '+372', label: '+372 (Estonia)', main: 'false'},
    {value: '+251', label: '+251 (Ethiopia)', main: 'false'},
    {value: '+500', label: '+500 (Falkland Islands)', main: 'false'},
    {value: '+298', label: '+298 (Faroe Islands)', main: 'false'},
    {value: '+679', label: '+679 (Fiji)', main: 'false'},
    {value: '+358', label: '+358 (Finland)', main: 'false'},
    {value: '+33', label: '+33 (France)', main: 'false'},
    {value: '+689', label: '+689 (French Polynesia)', main: 'false'},
    {value: '+241', label: '+241 (Gabon)', main: 'false'},
    {value: '+220', label: '+220 (Gambia)', main: 'false'},
    {value: '+995', label: '+995 (Georgia)', main: 'false'},
    {value: '+49', label: '+49 (Germany)', main: 'false'},
    {value: '+233', label: '+233 (Ghana)', main: 'false'},
    {value: '+350', label: '+350 (Gibraltar)', main: 'false'},
    {value: '+30', label: '+30 (Greece)', main: 'false'},
    {value: '+299', label: '+299 (Greenland)', main: 'false'},
    {value: '+1-473', label: '+1-473 (Grenada)', main: 'false'},
    {value: '+1-671', label: '+1-671 (Guam)', main: 'false'},
    {value: '+502', label: '+502 (Guatemala)', main: 'false'},
    {value: '+44-1481', label: '+44-1481 (Guernsey)', main: 'false'},
    {value: '+224', label: '+224 (Guinea)', main: 'false'},
    {value: '+245', label: '+245 (Guinea-Bissau)', main: 'false'},
    {value: '+592', label: '+592 (Guyana)', main: 'false'},
    {value: '+509', label: '+509 (Haiti)', main: 'false'},
    {value: '+504', label: '+504 (Honduras)', main: 'false'},
    {value: '+852', label: '+852 (Hong Kong)', main: 'false'},
    {value: '+36', label: '+36 (Hungary)', main: 'false'},
    {value: '+354', label: '+354 (Iceland)', main: 'false'},
    {value: '+91', label: '+91 (India)', main: 'false'},
    {value: '+62', label: '+62 (Indonesia)', main: 'false'},
    {value: '+98', label: '+98 (Iran)', main: 'false'},
    {value: '+964', label: '+964 (Iraq)', main: 'false'},
    {value: '+353', label: '+353 (Ireland)', main: 'false'},
    {value: '+44-1624', label: '+44-1624 (Isle of Man)', main: 'false'},
    {value: '+972', label: '+972 (Israel)', main: 'false'},
    {value: '+39', label: '+39 (Italy)', main: 'false'},
    {value: '+225', label: '+225 (Ivory Coast)', main: 'false'},
    {value: '+1-876', label: '+1-876 (Jamaica)', main: 'false'},
    {value: '+81', label: '+81 (Japan)', main: 'false'},
    {value: '+44-1534', label: '+44-1534 (Jersey)', main: 'false'},
    {value: '+962', label: '+962 (Jordan)', main: 'false'},
    {value: '+7', label: '+7 (Kazakhstan)', main: 'false'},
    {value: '+254', label: '+254 (Kenya)', main: 'false'},
    {value: '+686', label: '+686 (Kiribati)', main: 'false'},
    {value: '+383', label: '+383 (Kosovo)', main: 'false'},
    {value: '+965', label: '+965 (Kuwait)', main: 'false'},
    {value: '+996', label: '+996 (Kyrgyzstan)', main: 'false'},
    {value: '+856', label: '+856 (Laos)', main: 'false'},
    {value: '+371', label: '+371 (Latvia)', main: 'false'},
    {value: '+961', label: '+961 (Lebanon)', main: 'false'},
    {value: '+266', label: '+266 (Lesotho)', main: 'false'},
    {value: '+231', label: '+231 (Liberia)', main: 'false'},
    {value: '+218', label: '+218 (Libya)', main: 'false'},
    {value: '+423', label: '+423 (Liechtenstein)', main: 'false'},
    {value: '+370', label: '+370 (Lithuania)', main: 'false'},
    {value: '+352', label: '+352 (Luxembourg)', main: 'false'},
    {value: '+853', label: '+853 (Macau)', main: 'false'},
    {value: '+389', label: '+389 (Macedonia)', main: 'false'},
    {value: '+261', label: '+261 (Madagascar)', main: 'false'},
    {value: '+265', label: '+265 (Malawi)', main: 'false'},
    {value: '+60', label: '+60 (Malaysia)', main: 'false'},
    {value: '+960', label: '+960 (Maldives)', main: 'false'},
    {value: '+223', label: '+223 (Mali)', main: 'false'},
    {value: '+356', label: '+356 (Malta)', main: 'false'},
    {value: '+692', label: '+692 (Marshall Islands)', main: 'false'},
    {value: '+222', label: '+222 (Mauritania)', main: 'false'},
    {value: '+230', label: '+230 (Mauritius)', main: 'false'},
    {value: '+262', label: '+262 (Mayotte)', main: 'false'},
    {value: '+52', label: '+52 (Mexico)', main: 'false'},
    {value: '+691', label: '+691 (Micronesia)', main: 'false'},
    {value: '+373', label: '+373 (Moldova)', main: 'false'},
    {value: '+377', label: '+377 (Monaco)', main: 'false'},
    {value: '+976', label: '+976 (Mongolia)', main: 'false'},
    {value: '+382', label: '+382 (Montenegro)', main: 'false'},
    {value: '+1-664', label: '+1-664 (Montserrat)', main: 'false'},
    {value: '+212', label: '+212 (Morocco)', main: 'false'},
    {value: '+258', label: '+258 (Mozambique)', main: 'false'},
    {value: '+95', label: '+95 (Myanmar)', main: 'false'},
    {value: '+264', label: '+264 (Namibia)', main: 'false'},
    {value: '+674', label: '+674 (Nauru)', main: 'false'},
    {value: '+977', label: '+977 (Nepal)', main: 'false'},
    {value: '+31', label: '+31 (Netherlands)', main: 'false'},
    {value: '+599', label: '+599 (Netherlands Antilles)', main: 'false'},
    {value: '+687', label: '+687 (New Caledonia)', main: 'false'},
    {value: '+64', label: '+64 (New Zealand)', main: 'false'},
    {value: '+505', label: '+505 (Nicaragua)', main: 'false'},
    {value: '+227', label: '+227 (Niger)', main: 'false'},
    {value: '+234', label: '+234 (Nigeria)', main: 'false'},
    {value: '+683', label: '+683 (Niue)', main: 'false'},
    {value: '+850', label: '+850 (North Korea)', main: 'false'},
    {value: '+1-670', label: '+1-670 (Northern Mariana Islands)', main: 'false'},
    {value: '+47', label: '+47 (Norway)', main: 'false'},
    {value: '+968', label: '+968 (Oman)', main: 'false'},
    {value: '+92', label: '+92 (Pakistan)', main: 'false'},
    {value: '+680', label: '+680 (Palau)', main: 'false'},
    {value: '+970', label: '+970 (Palestine)', main: 'false'},
    {value: '+507', label: '+507 (Panama)', main: 'false'},
    {value: '+675', label: '+675 (Papua New Guinea)', main: 'false'},
    {value: '+595', label: '+595 (Paraguay)', main: 'false'},
    {value: '+51', label: '+51 (Peru)', main: 'false'},
    {value: '+63', label: '+63 (Philippines)', main: 'false'},
    {value: '+64', label: '+64 (Pitcairn)', main: 'false'},
    {value: '+48', label: '+48 (Poland)', main: 'false'},
    {value: '+351', label: '+351 (Portugal)', main: 'false'},
    {value: '+1-787, 1-939', label: '+1-787, 1-939 (Puerto Rico)', main: 'false'},
    {value: '+974', label: '+974 (Qatar)', main: 'false'},
    {value: '+242', label: '+242 (Republic of the Congo)', main: 'false'},
    {value: '+262', label: '+262 (Reunion)', main: 'false'},
    {value: '+40', label: '+40 (Romania)', main: 'false'},
    {value: '+7', label: '+7 (Russia)', main: 'false'},
    {value: '+250', label: '+250 (Rwanda)', main: 'false'},
    {value: '+590', label: '+590 (Saint Barthelemy)', main: 'false'},
    {value: '+290', label: '+290 (Saint Helena)', main: 'false'},
    {value: '+1-869', label: '+1-869 (Saint Kitts and Nevis)', main: 'false'},
    {value: '+1-758', label: '+1-758 (Saint Lucia)', main: 'false'},
    {value: '+590', label: '+590 (Saint Martin)', main: 'false'},
    {value: '+508', label: '+508 (Saint Pierre and Miquelon)', main: 'false'},
    {value: '+1-784', label: '+1-784 (Saint Vincent and the Grenadines)', main: 'false'},
    {value: '+685', label: '+685 (Samoa)', main: 'false'},
    {value: '+378', label: '+378 (San Marino)', main: 'false'},
    {value: '+239', label: '+239 (Sao Tome and Principe)', main: 'false'},
    {value: '+966', label: '+966 (Saudi Arabia)', main: 'false'},
    {value: '+221', label: '+221 (Senegal)', main: 'false'},
    {value: '+381', label: '+381 (Serbia)', main: 'false'},
    {value: '+248', label: '+248 (Seychelles)', main: 'false'},
    {value: '+232', label: '+232 (Sierra Leone)', main: 'false'},
    {value: '+65', label: '+65 (Singapore)', main: 'false'},
    {value: '+1-721', label: '+1-721 (Sint Maarten)', main: 'false'},
    {value: '+421', label: '+421 (Slovakia)', main: 'false'},
    {value: '+386', label: '+386 (Slovenia)', main: 'false'},
    {value: '+677', label: '+677 (Solomon Islands)', main: 'false'},
    {value: '+252', label: '+252 (Somalia)', main: 'false'},
    {value: '+27', label: '+27 (South Africa)', main: 'false'},
    {value: '+82', label: '+82 (South Korea)', main: 'false'},
    {value: '+211', label: '+211 (South Sudan)', main: 'false'},
    {value: '+34', label: '+34 (Spain)', main: 'false'},
    {value: '+94', label: '+94 (Sri Lanka)', main: 'false'},
    {value: '+249', label: '+249 (Sudan)', main: 'false'},
    {value: '+597', label: '+597 (Suriname)', main: 'false'},
    {value: '+47', label: '+47 (Svalbard and Jan Mayen)', main: 'false'},
    {value: '+268', label: '+268 (Swaziland)', main: 'false'},
    {value: '+46', label: '+46 (Sweden)', main: 'false'},
    {value: '+41', label: '+41 (Switzerland)', main: 'false'},
    {value: '+963', label: '+963 (Syria)', main: 'false'},
    {value: '+886', label: '+886 (Taiwan)', main: 'false'},
    {value: '+992', label: '+992 (Tajikistan)', main: 'false'},
    {value: '+255', label: '+255 (Tanzania)', main: 'false'},
    {value: '+66', label: '+66 (Thailand)', main: 'false'},
    {value: '+228', label: '+228 (Togo)', main: 'false'},
    {value: '+690', label: '+690 (Tokelau)', main: 'false'},
    {value: '+676', label: '+676 (Tonga)', main: 'false'},
    {value: '+1-868', label: '+1-868 (Trinidad and Tobago)', main: 'false'},
    {value: '+216', label: '+216 (Tunisia)', main: 'false'},
    {value: '+90', label: '+90 (Turkey)', main: 'false'},
    {value: '+993', label: '+993 (Turkmenistan)', main: 'false'},
    {value: '+1-649', label: '+1-649 (Turks and Caicos Islands)', main: 'false'},
    {value: '+688', label: '+688 (Tuvalu)', main: 'false'},
    {value: '+1-340', label: '+1-340 (U.S. Virgin Islands)', main: 'false'},
    {value: '+256', label: '+256 (Uganda)', main: 'false'},
    {value: '+380', label: '+380 (Ukraine)', main: 'false'},
    {value: '+971', label: '+971 (United Arab Emirates)', main: 'false'},
    {value: '+44', label: '+44 (United Kingdom)', main: 'false'},
    {value: '+1', label: '+1 (United States)', main: 'false'},
    {value: '+598', label: '+598 (Uruguay)', main: 'false'},
    {value: '+998', label: '+998 (Uzbekistan)', main: 'false'},
    {value: '+678', label: '+678 (Vanuatu)', main: 'false'},
    {value: '+379', label: '+379 (Vatican)', main: 'false'},
    {value: '+58', label: '+58 (Venezuela)', main: 'false'},
    {value: '+84', label: '+84 (Vietnam)', main: 'false'},
    {value: '+681', label: '+681 (Wallis and Futuna)', main: 'false'},
    {value: '+212', label: '+212 (Western Sahara)', main: 'false'},
    {value: '+967', label: '+967 (Yemen)', main: 'false'},
    {value: '+260', label: '+260 (Zambia)', main: 'false'},
    {value: '+263', label: '+263 (Zimbabwe)', main: 'false'},
  ]