export const motivation = [
    { text: "Os problemas são oportunidades para se mostrar o que sabe.", author: "Duke Ellington" },
    { text: "Nossos fracassos, às vezes, são mais frutíferos do que os êxitos.", author: "Henry Ford" },
    { text: "Tente de novo. Fracasse de novo. Mas fracasse melhor.", author: "Samuel Beckett" },
    { text: "É costume de um tolo, quando erra, queixar-se dos outros. É costume de um sábio queixar-se de si mesmo.", author: "Sócrates" },
    { text: "O verdadeiro heroísmo consiste em persistir por mais um momento, quando tudo parece perdido.", author: "W. F. Grenfel" },
    { text: "Cada cliente é como se fosse primeiro e único.", author: "Norman Bawes" },
    { text: "Mesmo que já tenhas feito uma longa caminhada, há sempre um novo caminho a fazer.", author: "Santo Agostinho" },
    { text: "Vender é construir uma ponte entre você e seu cliente e fazê-lo atravessar para o seu lado.", author: "Ciclo dos Profissionais de Venda" },
    { text: "Na prosperidade, nossos amigos nos conhecem; na adversidade, nós é que conhecemos nossos amigos.", author: "Churton Collins" },
    { text: "A felicidade não está em fazer o que a gente quer, e sim querer o que a gente faz.", author: "Jean Paul Sartre" },
    { text: "Nada acontece a menos que sonhemos antes.", author: "Carl Sandburg" },
    { text: "É sempre divertido fazer o impossível.", author: "Walt Disney" },
    { text: "A coisa mais cara é transformar um cliente insatisfeito em satisfeito.", author: "Jan Carlzon" },
    { text: "Experiência é o nome que cada um dá a seus erros.", author: "Oscar Wilde" },
    { text: "Lembre sempre que a sua vontade de triunfar é mais importante do que qualquer outra coisa.", author: "Abraham Lincoln" },
    { text: "Prefiro os erros do entusiasmo à indiferença da sabedoria.", author: "Anatole France" },
    { text: "Na realidade, vendas e serviços são inseparáveis.", author: "Carter Brow" },
    { text: "A arte de ser ora audacioso, ora prudente, é a arte de vencer.", author: "Napoleão Bonaparte" },
    { text: "Seja corajoso. Mesmo que você não seja, finja ser. Ninguém nota a diferença.", author: "H. Jackson Brown Jr." },
    { text: "Não somos responsáveis apenas pelo que fazemos, mas também pelo que deixamos de fazer.", author: "Moliere" },
    { text: "A estratégia de marketing começa, termina, vive e morre com o cliente.", author: "Michael Gerber" },
    { text: "Quando você contrata pessoas mais inteligentes do que você, prova que é mais inteligente do que elas.", author: "R. H. Grant" },
    { text: "O talento vence jogos, mas só o trabalho em equipe vence campeonatos.", author: "Michael Jordan" },
    { text: "Um negócio nunca é bom se com ele conseguimos um inimigo.", author: "Hugh Prather" },
    { text: "Um objetivo nada mais é do que um sonho com limite de tempo.", author: "Joel L. Griffith" },
    { text: "Sorte é o que acontece quando a preparação encontra a oportunidade.", author: "Elmer Letterman" },
    { text: "O mercado dita inovações. Quem não segue vira peça de museu.", author: "Phill Knight" },
    { text: "O único lugar que o sucesso vem antes do trabalho é no dicionário.", author: "Vidal Sasson" },
    { text: "Se você quiser ir daqui para lá no mundo dos negócios, não encontrará nenhuma linha reta para levá-lo.", author: "William Ahmanson" },
    { text: "Integridade é a essência de todo negócio.", author: "R. Buckminster Fuller" },
    { text: "Existe o risco que você jamais pode correr. Existe o risco que você jamais pode deixar de correr.", author: "Peter Drucker" },
    { text: "As duas coisas mais importantes não aparecem no balanço da empresa: sua reputação e o seu time.", author: "Henry Ford, adaptação" },
    { text: "A qualidade do seu trabalho tem tudo a ver com a qualidade da sua vida.", author: "Orison Swett Marden" },
    { text: "Nenhuma empresa pode ter sucesso tentando tudo para todos.", author: "Michael Treacy" },
    { text: "Nunca se esqueça de um cliente; e nunca deixe que um cliente esqueça você.", author: "Walter Reuther" },
    { text: "Somos o que repetidamente fazemos. Portanto, a excelência não é um feito, é um hábito.", author: "Aristóteles" },
    { text: "Persistência é irmã gêmea da excelência. Uma é mãe da qualidade, a outra a mãe do tempo.", author: "Marabel Morgan" },
    { text: "O propósito de uma companhia é criar e manter o cliente.", author: "Theodoro Levitt" },
    { text: "Comemore os seus sucessos. Veja com humor os seus fracassos.", author: "Sam Walton" },
    { text: "Autorrespeito, autoconhecimento e autocontrole conduzem a vida ao poder supremo.", author: "Alfred Tennyson" },
    { text: "É tentando o impossível que se chega à realização do possível.", author: "Henri Barbusse" },
    { text: "Ganharão o jogo empresas que têm como missão exceder as expectativas dos clientes.", author: "Richard Whiteley" },
    { text: "Toda empresa precisa ter gente que erra, que não tem medo de errar e que aprende com erro.", author: "Bill Gates" },
    { text: "A confiança em si mesmo é o primeiro segredo do sucesso.", author: "Ralph Waldo Emerson" },
    { text: "Aquele que pretende ser um líder tem que ser uma ponte.", author: "Provérbio Galês" },
    { text: "Sempre que se vê um empreendimento de sucesso é porque alguém antes tomou uma decisão destemida.", author: "Peter Ducker" },
    { text: "Serviços aos clientes é uma estratégia de marketing.", author: "John Tschohl" },
    { text: "Muda tuas ideias e mudarás teu mundo.", author: "Norman Vincent Peale" },
    { text: "Sua tarefa como líder é criar uma atmosfera que transforme o antagonismo em energia criativa.", author: "John Kao" },
    { text: "A publicidade traz os clientes até a porta; mas o mau serviço envia eles direto para fora.", author: "John Tschohl" },
    { text: "Único cliente bom é o cliente feliz. Lembre-se: clientes felizes adoram gastar dinheiro.", author: "Daryl Bernstein" },
    { text: "Devemos prometer somente aquilo que podemos entregar e entregar mais do que prometemos.", author: "Jean Rozwadowski" },
    { text: "Nada de importante no mundo foi realizado sem paixão.", author: "Georg Wilhelm" },
    { text: "Quem tem a obrigação de visualizar o futuro não é o cliente.", author: "Célia Chaim" },
    { text: "Profissional nota 10 é aquele que tem 2 pontos de esforço, 3 pontos de talento e 5 pontos de caráter.", author: "Roland Barthes" },
    { text: "Uma das melhores maneiras de convencer os outros é ouvindo. Ouça todos.", author: "Dean Rusk" },
    { text: "O importante é mudar sempre, mesmo que estejamos crescendo e ganhando o jogo.", author: "Masaaki Imai" },
    { text: "Sempre que você vai encontrar um cliente você é a empresa.", author: "Barrie Hopson e Mike Scally" },
    { text: "Se não puder destacar-se pelo talento, vença pelo esforço.", author: "Dave Weinbaum" },
    { text: "Em busca do ótimo não se faz o bom.", author: "Segundo Mandamento da TAM" },
    { text: "Se existe uma forma de fazer melhor, descubra-a.", author: "Thomas Edison" },
    { text: "Fechar os olhos e os ouvidos para o cliente é uma loucura. É um suicídio empresarial.", author: "Sérgio Almeida" },
    { text: "Não deixe o ruído das opiniões dos outros abafar a sua própria voz interior.", author: "Steve Jobs" },
    { text: "Somente os que ousam errar muito podem realizar muito.", author: "John F. Kennedy" },
    { text: "Aceite os desafios para que possa sentir o sabor da vitória.", author: "General George S. Patton" },
    { text: "A sorte favorece a mente preparada.", author: "Louis Pasteur" },
    { text: "Quando os momentos da verdade não são gerenciados, o serviço regride até a mediocridade.", author: "Karl Albrecht" },
    { text: "Metas são necessárias não só para nos motivar, mas para nos manter vivos.", author: "Robert H. Schuller" },
    { text: "Pessoas com meta têm sucesso pois sabem onde estão indo.", author: "Earl Nightingate" },
    { text: "A pessoa comum é exigente com os outros. A superior é exigente consigo mesmo.", author: "Marco Aurélio, adaptado" },
    { text: "Não há sucesso sem dificuldade.", author: "Sófocles" },
    { text: "Os clientes julgam os serviços pela maneira que são tratados por aqueles com quem tem contato.", author: "Carl Sewell" },
    { text: "Um grande prazer na vida é fazer aquilo que dizem que você não é capaz de fazer.", author: "Walter Gagehot" },
    { text: "Toda glória advém de ousar começar.", author: "Eugene F. Ware" },
    { text: "Todas as pequenas coisas, juntas, formam uma base de clientes fiéis e mais lucrativas.", author: "Bruce Hammonds" },
    { text: "A pessoa que não acredita em si mesmo não acredita em mais nada.", author: "Roy L. Smith, adaptado" },
    { text: "Grandes mentes estão prontas não apenas para explorar oportunidades, mas para criá-las.", author: "Cotton" },
    { text: "O primeiro passo indispensável para conseguir coisas na vida é decidir o que você quer.", author: "Ben Stein" },
    { text: "A percepção quando chega a ser julgada por outros é a realidade.", author: "Jack Lowenstein" },
    { text: "O pior fracassado do mundo é aquele que perdeu o entusiasmo.", author: "H. W. Arnold" },
    { text: "A maior recompensa pelo trabalho não é o que a pessoa ganha, é o que ela se torna através dele.", author: "John Ruskin" },
    { text: "Quando as expectativas aumentam inicia-se um ciclo interminável e contínuo de melhoria.", author: "Steven Hronec" },
    { text: "Aquele que cometeu um erro e não corrigiu está cometendo outro erro.", author: "Confúcio" },
    { text: "A vitória sempre foi de quem nunca duvidou dela.", author: "Raul Follerean" },
    { text: "Os satisfeitos nada mais fazem. Os insatisfeitos são os únicos propulsores do mundo.", author: "Walter Savage Landor" },
    { text: "Todas as coisas são possíveis àqueles que creem.", author: "S. Marcos, 11:23" },
    { text: "O problema é que a maioria das pessoas prefere um elogio que prejudique do que uma crítica que beneficie.", author: "Norman Vincent Peale" },
    { text: "A decepção surge da disparidade entre a expectativa de uma experiência agradável e a experiência real.", author: "Albert Hirschman" },
    { text: "Prefiro a angústia da busca do que a paz da acomodação.", author: "Dom Resende Costa" },
    { text: "Os únicos limites das pessoas são o tamanho de suas ideias e o grau de sua dedicação.", author: "F. Veiga, adaptado" },
    { text: "Conhecimento não é aquilo que você sabe, mas o que você faz com aquilo que sabe.", author: "Aldous Huxley" },
    { text: "Fidelidade do cliente é a chave para lucratividade e crescimento futuro.", author: "Rick Tate" },
    { text: "Critica o que fazes, e não faças o que criticas.", author: "Provérbio Árabe" },
    { text: "O que merece ser feito, merece ser bem feito.", author: "Lord Chesterfield" },
    { text: "Não encontre defeitos, encontre soluções. Qualquer um sabe queixar-se.", author: "Henry Ford" },
    { text: "Para evitar críticas: não faça nada, não diga nada, não seja nada.", author: "Elbert Hubbard" },
    { text: "As pessoas abominam a impessoalidade do negócio.", author: "Marcos Gouvêa de Souza" },
    { text: "Nunca aceite o ‘não’ como resposta.", author: "J. F. Mitchell" },
    { text: "A natureza nos deu uma língua e dois ouvidos para que ouçamos mais do que falamos.", author: "Diógenes Laércio" },
    { text: "Se você não puder manter, não proponha nada; esta é a regra básica na satisfação do cliente.", author: "Sérgio Almeida" },
    { text: "Feliz aquele que sabe adquirir experiência com o erro dos outros.", author: "Kauto" },
    { text: "Querer ser de seu tempo é já estar ultrapassado.", author: "Eugène Ionesco" },
    { text: "Planeje o seu trabalho hoje para todos os dias trabalhar o seu plano.", author: "Norman Vincent Peale" },
    { text: "Supere a expectativa do cliente com pequenas ações frequentes e não solicitadas.", author: "David Freemantle" },
    { text: "Sucesso é apenas sorte; pergunte para qualquer fracassado.", author: "Earle Wilson" },
    { text: "Destino não é exterior a nós; somos nós que criamos nosso próprio destino dia após dia.", author: "Henry Miller" },
    { text: "O homem que removeu a montanha começou carregando as pedras.", author: "Provérbio chinês" },
    { text: "O gosto amargo da baixa qualidade dura bem mais do que a doçura do preço inferior.", author: "Heinz Rahnan" },
    { text: "A covardia é o medo aceito; a coragem é o medo dominado.", author: "Lecouve" },
    { text: "Todos os dias me levanto para vencer.", author: "Onassis" },
    { text: "Meu sucesso se deve ao fato de me cercar de pessoas competentes.", author: "Enzo Ferrari" },
    { text: "Não atrase o seu progresso com medo de fracassar.", author: "Nathiel Hover" },
    { text: "As pessoas são a força direcional por trás do crescimento.", author: "Business Week" },
    { text: "Quem não tem inteligência para criar tem que ter coragem para copiar.", author: "Sétimo Mandamento da TAM" },
    { text: "Ninguém pode ferir você sem o seu consentimento.", author: "Eleanor Roosvelt" },
    { text: "O verdadeiro risco é não fazer nada.", author: "Denis Waitley" },
    { text: "Aquele que domina os outros é forte; aquele que domina a si mesmo é todo-poderoso.", author: "Lao Tsu" },
    { text: "Faça o que puder, com o que tiver, onde estiver.", author: "Theodore Roosvelt" },
    { text: "A qualidade do serviço e produto é decorrência da qualidade das pessoas.", author: "Claus Moller" },
    { text: "Nossas dúvidas são traidoras e nos fazem perder, por medo de tentar, o que poderíamos ganhar.", author: "William Shakespeare" },
    { text: "Os problemas são apenas oportunidades com roupas de trabalho.", author: "Henry John Kaiser" },
    { text: "Não nos transformamos de uma hora para outra aquilo que não cooperamos para nos tornar.", author: "William J. Bennett" },
    { text: "O que a pessoa pensa a respeito de si mesmo indica o seu destino.", author: "Henry David Thoreau, adaptado" },
    { text: "Decidir o que não fazer é tão importante quanto decidir o que fazer. Isso é verdadeiro para companhias e também para produtos.", author: "Steve Jobs" },
    { text: "O cliente precisa saber que nós nos importamos com ele.", author: "Roberto Maksoud" },
    { text: "Devemos ser a mudança que queremos ver no mundo.", author: "Gandhi" },
    { text: "Você tem que fazer as coisas que pensa não ser capaz de fazer.", author: "Eleanor Roosvelt" },
    { text: "Em toda a iniciativa, considere aonde você poderia chegar.", author: "Publilius Syrus" },
    { text: "Ninguém pode construir uma reputação com base naquilo que ainda vai fazer.", author: "Henry Ford" },
    { text: "A comunicação é a principal fonte de poder pessoal.", author: "Fortune Magazine" },
    { text: "Falhar no planejamento é um planejamento para falhar.", author: "Effie Jones" },
    { text: "Em todas as situações, deve-se considerar o objetivo.", author: "Jean de La Fontaine" },
    { text: "65% dos negócios de uma empresa vêm de clientes já existentes – não de novos.", author: "AMA" },
    { text: "É o motivo que engrandece a ação; é o fazer, não o feito.", author: "Margaret Preston" },
    { text: "Quem vive sem disciplina morre sem honra.", author: "Provérbio islandês" },
    { text: "Mesmo se você estiver no caminho certo será atropelado se ficar sentado nele.", author: "Will Rogers" },
    { text: "Desperdiçar o próprio tempo é uma espécie de suicídio.", author: "George Savile" },
    { text: "A ética dá lucro para a empresa.", author: "Lori Tansey" },
    { text: "O fanatismo consiste em redobrar esforços quando o objetivo for esquecido.", author: "George Santayana" },
    { text: "Se você não sabe para onde vai, provavelmente terminará em algum outro lugar.", author: "Laurence J. Peter" },
    { text: "Os atrasos deixam o cliente com os dentes rangendo.", author: "Fred Wiersema" },
    { text: "Uma jornada de mil quilômetros começa pelo primeiro passo.", author: "Lao Tsu" },
    { text: "Algumas derrotas são mais triunfantes do que vitórias.", author: "Michael de Montaigne" },
    { text: "Nossa vida é o que os nossos pensamentos fazem dela.", author: "Marco Aurélio Antonino" },
    { text: "Quem torna as coisas mais fáceis para os outros, torna as coisas mais fáceis para si.", author: "Ditado asiático" },
    { text: "Custa 6 vezes mais conquistar um novo cliente do que manter um antigo.", author: "Claus Moller" },
    { text: "Seja um parâmetro de qualidade. Algumas pessoas não estão acostumadas a um ambiente onde a excelência é esperada.", author: "Steve Jobs" },
    { text: "Coragem é estar morto de medo e encilhar o cavalo mesmo assim.", author: "John Wayne" },
    { text: "O talento sempre tem consciência de sua própria abundância e não cria objeções em dividir.", author: "Alexander Soljenitsyn" },
    { text: "Não se pode progredir enquanto se ajustam contas.", author: "Dick Armey" },
    { text: "O único bem coletivo é aquele que assegura o bem individual de cada cidadão.", author: "Charles Dickens" },
    { text: "Ouça, ou sua língua vai conservar sua surdez.", author: "Provérbio indígena norte-americano" },
    { text: "O que você dá é o que você recebe.", author: "Eric Berne" },
    { text: "Sucesso é a soma de pequenos esforços repetidos dia sim, e no outro também.", author: "Robert Collier" },
    { text: "É bom ter objetivo para a jornada à frente; mas, no fim, a jornada é o que importa.", author: "Ursula L. Le Guin" },
    { text: "Jamais imponha a sua linguagem às pessoas com as quais você deseja se comunicar.", author: "Abbie Hoffman" },
    { text: "Você tem que escutar os clientes e então agir com base no que eles disseram.", author: "Charles Lazarus" },
    { text: "As pessoas só vêem aquilo que estão preparadas para ver.", author: "Ralph Waldo Emerson" },
    { text: "Quem só conhece o seu lado do problema sabe pouco sobre ele.", author: "John Stuart Mill" },
    { text: "Duas cabeças são melhores do que uma.", author: "John Heywood" },
    { text: "Uma ideia pode virar pó ou mágica, depende do talento que esbarra nela.", author: "William Bernbach" },
    { text: "A empresa que busca encantar o cliente é inquieta e criativa.", author: "Sérgio Almeida" },
    { text: "A oposição traz concórdia. A discórdia vem da mais perfeita harmonia.", author: "Heráclito" },
    { text: "Não busque todas as qualidades em uma pessoa só.", author: "Confúcio" },
    { text: "Ter senso de humor é tão importante quanto ter talento.", author: "Gary Oldman" },
    { text: "Todos nós somos ignorantes, só que em assuntos diferentes.", author: "Will Rogers" },
    { text: "O plano de só uma pessoa pode ser incompleto; o de duas será melhor.", author: "Chuang-tsé, adaptado" },
    { text: "Ninguém jamais ganha uma discussão com o cliente.", author: "Barrie Hopson" },
    { text: "O hoje é aluno do ontem.", author: "Thomas Fuller" },
    { text: "Jamais devemos negociar por medo, mas jamais devemos ter medo de negociar.", author: "John F. Kennedy" },
    { text: "O tratamento deve sempre ser positivo, independente da circunstância.", author: "Fábio Eltz" },
    { text: "Não tenha medo de tempestades, pois estarás aprendendo a manejar o barco.", author: "Louisa May Alcott" },
    { text: "Se você pensa que educação é uma coisa cara, tente a ignorância.", author: "Derek Bok" },
    { text: "A coisa mais difícil é a decisão de agir, o resto é apenas tenacidade.", author: "Amelia Earhart" },
    { text: "O autodesenvolvimento é um dever maior do que o auto-sacrifício.", author: "Elizabeth Cady Stanton" },
    { text: "Grandes descobertas e progressos envolvem a cooperação de várias mentes.", author: "Alexander Graham Bell" },
    { text: "É preciso buscar fatias na multidão.", author: "Sérgio Quartiermeister" },
    { text: "Caia 7 vezes. Levante-se 8.", author: "Provérbio japonês" },
    { text: "Ninguém nasce um gênio; a pessoa se torna um.", author: "Simone de Beauvoir" },
    { text: "Quando eu deixar de ser o que sou, eu irei me tornar o que poderia ser.", author: "Lao Tzu" },
    { text: "Seu tempo é limitado, então não o gaste vivendo a vida de outra pessoa.", author: "Steve Jobs" },
    { text: "A mente humana, expandida por uma ideia nova, jamais retorna à dimensão original.", author: "Oliver Wendell Holmes" },
    { text: "A percepção é um ponto de vista individual. Portanto, não se discute.", author: "Sérgio Almeida" },
    { text: "Você deve guardar um dragão dentro de si. Quando precisar, você deixa o dragão sair.", author: "Anderson Silva" },
    { text: "Eu preferiria morrer de paixão do que de tédio.", author: "Vincent Van Gogh" },
    { text: "Sonhar, afinal, é uma forma de planejamento.", author: "Gloria Steinem" },
    { text: "O segredo do sucesso é a constância do objetivo.", author: "Benjamin Disraeli" },
    { text: "Escreva algo que valha a pena ler, ou faça alguma coisa que valha a pena escrever.", author: "Benjamin Franklin" },
    { text: "Saber ouvir e ter equilíbrio emocional: fundamentais no atendimento ao cliente.", author: "Fela Moscovici" },
    { text: "É preciso ter dúvidas. Só os estúpidos têm uma confiança absoluta em si mesmos.", author: "Orson Welles" },
    { text: "Devemos crer que somos dotados de alguma coisa, e que essa coisa, deve ser atingida a todo custo.", author: "Marie Curie" },
    { text: "Tudo tem beleza. Mas nem todos podem ver.", author: "Confúcio" },
    { text: "Prometa o que não irá cumprir e seus clientes formarão um mau conceito a seu respeito.", author: "Robert Peterson" },
    { text: "Se o índice de falha é de 1 em 1 milhão, o que você responde para esse cliente?.", author: "Pôster da IBM" },
    { text: "Se você deseja que seus filhos acabem bem, gaste o dobro de tempo com eles, e metade do dinheiro.", author: "Abigail Van Buren" },
    { text: "Use bom senso em todas as situações; não espere por regras novas, pois não virão.", author: "Manual da Nordstrom" },
    { text: "Todo mundo tem talento, é só uma questão de se mexer até descobrir qual.", author: "George Lucas" },
    { text: "Quanto mais nos defrontamos com tecnologia, maior nosso anseio por contatos humanos.", author: "John Nasbit" },
    { text: "Bem começado é meio caminho andado.", author: "Provérbio grego" },
    { text: "A mente é tudo. Você se torna aquilo que você pensa.", author: "Buddha" },
    { text: "Uma queixa é alguém avisando que você não o satisfez. E isso é escrito em ouro.", author: "Donald Beaver Jr." },
    { text: "O medo de ousar, ser agressivo ou inovar fechou mais empresas do que a ousadia.", author: "Júlio Ribeiro" },
    { text: "Minha primeira mensagem é: escute, escute e escute o pessoal que faz o trabalho.", author: "H. Ross Perot" },
    { text: "A preguiça caminha tão devagar que a pobreza a alcança com rapidez.", author: "Franklin D. Roosvelt" },
    { text: "Dos clientes insatisfeitos, apenas 5% efetivamente fez uma reclamação.", author: "Denis Walker" },
    { text: "Vá na direção de seus sonhos. Viva a vida que você imaginou.", author: "Henry David Thoreau" },
    { text: "Não existe empresa nota 10 com empregados nota 5.", author: "Marcos Gouvêa de Souza" },
    { text: "Perder tempo é um castigo insuportável.", author: "Quin Guanshu" },
    { text: "Serviços ao cliente não consistem em satisfação, mas sim em deslumbre.", author: "Chip Bell" },
    { text: "Você pode destruir o seu hoje se preocupando com o amanhã.", author: "Janis Joplin" },
    { text: "Todo cliente quer ser tratado como especial, não quer ser ‘mais um'.", author: "Fábio Eltz" },
    { text: "Começar é a parte mais importante de qualquer trabalho.", author: "Platão" },
    { text: "Nossa meta é resolver problemas antes que os clientes saibam que eles existam.", author: "Ron Bern" },
    { text: "Uma boa cabeça e um bom coração formam sempre uma combinação formidável.", author: "Nelson Mandela" },
    { text: "Se você não tem item de controle, você não tem gerência.", author: "Kaoru Ishikawa" },
    { text: "Os colaboradores evitam as queixas pois eles nunca foram instruídos a lidar com elas.", author: "John Tschohl" },
    { text: "O maior prêmio que a vida oferece é trabalhar em algo que valha a pena.", author: "Theodore Roosvelt" },
    { text: "Um bom porta-voz transforma leite desnatado em chantilly.", author: "George Lichtenberg" },
    { text: "Um líder genuíno é motivador: orienta as pessoas, não as dirige; envolve, não as coage.", author: "J. Walters" },
    { text: "A vida não é sobre ter, é sobre dar e ser.", author: "Kevin Kruse" },
    { text: "O resultado final de um serviço é um sentimento.", author: "Karl Albrecht" },
    { text: "O objetivo do marketing de relacionamento é a retenção de clientes.", author: "Terry Vavra" },
    { text: "Aqueles que nada fazem estão sempre dispostos a criticar os que fazem algo.", author: "Paul Deschanel" },
    { text: "Cliente é todo aquele impactado por seus produtos, processos e serviços.", author: "Juran" },
    { text: "As empresas terão de adaptar-se às preferências individuais de cada consumidor ou sucumbirão.", author: "Raimar Richers" },
    { text: "Sente-se sufocado aquele sem um objetivo de vida”.", author: "Fiódor Dostoiévski" },
    { text: "Não critique a pessoa, somente o comportamento.", author: "Claus Moller" },
    { text: "É doce deixar a mente relaxar de vez em quando.", author: "Horácio" },
    { text: "O presente é o único momento que temos para fazer algo.", author: "Ken O’Donnell" },
    { text: "Todo mundo é capaz de dominar uma dor, exceto quem a sente.", author: "William Shakespeare" },
    { text: "Desperdício é tudo aquilo que não representa valor para o cliente.", author: "Richard Whiteley" },
    { text: "A convicção é inútil – a menos que se transforme em conduta.", author: "Thomas Carlyle" },
    { text: "Quanto mais distante o administrador do administrado, menos eficiente a administração.", author: "Phillip Crosby" },
    { text: "A felicidade não é algo pronto. Ela vem de suas próprias ações.", author: "Dalai Lama" },
    { text: "Devemos seguir o exemplo dos rios: dão suas águas ao mar e nunca ficam vazios.", author: "Jefferson Leão de Almeida" },
    { text: "Meu maior poder como consultor é ser ignorante e fazer algumas perguntas.", author: "Peter Drucker" },
    { text: "O cliente é alguém que nos traz suas necessidades.", author: "L. L. Bean Inc" },
    { text: "O pior erro que você pode cometer em sua vida é ficar com medo de cometer algum erro.", author: "Elbert Hubbard" },
    { text: "Se houver uma opção melhor, os clientes mudarão de fornecedor.", author: "Catherine Romano" },
    { text: "O alvo na vida não deve ser ultrapassar os outros, mas sim ultrapassar a nós mesmos.", author: "M. J. Babcock" },
    { text: "Quando são cometidos lapsos nos serviços, as vendas caem.", author: "Terrell Harris" },
    { text: "Jamais prometa mais do que pode fazer.", author: "Publilius Syrus" },
    { text: "Se você for direto e honesto com seus clientes eles o tratarão como amigo.", author: "Milton Moore" },
    { text: "Não arriscar nada é arriscar tudo.", author: "Cesare Cantú" },
    { text: "Não se comprometa a fazer o que não é capaz, mas preocupe-se em manter sua promessa.", author: "George Washington" },
    { text: "Quando você atende ao telefone, a imagem da sua empresa é percebida do outro lado da linha.", author: "Video Business Magazine" },
    { text: "Um investimento em conhecimento sempre paga o maior juro.", author: "Benjamin Franklin" },
    { text: "Contrate o tipo de pessoa capaz de construir relações sólidas com os clientes.", author: "Lunda Goldzimer" },
    { text: "Não abandone suas três grandes e inabaláveis amigas: a intuição, a inocência e a fé.", author: "George Gurdjieff" },
    { text: "Quem sabe faz a hora, não espera acontecer.", author: "Geraldo Vandré" },
    { text: "A única coisa que sabemos sobre o futuro é que ele será diferente.", author: "Peter Drucker" },
    { text: "Quando você perde um cliente, perde transações futuras e propaganda boca a boca.", author: "David Clutterbuck" },
    { text: "Eu me sentia derrotado por não ter sapatos, até o dia que encontrei um homem que não tinha pés.", author: "Harols Abbott" },
    { text: "Uma empresa que não escuta o seu cliente está fadada ao insucesso.", author: "Paulo Apsan" },
    { text: "Se você não é notado, você não tem nada.", author: "Leo Burnett" },
    { text: "Não são os anos de sua vida que contam. É a vida em seus anos.", author: "Abraham Lincoln" },
    { text: "O marketing de relacionamento reduz o impacto dos esforços feitos pela concorrência.", author: "Don Peppers" },
    { text: "É melhor ser invejado do que lastimado.", author: "Heródoto" },
    { text: "Você pode construir o mais belo lugar do mundo, mas serão as pessoas que tornarão realidade o sonho.", author: "Walt Disney" },
    { text: "Não existe técnica de comunicação mais relevante do que a naturalidade.", author: "Reinaldo Polito" },
    { text: "Na vida sempre fazemos escolhas. Ainda que escolhemos não escolher.", author: "Carmen Miranda" },
    { text: "A melhor maneira de vender é facilitando a compra.", author: "Sales and Marketing Magazine" },
    { text: "A cortesia tem um grande poder, e não custa nada.", author: "Samuel Smiles" },
    { text: "Você pode ficar desapontado se falhar, mas já está derrotado se não tentar.", author: "Beverly Sills" },
    { text: "Se souber o nome do cliente, use em sua saudação.", author: "Texas American Bank" },
    { text: "Ofereça ao cliente algo que vale a pena e ele pagará o que vale.", author: "Tom Peter e Nancy Austin" },
    { text: "Seja hoje melhor do que ontem e, amanhã, melhor do que hoje.", author: "Constantino C. Vigil" },
    { text: "O acordo é o último recurso dos que não têm imaginação.", author: "Oscar Wilde" },
    { text: "Lucro é vital, mas o cliente vem antes. Sem ele não há lucro.", author: "Richard Whiteley" },
    { text: "Sonhe grande e se atreva a falhar.", author: "Norman Vaughan" },
    { text: "Eu sempre uso o produto dos meus clientes; não é bajulação, mas boas maneiras.", author: "David Ogilvy" },
    { text: "Traga novas ideias e trate-as regiamente, pois uma delas pode ser o rei.", author: "Mark van Doren" },
    { text: "Quem quer agradar a todo mundo não agrada a ninguém.", author: "Dito popular" },
    { text: "Leve é a tarefa quando muitos dividem o trabalho.", author: "Samuel Johnson" },
    { text: "Você seria seu próprio cliente?.", author: "Linda Goldzimer" },
    { text: "Ganhar não é tudo, mas querer ganhar é.", author: "Vince Lombardi" },
    { text: "Aquilo que você não pode medir não pode ser aperfeiçoado.", author: "John Young" },
    { text: "O conveniente e o correto raramente são a mesma coisa.", author: "Charles Brower" },
    { text: "A confiabilidade do serviço é fator mais importante de todos, duas vezes acima dos demais.", author: "Gordon Spainhower" },
    { text: "Uma pessoa que nunca cometeu um erro, nunca tentou nada de novo.", author: "Albert Einstein" },
    { text: "Você precisa ver seus erros para poder fazer algo a respeito deles.", author: "Claus Moller" },
    { text: "Se os ventos não vão servir, leve os remos.", author: "Provérbio norte-americano" },
    { text: "Ninguém cativa um cliente sabendo apenas o nome e onde ele mora.", author: "Sérgio Quartiermeister" },
    { text: "O trabalho de adivinhação torna inevitável a insatisfação.", author: "John Tschohol" },
    { text: "Quando deixamos de contribuir, começamos a morrer.", author: "Eleanor Roosvelt" },
    { text: "A chave do negócio é analisar cada cliente antes de servi-lo.", author: "Laurent Svadon" },
    { text: "O problema não é o problema. O problema é a atitude com relação ao problema.", author: "Kelly Young" },
    { text: "Verifique seus sentimentos à porta do escritório.", author: "Tom Peters" },
    { text: "Diga ‘obrigado’ sempre que tiver uma oportunidade.", author: "Carl Sewell" },
    { text: "Você nunca vai chegar ao seu destino se você parar e atirar pedras em cada cão que late.", author: "Winston Churchill" },
    { text: "A confiança dos clientes é o ativo mais valioso de uma companhia de serviços.", author: "Leonard Berry" },
    { text: "Não ergas um edifício sem fortes alicerces ou viverás com medo.", author: "Sabedoria Persa" },
    { text: "Trate seus funcionários assim como quer que eles tratem seus melhores clientes.", author: "Stephen Covey" },
    { text: "Somos damas e cavalheiros servindo damas e cavalheiros.", author: "Lema do Ritz-Carlton Hotel" },
    { text: "Esforce-se para não ser um sucesso, mas sim para ser valioso.", author: "Albert Einstein" },
    { text: "Projete um sistema que equilibre processo, produto e medidas de satisfação.", author: "Peter Francese" },
    { text: "Ouça qualquer um que tenha uma ideia original. Encoraje-o. Deixe as pessoas continuarem suas ideias.", author: "William McKnight" },
    { text: "Satisfaça o cliente no começo, no fim e sempre.", author: "Phillip Crosby" },
    { text: "Eu não falhei no teste. Eu só encontrei 100 maneiras de fazer errado.", author: "Benjamin Franklin" },
    { text: "Quer segurança em um emprego? Faça um cliente feliz.", author: "Júlio Lobos" },
    { text: "O essencial é invisível aos olhos.", author: "Antoine de Saint-Exupéry" },
    { text: "Conheça seus clientes como sua família, satisfaça-os e você terá sucesso.", author: "Richard Whiteley" },
    { text: "Um cliente que reclama é um consultor. Aponta o que melhorar e não cobra nada por isso.", author: "Sérgio Almeida" },
    { text: "Nunca é tarde demais para ser o que você poderia ter sido.", author: "George Eliot" },
    { text: "Não existe melhor publicidade do que um cliente satisfeito.", author: "Jay Curry e Ludovic Stora" },
    { text: "Gerenciar não é mais a direção da coisa, mas o aperfeiçoamento das pessoas.", author: "Alvin Toffler" },
    { text: "A pessoa no comando não pode apenas pregar. Ela precisa liderar com exemplos.", author: "Carl Sewell" },
    { text: "A marca é um símbolo que identifica uma promessa na cabeça do cliente.", author: "Larry Light" },
    { text: "Não há saber mais ou saber menos: há saberes diferentes.", author: "Paulo Freire" },
    { text: "O papel do gerente é de orientar, energizar e estimular.", author: "Jack Welck" },
    { text: "Se você quiser se levantar, levante outra pessoa.", author: "Booker T. Washington" },
    { text: "Você pode tosquiar o carneiro por muitos anos, mas poderá esfolá-lo somente uma vez.", author: "John Sewell" },
    { text: "Quanto maior a dificuldade maior é o mérito de superá-la.", author: "H. W. Beecher" },
    { text: "Cuidar o lado emocional do cliente é mais importante do que consertar um equipamento.", author: "Bill Bleuel" },
    { text: "O cliente compra uma promessa e são obrigados a confiar que a empresa ira cumpri-la.", author: "Leonard Berry" },
    { text: "A questão não é quem vai me deixar; mas sim, quem vai me impedir.", author: "Ayn Rand" },
    { text: "Certifique-se de que suas palavras e seus atos estão em harmonia.", author: "Claus Moller" },
    { text: "As pessoas estão atentas a você. A qualidade está no seu coração.", author: "Steven Leonard Jr." },
    { text: "Nossa paciência conquistará mais do que a nossa força.", author: "Edmund Burke" },
    { text: "Se os clientes não estão reclamando você está perdendo a oportunidade de ser melhor.", author: "Karl Albrecht" },
    { text: "Você pode mudar sem crescer, mas não pode crescer sem mudar.", author: "Larry Wilson" },
    { text: "Agradeça com um sorriso a presença do cliente.", author: "Texas American Bank" },
    { text: "Você não crescerá a não ser que tente algo além daquilo que já domina.", author: "Ronald Osborn" },
    { text: "Faça a voz do cliente ecoar em toda a empresa.", author: "Richard Whiteley" },
    { text: "Tudo o que você sempre quis está do outro lado do seu medo.", author: "George Addair" },
    { text: "Nada contribui tanto para clarear a mente do que um objetivo claro.", author: "Marry W. Shelley" },
    { text: "Um único pensamento pode revolucionar sua vida.", author: "Norman Vincent Peale" },
    { text: "Todo o marketing da sua empresa pode ser anulado por um único empregado grosseiro.", author: "John Tschohl" },
    { text: "Quando compreende-se o que o cliente deseja, torna-se mais fácil atendê-lo.", author: "Fábio Eltz" },
    { text: "Só serão felizes aqueles que procurarem e encontrarem um meio de servir.", author: "Albert Schweitzer" },
    { text: "A percepção que o cliente tem em relação ao seu produto é o que determina sua satisfação.", author: "Linda Goldzimer" },
    { text: "O mais corajoso dos atos ainda é pensar com a própria cabeça.", author: "Coco Chanel" },
    { text: "A coisa mais importante para o cliente é: você fez aquilo que prometeu?.", author: "Carl Sewell" },
    { text: "Nada que valha a pena acontece a alguém exceto o resultado do trabalho árduo.", author: "Booker T. Washington" },
    { text: "A forma mais barata de manter clientes satisfeitos é servi-los bem desde o começo.", author: "Fortune Magazine" },
    { text: "A melhor forma de ter clientes para sempre é oferecer a eles um negócio irrecusável.", author: "Don Peppers" },
    { text: "Tenho aprendido ao longo dos anos que, quando a mente está pronta, isso diminui o medo.", author: "Rosa Parks" },
    { text: "O cliente é o chefe.", author: "Lema da Bio-Lab" },
    { text: "Mestre não é quem sempre ensina, mas quem de repente aprende.", author: "João Guimarães Rosa" },
    { text: "Se não agrega valor, pare; se faz sentido para o cliente, prossiga.", author: "Bob Harbage" },
    { text: "Os clientes sempre reconhecem quando alguém saiu do seu caminho para ajudá-los.", author: "Leonard Berry" },
    { text: "Espíritos grandiosos sempre encontraram oposição violenta de mentes medíocres.", author: "Albert Einstein" },
    { text: "A busca da qualidade é um estado de espírito.", author: "Cesare Romiti" },
    { text: "O que é realmente necessário em empresa que presta serviço são pessoas que gostem de pessoas.", author: "Frank Petro" },
    { text: "É importante aprender a não se aborrecer com opiniões diferentes das suas.", author: "Bertrand Russell" },
    { text: "O melhor vendedor do mundo é um cliente encantado.", author: "Sérgio Almeida" },
    { text: "Ter problemas na vida é inevitável. Ser derrotado por eles é opcional.", author: "Roger Crowford" },
    { text: "Limitar o foco ao cliente provoca uma espécie de cegueira para inovações.", author: "Paulo Apsan" },
    { text: "A prestação de bons serviços nunca é acidental.", author: "Jaclyn Jeffrey" },
    { text: "Você nunca pode atravessar o oceano até que você tenha coragem de perder de vista a costa.", author: "Cristóvão Colombo" },
    { text: "O que pode sair errado? Essa é a pergunta a se fazer ao projetar os seus sistemas”.", author: "Carl Sewell" },
    { text: "Toma conta do teu negócio ou ele tomará conta de ti.", author: "Benjamin Franklin" },
    { text: "A satisfação do cliente é uma relação entre o que ele viu e o que ele esperava ver.", author: "Sérgio Almeida" },
    { text: "Perde tudo quem perde o momento certo.", author: "Provérbio espanhol" },
    { text: "Combata a mediocridade – em si e nos outros.", author: "Claus Moller" },
    { text: "Lembre-se que não conseguir o que você quer é algumas vezes um lance de sorte.", author: "Dalai Lama" },
    { text: "Uma atitude vitoriosa é meio caminho andado para o sucesso.", author: "Arthur Riedel" },
    { text: "Agregar valor é resolver os problemas do cliente.", author: "James Belasco" },
    { text: "Fazer rápido obriga-o a fazer certo logo na primeira vez.", author: "John Young" },
    { text: "Devemos preferir as queixas aos cumprimentos.", author: "Donald Beaver Jr." },
    { text: "Todos os sorrisos do mundo não irão ajudá-lo se o produto ou serviço não for o que o cliente deseja.", author: "Carl Sewell" },
    { text: "Um serviço excelente é uma estratégia de lucro.", author: "Leonard Berry" },
    { text: "Você pode tudo se tiver entusiasmo.", author: "Henry Ford" },
    { text: "Não sei aonde vou, mas já estou no caminho.", author: "Carl Sandburg" },
    { text: "Conte a verdade – ou não conte nada. Ninguém gosta de gente mentirosa.", author: "Fortune Magazine" },
    { text: "O insucesso é uma oportunidade para recomeçar com mais inteligência.", author: "Henry Ford" },
];