export const rgie_authorities = [
    {value: 'ABNC', label: 'ABNC - Academia Brasileira de Neurocirurgia', main: false},
    {value: 'CGPI', label: 'CGPI - Coordenação-Geral de Privilégios e Imunidades', main: false},
    {value: 'CGPI/DUREX/DPF', label: 'CGPI/DUREX/DPF - Coordenação Geral de Polícia de Imigração da Polícia Federal', main: false},
    {value: 'CGPMAF', label: 'CGPMAF - Coordenadoria Geral de Polícia Marítima, Aeronáutica e de Fronteiras', main: false},
    {value: 'CNIG', label: 'CNIG - Conselho Nacional de Imigração', main: false},
    {value: 'CNT', label: 'CNT - Carteira Nacional de Habilitação', main: false},
    {value: 'CNT', label: 'CNT - Carteira Nacional de Habilitação', main: false},
    {value: 'CTPS', label: 'CTPS - Carteira de Trabaho e Previdência Social', main: false},
    {value: 'DIC', label: 'DIC - Diretoria de Identificação Civil', main: false},
    {value: 'DPF', label: 'DPF - Polícia Federal', main: false},
    {value: 'EST', label: 'EST - Carteira de Estrangeiro', main: false},
    {value: 'FGTS', label: 'FGTS - Fundo de Garantia do Tempo de Serviço', main: false},
    {value: 'IFP', label: 'IFP - Instituto Félix Pacheco', main: false},
    {value: 'IML', label: 'IML - Instituto Médico-Legal', main: false},
    {value: 'IPF', label: 'IPF - Instituto Pereira Faustino', main: false},
    {value: 'MAE', label: 'MAE - Ministério da Aeronáutica', main: false},
    {value: 'MEX', label: 'MEX - Ministério do Exército', main: false},
    {value: 'MMA', label: 'MMA - Ministério da Marinha', main: false},
    {value: 'MTE', label: 'MTE - Ministério do Trabalho e Emprego', main: false},
    {value: 'PC', label: 'PC - Policia Civil', main: false},
    {value: 'PM', label: 'PM - Polícia Militar', main: false},
    {value: 'POF', label: 'POF - Polícia Federal', main: false},
    {value: 'POM', label: 'POM - Polícia Militar', main: false},
    {value: 'SDS', label: 'SDS - Secretaria de Defesa Social', main: false},
    {value: 'SECC', label: 'SECC - Secretaria de Estado da Casa Civil', main: false},
    {value: 'SEJUSP', label: 'SEJUSP - Secretaria de Estado de Justiça e Segurança Pública', main: false},
    {value: 'SES', label: 'SES - Carteira de Estrangeiro', main: false},
    {value: 'SESP', label: 'SESP - Secretaria de Estado da Segurança Pública', main: false},
    {value: 'SJS', label: 'SJS - Secretaria da Justiça e Segurança', main: false},
    {value: 'SJTC', label: 'SJTC - Secretaria da Justiça do Trabalho e Cidadania', main: false},
    {value: 'SJTS', label: 'SJTS - Secretaria da Justiça do Trabalho e Segurança', main: false},
    {value: 'SNJ', label: 'SNJ - Secretaria Nacional de Justiça / Departamento de Estrangeiros', main: false},
    {value: 'SPTC', label: 'SPTC - Secretaria de Polícia Técnico-Científica', main: false},
    {value: 'SSP', label: 'SSP - Secretaria de Segurança Pública', main: true},
    {value: 'ZZZ', label: 'ZZZ - Outros (inclusive exterior)', main: false},
];